// Code generated by scripts/migrate from extern/tstl/test/unit/builtins/async-await.spec.ts. DO NOT EDIT.
package tstltest

import (
	"testing"

	"github.com/realcoldfry/tslua/internal/transpiler"
)

func TestEval_AsyncAwait(t *testing.T) {
	t.Parallel()

	batchExpectFunctions(t, []funcTestCase{
		{"high amount of chained awaits doesn't cause stack overflow", `let result = "not executed";

        async function delay() {
            return;
        }

        async function loop() {
            try {
                for (let i = 0; i < 500000; ++i) {
                    await delay();
                }
                result = "success";
            } catch (e: any) {
                result = e;
            }
        }

        loop();

        return result;`, `"success"`, `local ____lualib = require("lualib_bundle")
local __TS__AsyncAwaiter = ____lualib.__TS__AsyncAwaiter
local __TS__Await = ____lualib.__TS__Await
local ____exports = {}
function ____exports.__main(self)
    local result = "not executed"
    local function delay(self)
        return __TS__AsyncAwaiter(function(____awaiter_resolve)
            return ____awaiter_resolve(nil)
        end)
    end
    local function loop(self)
        return __TS__AsyncAwaiter(function(____awaiter_resolve)
            local ____try = __TS__AsyncAwaiter(function()
                do
                    local i = 0
                    while i < 500000 do
                        __TS__Await(delay(nil))
                        i = i + 1
                    end
                end
                result = "success"
            end)
            __TS__Await(____try.catch(
                ____try,
                function(____, e)
                    result = e
                end
            ))
        end)
    end
    loop(nil)
    return result
end
return ____exports`, false, false},
		{"can await already resolved promise", `const result: number[] = [];
        async function abc() {
            return await Promise.resolve(30);
        }
        abc().then(value => result.push(value));

        return result;`, `{30}`, `local ____lualib = require("lualib_bundle")
local __TS__Promise = ____lualib.__TS__Promise
local __TS__AsyncAwaiter = ____lualib.__TS__AsyncAwaiter
local __TS__Await = ____lualib.__TS__Await
local ____exports = {}
function ____exports.__main(self)
    local result = {}
    local function abc(self)
        return __TS__AsyncAwaiter(function(____awaiter_resolve)
            return ____awaiter_resolve(
                nil,
                __TS__Await(__TS__Promise.resolve(30))
            )
        end)
    end
    local ____self_1 = abc(nil)
    ____self_1["then"](
        ____self_1,
        function(____, value)
            local ____temp_0 = #result + 1
            result[____temp_0] = value
            return ____temp_0
        end
    )
    return result
end
return ____exports`, false, false},
		{"can await already rejected promise", `const result: string[] = [];
        async function abc() {
            return await Promise.reject("test rejection");
        }
        abc().catch(reason => result.push(reason));

        return result;`, `{"test rejection"}`, `local ____lualib = require("lualib_bundle")
local __TS__Promise = ____lualib.__TS__Promise
local __TS__AsyncAwaiter = ____lualib.__TS__AsyncAwaiter
local __TS__Await = ____lualib.__TS__Await
local ____exports = {}
function ____exports.__main(self)
    local result = {}
    local function abc(self)
        return __TS__AsyncAwaiter(function(____awaiter_resolve)
            return ____awaiter_resolve(
                nil,
                __TS__Await(__TS__Promise.reject("test rejection"))
            )
        end)
    end
    abc(nil):catch(function(____, reason)
        local ____temp_0 = #result + 1
        result[____temp_0] = reason
        return ____temp_0
    end)
    return result
end
return ____exports`, false, false},
		{"can await non-promise values", `async function foo() {
            return await "foo";
        }

        async function bar() {
            return await { foo: await foo(), bar: "bar" };
        }

        async function baz() {
            return (await bar()).foo + (await bar()).bar;
        }

        const { state, value } = baz() as any;
        return { state, value };`, `{state = 1, value = "foobar"}`, `local ____lualib = require("lualib_bundle")
local __TS__AsyncAwaiter = ____lualib.__TS__AsyncAwaiter
local __TS__Await = ____lualib.__TS__Await
local ____exports = {}
function ____exports.__main(self)
    local function foo(self)
        return __TS__AsyncAwaiter(function(____awaiter_resolve)
            return ____awaiter_resolve(
                nil,
                __TS__Await("foo")
            )
        end)
    end
    local function bar(self)
        return __TS__AsyncAwaiter(function(____awaiter_resolve)
            return ____awaiter_resolve(
                nil,
                __TS__Await({
                    foo = __TS__Await(foo(nil)),
                    bar = "bar"
                })
            )
        end)
    end
    local function baz(self)
        return __TS__AsyncAwaiter(function(____awaiter_resolve)
            return ____awaiter_resolve(
                nil,
                __TS__Await(bar(nil)).foo .. __TS__Await(bar(nil)).bar
            )
        end)
    end
    local ____baz_result_0 = baz(nil)
    local state = ____baz_result_0.state
    local value = ____baz_result_0.value
    return {state = state, value = value}
end
return ____exports`, false, false},
		{"can make inline async functions", `const foo = async function() { return "foo"; };
        const bar = async function() { return await foo(); };

        const { state, value } = bar() as any;
        return { state, value };`, `{state = 1, value = "foo"}`, `local ____lualib = require("lualib_bundle")
local __TS__AsyncAwaiter = ____lualib.__TS__AsyncAwaiter
local __TS__Await = ____lualib.__TS__Await
local ____exports = {}
function ____exports.__main(self)
    local function foo(self)
        return __TS__AsyncAwaiter(function(____awaiter_resolve)
            return ____awaiter_resolve(nil, "foo")
        end)
    end
    local function bar(self)
        return __TS__AsyncAwaiter(function(____awaiter_resolve)
            return ____awaiter_resolve(
                nil,
                __TS__Await(foo(nil))
            )
        end)
    end
    local ____bar_result_0 = bar(nil)
    local state = ____bar_result_0.state
    local value = ____bar_result_0.value
    return {state = state, value = value}
end
return ____exports`, false, false},
		{"can make async lambdas with expression body", `const foo = async () => "foo";
        const bar = async () => await foo();

        const { state, value } = bar() as any;
        return { state, value };`, `{state = 1, value = "foo"}`, `local ____lualib = require("lualib_bundle")
local __TS__AsyncAwaiter = ____lualib.__TS__AsyncAwaiter
local __TS__Await = ____lualib.__TS__Await
local ____exports = {}
function ____exports.__main(self)
    local function foo()
        return __TS__AsyncAwaiter(function(____awaiter_resolve)
            return ____awaiter_resolve(nil, "foo")
        end)
    end
    local function bar()
        return __TS__AsyncAwaiter(function(____awaiter_resolve)
            return ____awaiter_resolve(
                nil,
                __TS__Await(foo(nil))
            )
        end)
    end
    local ____bar_result_0 = bar(nil)
    local state = ____bar_result_0.state
    local value = ____bar_result_0.value
    return {state = state, value = value}
end
return ____exports`, false, false},
		{"async function returning value is same as non-async function returning promise", `function f(): Promise<number> {
            return Promise.resolve(42);
        }

        async function fAsync(): Promise<number> {
            return 42;
        }

        const { state: state1, value: value1 } = f() as any;
        const { state: state2, value: value2 } = fAsync() as any;

        return {
            state1, value1,
            state2, value2
        };`, `{state1 = 1, state2 = 1, value1 = 42, value2 = 42}`, `local ____lualib = require("lualib_bundle")
local __TS__Promise = ____lualib.__TS__Promise
local __TS__AsyncAwaiter = ____lualib.__TS__AsyncAwaiter
local __TS__Await = ____lualib.__TS__Await
local ____exports = {}
function ____exports.__main(self)
    local function f(self)
        return __TS__Promise.resolve(42)
    end
    local function fAsync(self)
        return __TS__AsyncAwaiter(function(____awaiter_resolve)
            return ____awaiter_resolve(nil, 42)
        end)
    end
    local ____f_result_0 = f(nil)
    local state1 = ____f_result_0.state
    local value1 = ____f_result_0.value
    local ____fAsync_result_1 = fAsync(nil)
    local state2 = ____fAsync_result_1.state
    local value2 = ____fAsync_result_1.value
    return {state1 = state1, value1 = value1, state2 = state2, value2 = value2}
end
return ____exports`, false, false},
		{"async function throws error", `async function a() {
            throw "test throw";
        }

        const { state, rejectionReason } = a() as any;
        return { state, rejectionReason };`, `{rejectionReason = "test throw", state = 2}`, `local ____lualib = require("lualib_bundle")
local __TS__AsyncAwaiter = ____lualib.__TS__AsyncAwaiter
local __TS__Await = ____lualib.__TS__Await
local ____exports = {}
function ____exports.__main(self)
    local function a(self)
        return __TS__AsyncAwaiter(function(____awaiter_resolve)
            error("test throw", 0)
        end)
    end
    local ____a_result_0 = a(nil)
    local state = ____a_result_0.state
    local rejectionReason = ____a_result_0.rejectionReason
    return {state = state, rejectionReason = rejectionReason}
end
return ____exports`, false, false},
		{"async lambda throws error", `const a = async () => {
            throw "test throw";
        }

        const { state, rejectionReason } = a() as any;
        return { state, rejectionReason };`, `{rejectionReason = "test throw", state = 2}`, `local ____lualib = require("lualib_bundle")
local __TS__AsyncAwaiter = ____lualib.__TS__AsyncAwaiter
local __TS__Await = ____lualib.__TS__Await
local ____exports = {}
function ____exports.__main(self)
    local function a()
        return __TS__AsyncAwaiter(function(____awaiter_resolve)
            error("test throw", 0)
        end)
    end
    local ____a_result_0 = a(nil)
    local state = ____a_result_0.state
    local rejectionReason = ____a_result_0.rejectionReason
    return {state = state, rejectionReason = rejectionReason}
end
return ____exports`, false, false},
		{"async function throws object", `async function a() {
            throw new Error("test throw");
        }

        const { state, rejectionReason } = a() as any;
        return { state, rejectionReason };`, `{rejectionReason = {message = "test throw", name = "Error", stack = ~contains:stack traceback}, state = 2}`, `local ____lualib = require("lualib_bundle")
local Error = ____lualib.Error
local RangeError = ____lualib.RangeError
local ReferenceError = ____lualib.ReferenceError
local SyntaxError = ____lualib.SyntaxError
local TypeError = ____lualib.TypeError
local URIError = ____lualib.URIError
local __TS__New = ____lualib.__TS__New
local __TS__AsyncAwaiter = ____lualib.__TS__AsyncAwaiter
local __TS__Await = ____lualib.__TS__Await
local ____exports = {}
function ____exports.__main(self)
    local function a(self)
        return __TS__AsyncAwaiter(function(____awaiter_resolve)
            error(
                __TS__New(Error, "test throw"),
                0
            )
        end)
    end
    local ____a_result_0 = a(nil)
    local state = ____a_result_0.state
    local rejectionReason = ____a_result_0.rejectionReason
    return {state = state, rejectionReason = rejectionReason}
end
return ____exports`, false, false},
	})

	batchExpectModules(t, []moduleTestCase{
		{"try/catch in async function try/finally in async function", `const foo = async () => {
                throw "foo error";
            };

            let finallyCalled = false;

            const run = async () => {
                try {
                    await foo();
                } finally {
                    finallyCalled = true;
                }
                return 10;
            };

            let succeeded: any = false;
            let rejected: any = false;

            run()
                .then(_ => { succeeded = true })
                .catch(e => { rejected = e });

            export const result = { finallyCalled, succeeded, rejected };`, `{result = {finallyCalled = true, rejected = "foo error", succeeded = false}}`, `local ____lualib = require("lualib_bundle")
local __TS__AsyncAwaiter = ____lualib.__TS__AsyncAwaiter
local __TS__Await = ____lualib.__TS__Await
local ____exports = {}
local function foo()
    return __TS__AsyncAwaiter(function(____awaiter_resolve)
        error("foo error", 0)
    end)
end
local finallyCalled = false
local function run()
    return __TS__AsyncAwaiter(function(____awaiter_resolve)
        local ____try = __TS__AsyncAwaiter(function()
            __TS__Await(foo(nil))
        end)
        ____try.finally(
            ____try,
            function()
                finallyCalled = true
            end
        )
        __TS__Await(____try)
        return ____awaiter_resolve(nil, 10)
    end)
end
local succeeded = false
local rejected = false
local ____self_0 = run(nil)
____self_0["then"](
    ____self_0,
    function(____, _)
        succeeded = true
    end
):catch(function(____, e)
    rejected = e
end)
____exports.result = {finallyCalled = finallyCalled, succeeded = succeeded, rejected = rejected}
return ____exports`, false, false},
		{"try/catch in async function Awaiting a rejected promise should halt function execution (#1272)", `const foo = async () => {
                throw new Error('foo error');
            };

            let halted = true;
            let caught = "";

            const run = async () => {
                try {
                    await foo();
                    halted = false;
                } catch (err) {
                    caught = 'catch err: ' + err;
                }
            };

            let succeeded: any = false;
            let rejected: any = false;

            run()
                .then(_ => { succeeded = true },
                      e => { rejected = e });

            export const result = { halted, caught, succeeded, rejected };`, `{result = {caught = "catch err: Error: foo error", halted = true, rejected = false, succeeded = true}}`, `local ____lualib = require("lualib_bundle")
local Error = ____lualib.Error
local RangeError = ____lualib.RangeError
local ReferenceError = ____lualib.ReferenceError
local SyntaxError = ____lualib.SyntaxError
local TypeError = ____lualib.TypeError
local URIError = ____lualib.URIError
local __TS__New = ____lualib.__TS__New
local __TS__AsyncAwaiter = ____lualib.__TS__AsyncAwaiter
local __TS__Await = ____lualib.__TS__Await
local ____exports = {}
local function foo()
    return __TS__AsyncAwaiter(function(____awaiter_resolve)
        error(
            __TS__New(Error, "foo error"),
            0
        )
    end)
end
local halted = true
local caught = ""
local function run()
    return __TS__AsyncAwaiter(function(____awaiter_resolve)
        local ____try = __TS__AsyncAwaiter(function()
            __TS__Await(foo(nil))
            halted = false
        end)
        __TS__Await(____try.catch(
            ____try,
            function(____, err)
                caught = "catch err: " .. tostring(err)
            end
        ))
    end)
end
local succeeded = false
local rejected = false
local ____self_0 = run(nil)
____self_0["then"](
    ____self_0,
    function(____, _)
        succeeded = true
    end,
    function(____, e)
        rejected = e
    end
)
____exports.result = {halted = halted, caught = caught, succeeded = succeeded, rejected = rejected}
return ____exports`, false, false},
		{"try/catch in async function Awaiting a rejecting promise should halt function execution (#1272)", `let rej: (error: any) => void = () => {};
            const foo = () => new Promise((_, reject) => {
                rej = reject;
            });

            let halted = true;
            let caught = "";

            const run = async () => {
                try {
                    await foo();
                    halted = false;
                } catch (err) {
                    caught = 'catch err: ' + err;
                }
            };

            let succeeded: any = false;
            let rejected: any = false;

            run()
                .then(_ => { succeeded = true },
                      e => { rejected = e });

            rej("rejection message");

            export const result = { halted, caught, succeeded, rejected };`, `{result = {caught = "catch err: rejection message", halted = true, rejected = false, succeeded = true}}`, `local ____lualib = require("lualib_bundle")
local __TS__Promise = ____lualib.__TS__Promise
local __TS__New = ____lualib.__TS__New
local __TS__AsyncAwaiter = ____lualib.__TS__AsyncAwaiter
local __TS__Await = ____lualib.__TS__Await
local ____exports = {}
local function rej()
end
local function foo()
    return __TS__New(
        __TS__Promise,
        function(____, _, reject)
            rej = reject
        end
    )
end
local halted = true
local caught = ""
local function run()
    return __TS__AsyncAwaiter(function(____awaiter_resolve)
        local ____try = __TS__AsyncAwaiter(function()
            __TS__Await(foo(nil))
            halted = false
        end)
        __TS__Await(____try.catch(
            ____try,
            function(____, err)
                caught = "catch err: " .. tostring(err)
            end
        ))
    end)
end
local succeeded = false
local rejected = false
local ____self_0 = run(nil)
____self_0["then"](
    ____self_0,
    function(____, _)
        succeeded = true
    end,
    function(____, e)
        rejected = e
    end
)
rej(nil, "rejection message")
____exports.result = {halted = halted, caught = caught, succeeded = succeeded, rejected = rejected}
return ____exports`, false, false},
		{"try/catch in async function Async try/catch complicated case (#1272)", "const foo = async () => {\n                throw new Error('foo error');\n            };\n\n            let halted = true;\n            let caught = \"\";\n\n            const run = async () => {\n                try {\n                    await foo(); // This throws\n                } catch (err) {\n                    caught = 'catch err: ' + err; // This catches the async thrown error, function continues\n                }\n                try {\n                    throw \"throw 2\"; // Another throw\n                } catch (err) {\n                    try {\n                        await foo();\n                    } catch (err2) {\n                        return `caught: ${err}, then: ${err2}`; // Async function should exit here\n                    }\n                }\n                halted = false; // This code should not be called\n                return 10;\n            };\n\n            let succeeded: any = false;\n            let rejected: any = false;\n            let value: any = undefined;\n\n            run()\n                .then(v => { succeeded = true; value = v },\n                      e => { rejected = e });\n\n            export const result = { halted, caught, succeeded, rejected, value };", `{result = {caught = "catch err: Error: foo error", halted = true, rejected = false, succeeded = true, value = "caught: throw 2, then: Error: foo error"}}`, `local ____lualib = require("lualib_bundle")
local Error = ____lualib.Error
local RangeError = ____lualib.RangeError
local ReferenceError = ____lualib.ReferenceError
local SyntaxError = ____lualib.SyntaxError
local TypeError = ____lualib.TypeError
local URIError = ____lualib.URIError
local __TS__New = ____lualib.__TS__New
local __TS__AsyncAwaiter = ____lualib.__TS__AsyncAwaiter
local __TS__Await = ____lualib.__TS__Await
local ____exports = {}
local function foo()
    return __TS__AsyncAwaiter(function(____awaiter_resolve)
        error(
            __TS__New(Error, "foo error"),
            0
        )
    end)
end
local halted = true
local caught = ""
local function run()
    return __TS__AsyncAwaiter(function(____awaiter_resolve)
        local ____try = __TS__AsyncAwaiter(function()
            __TS__Await(foo(nil))
        end)
        __TS__Await(____try.catch(
            ____try,
            function(____, err)
                caught = "catch err: " .. tostring(err)
            end
        ))
        local ____try = __TS__AsyncAwaiter(function()
            error("throw 2", 0)
        end)
        __TS__Await(____try.catch(
            ____try,
            function(____, err)
                local ____try = __TS__AsyncAwaiter(function()
                    __TS__Await(foo(nil))
                end)
                __TS__Await(____try.catch(
                    ____try,
                    function(____, err2)
                        return ____awaiter_resolve(
                            nil,
                            (("caught: " .. tostring(err)) .. ", then: ") .. tostring(err2)
                        )
                    end
                ))
            end
        ))
        halted = false
        return ____awaiter_resolve(nil, 10)
    end)
end
local succeeded = false
local rejected = false
local value = nil
local ____self_0 = run(nil)
____self_0["then"](
    ____self_0,
    function(____, v)
        succeeded = true
        value = v
    end,
    function(____, e)
        rejected = e
    end
)
____exports.result = {
    halted = halted,
    caught = caught,
    succeeded = succeeded,
    rejected = rejected,
    value = value
}
return ____exports`, false, false},
	})

	batchRunTests(t, []batchTestCase{
		{name: "can await pending promise", tsCode: `
// Some logging utility, useful for asserting orders of operations

const allLogs: any[] = [];
function log(...values: any[]) {
    allLogs.push(...values);
}

// Create a promise and store its resolve and reject functions, useful for creating pending promises

function defer<T>() {
    let resolve: (data: any) => void = () => {};
    let reject: (reason: string) => void = () => {};
    const promise = new Promise<T>((res, rej) => {
        resolve = res;
        reject = rej;
    });
    return { promise, resolve, reject };
}
export function __main() {const { promise, resolve } = defer<string>();
        promise.then(data => log("resolving original promise", data));

        async function abc() {
            return await promise;
        }

        const awaitingPromise = abc();
        awaitingPromise.then(data => log("resolving awaiting promise", data));

        resolve("resolved data");

        return allLogs;}`, accessor: `mod.__main()`, want: `{"resolving original promise", "resolved data", "resolving awaiting promise", "resolved data"}`, refLua: `local ____lualib = require("lualib_bundle")
local __TS__ArrayPush = ____lualib.__TS__ArrayPush
local __TS__Promise = ____lualib.__TS__Promise
local __TS__New = ____lualib.__TS__New
local __TS__AsyncAwaiter = ____lualib.__TS__AsyncAwaiter
local __TS__Await = ____lualib.__TS__Await
local ____exports = {}
local allLogs = {}
local function log(self, ...)
    __TS__ArrayPush(allLogs, ...)
end
local function defer(self)
    local function resolve()
    end
    local function reject()
    end
    local promise = __TS__New(
        __TS__Promise,
        function(____, res, rej)
            resolve = res
            reject = rej
        end
    )
    return {promise = promise, resolve = resolve, reject = reject}
end
function ____exports.__main(self)
    local ____defer_result_0 = defer(nil)
    local promise = ____defer_result_0.promise
    local resolve = ____defer_result_0.resolve
    promise["then"](
        promise,
        function(____, data) return log(nil, "resolving original promise", data) end
    )
    local function abc(self)
        return __TS__AsyncAwaiter(function(____awaiter_resolve)
            return ____awaiter_resolve(
                nil,
                __TS__Await(promise)
            )
        end)
    end
    local awaitingPromise = abc(nil)
    awaitingPromise["then"](
        awaitingPromise,
        function(____, data) return log(nil, "resolving awaiting promise", data) end
    )
    resolve(nil, "resolved data")
    return allLogs
end
return ____exports`},
		{name: "can return non-promise from async function (\"async function abc() {\")", tsCode: `
// Some logging utility, useful for asserting orders of operations

const allLogs: any[] = [];
function log(...values: any[]) {
    allLogs.push(...values);
}

// Create a promise and store its resolve and reject functions, useful for creating pending promises

function defer<T>() {
    let resolve: (data: any) => void = () => {};
    let reject: (reason: string) => void = () => {};
    const promise = new Promise<T>((res, rej) => {
        resolve = res;
        reject = rej;
    });
    return { promise, resolve, reject };
}
export function __main() {const { promise, resolve } = defer<string>();
        promise.then(data => log("resolving original promise", data));

        async function abc() {
            await promise;
            return "abc return data"
        }

        const awaitingPromise = abc();
        awaitingPromise.then(data => log("resolving awaiting promise", data));

        resolve("resolved data");

        return allLogs;}`, accessor: `mod.__main()`, want: `{"resolving original promise", "resolved data", "resolving awaiting promise", "abc return data"}`, refLua: `local ____lualib = require("lualib_bundle")
local __TS__ArrayPush = ____lualib.__TS__ArrayPush
local __TS__Promise = ____lualib.__TS__Promise
local __TS__New = ____lualib.__TS__New
local __TS__AsyncAwaiter = ____lualib.__TS__AsyncAwaiter
local __TS__Await = ____lualib.__TS__Await
local ____exports = {}
local allLogs = {}
local function log(self, ...)
    __TS__ArrayPush(allLogs, ...)
end
local function defer(self)
    local function resolve()
    end
    local function reject()
    end
    local promise = __TS__New(
        __TS__Promise,
        function(____, res, rej)
            resolve = res
            reject = rej
        end
    )
    return {promise = promise, resolve = resolve, reject = reject}
end
function ____exports.__main(self)
    local ____defer_result_0 = defer(nil)
    local promise = ____defer_result_0.promise
    local resolve = ____defer_result_0.resolve
    promise["then"](
        promise,
        function(____, data) return log(nil, "resolving original promise", data) end
    )
    local function abc(self)
        return __TS__AsyncAwaiter(function(____awaiter_resolve)
            __TS__Await(promise)
            return ____awaiter_resolve(nil, "abc return data")
        end)
    end
    local awaitingPromise = abc(nil)
    awaitingPromise["then"](
        awaitingPromise,
        function(____, data) return log(nil, "resolving awaiting promise", data) end
    )
    resolve(nil, "resolved data")
    return allLogs
end
return ____exports`},
		{name: "can return non-promise from async function (\"const abc = async () => {\")", tsCode: `
// Some logging utility, useful for asserting orders of operations

const allLogs: any[] = [];
function log(...values: any[]) {
    allLogs.push(...values);
}

// Create a promise and store its resolve and reject functions, useful for creating pending promises

function defer<T>() {
    let resolve: (data: any) => void = () => {};
    let reject: (reason: string) => void = () => {};
    const promise = new Promise<T>((res, rej) => {
        resolve = res;
        reject = rej;
    });
    return { promise, resolve, reject };
}
export function __main() {const { promise, resolve } = defer<string>();
        promise.then(data => log("resolving original promise", data));

        const abc = async () => {
            await promise;
            return "abc return data"
        }

        const awaitingPromise = abc();
        awaitingPromise.then(data => log("resolving awaiting promise", data));

        resolve("resolved data");

        return allLogs;}`, accessor: `mod.__main()`, want: `{"resolving original promise", "resolved data", "resolving awaiting promise", "abc return data"}`, refLua: `local ____lualib = require("lualib_bundle")
local __TS__ArrayPush = ____lualib.__TS__ArrayPush
local __TS__Promise = ____lualib.__TS__Promise
local __TS__New = ____lualib.__TS__New
local __TS__AsyncAwaiter = ____lualib.__TS__AsyncAwaiter
local __TS__Await = ____lualib.__TS__Await
local ____exports = {}
local allLogs = {}
local function log(self, ...)
    __TS__ArrayPush(allLogs, ...)
end
local function defer(self)
    local function resolve()
    end
    local function reject()
    end
    local promise = __TS__New(
        __TS__Promise,
        function(____, res, rej)
            resolve = res
            reject = rej
        end
    )
    return {promise = promise, resolve = resolve, reject = reject}
end
function ____exports.__main(self)
    local ____defer_result_0 = defer(nil)
    local promise = ____defer_result_0.promise
    local resolve = ____defer_result_0.resolve
    promise["then"](
        promise,
        function(____, data) return log(nil, "resolving original promise", data) end
    )
    local function abc()
        return __TS__AsyncAwaiter(function(____awaiter_resolve)
            __TS__Await(promise)
            return ____awaiter_resolve(nil, "abc return data")
        end)
    end
    local awaitingPromise = abc(nil)
    awaitingPromise["then"](
        awaitingPromise,
        function(____, data) return log(nil, "resolving awaiting promise", data) end
    )
    resolve(nil, "resolved data")
    return allLogs
end
return ____exports`},
		{name: "can have multiple awaits in async function (\"async function abc() {\")", tsCode: `
// Some logging utility, useful for asserting orders of operations

const allLogs: any[] = [];
function log(...values: any[]) {
    allLogs.push(...values);
}

// Create a promise and store its resolve and reject functions, useful for creating pending promises

function defer<T>() {
    let resolve: (data: any) => void = () => {};
    let reject: (reason: string) => void = () => {};
    const promise = new Promise<T>((res, rej) => {
        resolve = res;
        reject = rej;
    });
    return { promise, resolve, reject };
}
export function __main() {const { promise: promise1, resolve: resolve1 } = defer<string>();
        const { promise: promise2, resolve: resolve2 } = defer<string>();
        const { promise: promise3, resolve: resolve3 } = defer<string>();
        promise1.then(data => log("resolving promise1", data));
        promise2.then(data => log("resolving promise2", data));
        promise3.then(data => log("resolving promise3", data));

        async function abc() {
            const result1 = await promise1;
            const result2 = await promise2;
            const result3 = await promise3;
            return [result1, result2, result3];
        }

        const awaitingPromise = abc();
        awaitingPromise.then(data => log("resolving awaiting promise", data));

        resolve1("data1");
        resolve2("data2");
        resolve3("data3");

        return allLogs;}`, accessor: `mod.__main()`, want: `{"resolving promise1", "data1", "resolving promise2", "data2", "resolving promise3", "data3", "resolving awaiting promise", {"data1", "data2", "data3"}}`, refLua: `local ____lualib = require("lualib_bundle")
local __TS__ArrayPush = ____lualib.__TS__ArrayPush
local __TS__Promise = ____lualib.__TS__Promise
local __TS__New = ____lualib.__TS__New
local __TS__AsyncAwaiter = ____lualib.__TS__AsyncAwaiter
local __TS__Await = ____lualib.__TS__Await
local ____exports = {}
local allLogs = {}
local function log(self, ...)
    __TS__ArrayPush(allLogs, ...)
end
local function defer(self)
    local function resolve()
    end
    local function reject()
    end
    local promise = __TS__New(
        __TS__Promise,
        function(____, res, rej)
            resolve = res
            reject = rej
        end
    )
    return {promise = promise, resolve = resolve, reject = reject}
end
function ____exports.__main(self)
    local ____defer_result_0 = defer(nil)
    local promise1 = ____defer_result_0.promise
    local resolve1 = ____defer_result_0.resolve
    local ____defer_result_1 = defer(nil)
    local promise2 = ____defer_result_1.promise
    local resolve2 = ____defer_result_1.resolve
    local ____defer_result_2 = defer(nil)
    local promise3 = ____defer_result_2.promise
    local resolve3 = ____defer_result_2.resolve
    promise1["then"](
        promise1,
        function(____, data) return log(nil, "resolving promise1", data) end
    )
    promise2["then"](
        promise2,
        function(____, data) return log(nil, "resolving promise2", data) end
    )
    promise3["then"](
        promise3,
        function(____, data) return log(nil, "resolving promise3", data) end
    )
    local function abc(self)
        return __TS__AsyncAwaiter(function(____awaiter_resolve)
            local result1 = __TS__Await(promise1)
            local result2 = __TS__Await(promise2)
            local result3 = __TS__Await(promise3)
            return ____awaiter_resolve(nil, {result1, result2, result3})
        end)
    end
    local awaitingPromise = abc(nil)
    awaitingPromise["then"](
        awaitingPromise,
        function(____, data) return log(nil, "resolving awaiting promise", data) end
    )
    resolve1(nil, "data1")
    resolve2(nil, "data2")
    resolve3(nil, "data3")
    return allLogs
end
return ____exports`},
		{name: "can have multiple awaits in async function (\"const abc = async () => {\")", tsCode: `
// Some logging utility, useful for asserting orders of operations

const allLogs: any[] = [];
function log(...values: any[]) {
    allLogs.push(...values);
}

// Create a promise and store its resolve and reject functions, useful for creating pending promises

function defer<T>() {
    let resolve: (data: any) => void = () => {};
    let reject: (reason: string) => void = () => {};
    const promise = new Promise<T>((res, rej) => {
        resolve = res;
        reject = rej;
    });
    return { promise, resolve, reject };
}
export function __main() {const { promise: promise1, resolve: resolve1 } = defer<string>();
        const { promise: promise2, resolve: resolve2 } = defer<string>();
        const { promise: promise3, resolve: resolve3 } = defer<string>();
        promise1.then(data => log("resolving promise1", data));
        promise2.then(data => log("resolving promise2", data));
        promise3.then(data => log("resolving promise3", data));

        const abc = async () => {
            const result1 = await promise1;
            const result2 = await promise2;
            const result3 = await promise3;
            return [result1, result2, result3];
        }

        const awaitingPromise = abc();
        awaitingPromise.then(data => log("resolving awaiting promise", data));

        resolve1("data1");
        resolve2("data2");
        resolve3("data3");

        return allLogs;}`, accessor: `mod.__main()`, want: `{"resolving promise1", "data1", "resolving promise2", "data2", "resolving promise3", "data3", "resolving awaiting promise", {"data1", "data2", "data3"}}`, refLua: `local ____lualib = require("lualib_bundle")
local __TS__ArrayPush = ____lualib.__TS__ArrayPush
local __TS__Promise = ____lualib.__TS__Promise
local __TS__New = ____lualib.__TS__New
local __TS__AsyncAwaiter = ____lualib.__TS__AsyncAwaiter
local __TS__Await = ____lualib.__TS__Await
local ____exports = {}
local allLogs = {}
local function log(self, ...)
    __TS__ArrayPush(allLogs, ...)
end
local function defer(self)
    local function resolve()
    end
    local function reject()
    end
    local promise = __TS__New(
        __TS__Promise,
        function(____, res, rej)
            resolve = res
            reject = rej
        end
    )
    return {promise = promise, resolve = resolve, reject = reject}
end
function ____exports.__main(self)
    local ____defer_result_0 = defer(nil)
    local promise1 = ____defer_result_0.promise
    local resolve1 = ____defer_result_0.resolve
    local ____defer_result_1 = defer(nil)
    local promise2 = ____defer_result_1.promise
    local resolve2 = ____defer_result_1.resolve
    local ____defer_result_2 = defer(nil)
    local promise3 = ____defer_result_2.promise
    local resolve3 = ____defer_result_2.resolve
    promise1["then"](
        promise1,
        function(____, data) return log(nil, "resolving promise1", data) end
    )
    promise2["then"](
        promise2,
        function(____, data) return log(nil, "resolving promise2", data) end
    )
    promise3["then"](
        promise3,
        function(____, data) return log(nil, "resolving promise3", data) end
    )
    local function abc()
        return __TS__AsyncAwaiter(function(____awaiter_resolve)
            local result1 = __TS__Await(promise1)
            local result2 = __TS__Await(promise2)
            local result3 = __TS__Await(promise3)
            return ____awaiter_resolve(nil, {result1, result2, result3})
        end)
    end
    local awaitingPromise = abc(nil)
    awaitingPromise["then"](
        awaitingPromise,
        function(____, data) return log(nil, "resolving awaiting promise", data) end
    )
    resolve1(nil, "data1")
    resolve2(nil, "data2")
    resolve3(nil, "data3")
    return allLogs
end
return ____exports`},
		{name: "can await async function from async function", tsCode: `
// Some logging utility, useful for asserting orders of operations

const allLogs: any[] = [];
function log(...values: any[]) {
    allLogs.push(...values);
}

// Create a promise and store its resolve and reject functions, useful for creating pending promises

function defer<T>() {
    let resolve: (data: any) => void = () => {};
    let reject: (reason: string) => void = () => {};
    const promise = new Promise<T>((res, rej) => {
        resolve = res;
        reject = rej;
    });
    return { promise, resolve, reject };
}
export function __main() {const { promise, resolve } = defer<string>();
        promise.then(data => log("resolving original promise", data));

        async function abc() {
            return await promise;
        }

        async function def() {
            return await abc();
        }

        const awaitingPromise = def();
        awaitingPromise.then(data => log("resolving awaiting promise", data));

        resolve("resolved data");

        return allLogs;}`, accessor: `mod.__main()`, want: `{"resolving original promise", "resolved data", "resolving awaiting promise", "resolved data"}`, refLua: `local ____lualib = require("lualib_bundle")
local __TS__ArrayPush = ____lualib.__TS__ArrayPush
local __TS__Promise = ____lualib.__TS__Promise
local __TS__New = ____lualib.__TS__New
local __TS__AsyncAwaiter = ____lualib.__TS__AsyncAwaiter
local __TS__Await = ____lualib.__TS__Await
local ____exports = {}
local allLogs = {}
local function log(self, ...)
    __TS__ArrayPush(allLogs, ...)
end
local function defer(self)
    local function resolve()
    end
    local function reject()
    end
    local promise = __TS__New(
        __TS__Promise,
        function(____, res, rej)
            resolve = res
            reject = rej
        end
    )
    return {promise = promise, resolve = resolve, reject = reject}
end
function ____exports.__main(self)
    local ____defer_result_0 = defer(nil)
    local promise = ____defer_result_0.promise
    local resolve = ____defer_result_0.resolve
    promise["then"](
        promise,
        function(____, data) return log(nil, "resolving original promise", data) end
    )
    local function abc(self)
        return __TS__AsyncAwaiter(function(____awaiter_resolve)
            return ____awaiter_resolve(
                nil,
                __TS__Await(promise)
            )
        end)
    end
    local function def(self)
        return __TS__AsyncAwaiter(function(____awaiter_resolve)
            return ____awaiter_resolve(
                nil,
                __TS__Await(abc(nil))
            )
        end)
    end
    local awaitingPromise = def(nil)
    awaitingPromise["then"](
        awaitingPromise,
        function(____, data) return log(nil, "resolving awaiting promise", data) end
    )
    resolve(nil, "resolved data")
    return allLogs
end
return ____exports`},
		{name: "correctly handles awaited functions rejecting", tsCode: `
// Some logging utility, useful for asserting orders of operations

const allLogs: any[] = [];
function log(...values: any[]) {
    allLogs.push(...values);
}

// Create a promise and store its resolve and reject functions, useful for creating pending promises

function defer<T>() {
    let resolve: (data: any) => void = () => {};
    let reject: (reason: string) => void = () => {};
    const promise = new Promise<T>((res, rej) => {
        resolve = res;
        reject = rej;
    });
    return { promise, resolve, reject };
}
export function __main() {const { promise: promise1, reject } = defer<string>();
        const { promise: promise2 } = defer<string>();

        promise1.then(data => log("resolving promise1", data), reason => log("rejecting promise1", reason));
        promise2.then(data => log("resolving promise2", data));

        async function abc() {
            const result1 = await promise1;
            const result2 = await promise2;
            return [result1, result2];
        }

        const awaitingPromise = abc();
        awaitingPromise.catch(reason => log("awaiting promise was rejected because:", reason));

        reject("test reject");

        return allLogs;}`, accessor: `mod.__main()`, want: `{"rejecting promise1", "test reject", "awaiting promise was rejected because:", "test reject"}`, refLua: `local ____lualib = require("lualib_bundle")
local __TS__ArrayPush = ____lualib.__TS__ArrayPush
local __TS__Promise = ____lualib.__TS__Promise
local __TS__New = ____lualib.__TS__New
local __TS__AsyncAwaiter = ____lualib.__TS__AsyncAwaiter
local __TS__Await = ____lualib.__TS__Await
local ____exports = {}
local allLogs = {}
local function log(self, ...)
    __TS__ArrayPush(allLogs, ...)
end
local function defer(self)
    local function resolve()
    end
    local function reject()
    end
    local promise = __TS__New(
        __TS__Promise,
        function(____, res, rej)
            resolve = res
            reject = rej
        end
    )
    return {promise = promise, resolve = resolve, reject = reject}
end
function ____exports.__main(self)
    local ____defer_result_0 = defer(nil)
    local promise1 = ____defer_result_0.promise
    local reject = ____defer_result_0.reject
    local ____defer_result_1 = defer(nil)
    local promise2 = ____defer_result_1.promise
    promise1["then"](
        promise1,
        function(____, data) return log(nil, "resolving promise1", data) end,
        function(____, reason) return log(nil, "rejecting promise1", reason) end
    )
    promise2["then"](
        promise2,
        function(____, data) return log(nil, "resolving promise2", data) end
    )
    local function abc(self)
        return __TS__AsyncAwaiter(function(____awaiter_resolve)
            local result1 = __TS__Await(promise1)
            local result2 = __TS__Await(promise2)
            return ____awaiter_resolve(nil, {result1, result2})
        end)
    end
    local awaitingPromise = abc(nil)
    awaitingPromise:catch(function(____, reason) return log(nil, "awaiting promise was rejected because:", reason) end)
    reject(nil, "test reject")
    return allLogs
end
return ____exports`},
		{name: "async function can access varargs", tsCode: `
// Some logging utility, useful for asserting orders of operations

const allLogs: any[] = [];
function log(...values: any[]) {
    allLogs.push(...values);
}

// Create a promise and store its resolve and reject functions, useful for creating pending promises

function defer<T>() {
    let resolve: (data: any) => void = () => {};
    let reject: (reason: string) => void = () => {};
    const promise = new Promise<T>((res, rej) => {
        resolve = res;
        reject = rej;
    });
    return { promise, resolve, reject };
}
export function __main() {const { promise, resolve } = defer<string>();

        async function a(...args: string[]) {
            log(await promise);
            log(args[1]);
        }

        const awaitingPromise = a("A", "B", "C");
        resolve("resolved");

        return allLogs;}`, accessor: `mod.__main()`, want: `{"resolved", "B"}`, refLua: `local ____lualib = require("lualib_bundle")
local __TS__ArrayPush = ____lualib.__TS__ArrayPush
local __TS__Promise = ____lualib.__TS__Promise
local __TS__New = ____lualib.__TS__New
local __TS__AsyncAwaiter = ____lualib.__TS__AsyncAwaiter
local __TS__Await = ____lualib.__TS__Await
local ____exports = {}
local allLogs = {}
local function log(self, ...)
    __TS__ArrayPush(allLogs, ...)
end
local function defer(self)
    local function resolve()
    end
    local function reject()
    end
    local promise = __TS__New(
        __TS__Promise,
        function(____, res, rej)
            resolve = res
            reject = rej
        end
    )
    return {promise = promise, resolve = resolve, reject = reject}
end
function ____exports.__main(self)
    local ____defer_result_0 = defer(nil)
    local promise = ____defer_result_0.promise
    local resolve = ____defer_result_0.resolve
    local function a(self, ...)
        local args = {...}
        return __TS__AsyncAwaiter(function(____awaiter_resolve)
            log(
                nil,
                __TS__Await(promise)
            )
            log(nil, args[2])
        end)
    end
    local awaitingPromise = a(nil, "A", "B", "C")
    resolve(nil, "resolved")
    return allLogs
end
return ____exports`},
		{name: "async function can forward varargs", tsCode: `
// Some logging utility, useful for asserting orders of operations

const allLogs: any[] = [];
function log(...values: any[]) {
    allLogs.push(...values);
}

// Create a promise and store its resolve and reject functions, useful for creating pending promises

function defer<T>() {
    let resolve: (data: any) => void = () => {};
    let reject: (reason: string) => void = () => {};
    const promise = new Promise<T>((res, rej) => {
        resolve = res;
        reject = rej;
    });
    return { promise, resolve, reject };
}
export function __main() {const { promise, resolve } = defer<string>();

        async function a(...args: string[]) {
            log(await promise);
            log(...args);
        }

        const awaitingPromise = a("A", "B", "C");
        resolve("resolved");

        return allLogs;}`, accessor: `mod.__main()`, want: `{"resolved", "A", "B", "C"}`, refLua: `local ____lualib = require("lualib_bundle")
local __TS__ArrayPush = ____lualib.__TS__ArrayPush
local __TS__Promise = ____lualib.__TS__Promise
local __TS__New = ____lualib.__TS__New
local __TS__AsyncAwaiter = ____lualib.__TS__AsyncAwaiter
local __TS__Await = ____lualib.__TS__Await
local ____exports = {}
local allLogs = {}
local function log(self, ...)
    __TS__ArrayPush(allLogs, ...)
end
local function defer(self)
    local function resolve()
    end
    local function reject()
    end
    local promise = __TS__New(
        __TS__Promise,
        function(____, res, rej)
            resolve = res
            reject = rej
        end
    )
    return {promise = promise, resolve = resolve, reject = reject}
end
function ____exports.__main(self)
    local ____defer_result_0 = defer(nil)
    local promise = ____defer_result_0.promise
    local resolve = ____defer_result_0.resolve
    local function a(self, ...)
        local args = {...}
        return __TS__AsyncAwaiter(function(____awaiter_resolve)
            log(
                nil,
                __TS__Await(promise)
            )
            log(
                nil,
                table.unpack(args)
            )
        end)
    end
    local awaitingPromise = a(nil, "A", "B", "C")
    resolve(nil, "resolved")
    return allLogs
end
return ____exports`},
		{name: "async function adopts pending promise", tsCode: `
// Some logging utility, useful for asserting orders of operations

const allLogs: any[] = [];
function log(...values: any[]) {
    allLogs.push(...values);
}

// Create a promise and store its resolve and reject functions, useful for creating pending promises

function defer<T>() {
    let resolve: (data: any) => void = () => {};
    let reject: (reason: string) => void = () => {};
    const promise = new Promise<T>((res, rej) => {
        resolve = res;
        reject = rej;
    });
    return { promise, resolve, reject };
}
export function __main() {let resolve: (v: string) => void = () => {};
        async function receive(): Promise<string> {
            return new Promise(res => {
                resolve = res;
            });
        }

        receive().then(v => {
            log(v);
        });

        resolve("delayed resolve");

        return allLogs;}`, accessor: `mod.__main()`, want: `{"delayed resolve"}`, refLua: `local ____lualib = require("lualib_bundle")
local __TS__ArrayPush = ____lualib.__TS__ArrayPush
local __TS__Promise = ____lualib.__TS__Promise
local __TS__New = ____lualib.__TS__New
local __TS__AsyncAwaiter = ____lualib.__TS__AsyncAwaiter
local __TS__Await = ____lualib.__TS__Await
local ____exports = {}
local allLogs = {}
local function log(self, ...)
    __TS__ArrayPush(allLogs, ...)
end
local function defer(self)
    local function resolve()
    end
    local function reject()
    end
    local promise = __TS__New(
        __TS__Promise,
        function(____, res, rej)
            resolve = res
            reject = rej
        end
    )
    return {promise = promise, resolve = resolve, reject = reject}
end
function ____exports.__main(self)
    local function resolve()
    end
    local function receive(self)
        return __TS__AsyncAwaiter(function(____awaiter_resolve)
            return ____awaiter_resolve(
                nil,
                __TS__New(
                    __TS__Promise,
                    function(____, res)
                        resolve = res
                    end
                )
            )
        end)
    end
    local ____self_0 = receive(nil)
    ____self_0["then"](
        ____self_0,
        function(____, v)
            log(nil, v)
        end
    )
    resolve(nil, "delayed resolve")
    return allLogs
end
return ____exports`},
		{name: "async function adopts resolved promise", tsCode: `
// Some logging utility, useful for asserting orders of operations

const allLogs: any[] = [];
function log(...values: any[]) {
    allLogs.push(...values);
}

// Create a promise and store its resolve and reject functions, useful for creating pending promises

function defer<T>() {
    let resolve: (data: any) => void = () => {};
    let reject: (reason: string) => void = () => {};
    const promise = new Promise<T>((res, rej) => {
        resolve = res;
        reject = rej;
    });
    return { promise, resolve, reject };
}
export function __main() {async function receive(): Promise<string> {
            return new Promise(resolve => {
                resolve("resolved!");
            });
        }

        receive().then(v => {
            log(v);
        });

        return allLogs;}`, accessor: `mod.__main()`, want: `{"resolved!"}`, refLua: `local ____lualib = require("lualib_bundle")
local __TS__ArrayPush = ____lualib.__TS__ArrayPush
local __TS__Promise = ____lualib.__TS__Promise
local __TS__New = ____lualib.__TS__New
local __TS__AsyncAwaiter = ____lualib.__TS__AsyncAwaiter
local __TS__Await = ____lualib.__TS__Await
local ____exports = {}
local allLogs = {}
local function log(self, ...)
    __TS__ArrayPush(allLogs, ...)
end
local function defer(self)
    local function resolve()
    end
    local function reject()
    end
    local promise = __TS__New(
        __TS__Promise,
        function(____, res, rej)
            resolve = res
            reject = rej
        end
    )
    return {promise = promise, resolve = resolve, reject = reject}
end
function ____exports.__main(self)
    local function receive(self)
        return __TS__AsyncAwaiter(function(____awaiter_resolve)
            return ____awaiter_resolve(
                nil,
                __TS__New(
                    __TS__Promise,
                    function(____, resolve)
                        resolve(nil, "resolved!")
                    end
                )
            )
        end)
    end
    local ____self_0 = receive(nil)
    ____self_0["then"](
        ____self_0,
        function(____, v)
            log(nil, v)
        end
    )
    return allLogs
end
return ____exports`},
		{name: "async function adopts rejected promise", tsCode: `
// Some logging utility, useful for asserting orders of operations

const allLogs: any[] = [];
function log(...values: any[]) {
    allLogs.push(...values);
}

// Create a promise and store its resolve and reject functions, useful for creating pending promises

function defer<T>() {
    let resolve: (data: any) => void = () => {};
    let reject: (reason: string) => void = () => {};
    const promise = new Promise<T>((res, rej) => {
        resolve = res;
        reject = rej;
    });
    return { promise, resolve, reject };
}
export function __main() {async function receive(): Promise<string> {
            return new Promise((_, reject) => {
                reject("rejected");
            });
        }

        receive().catch(err => {
            log(err);
        });

        return allLogs;}`, accessor: `mod.__main()`, want: `{"rejected"}`, refLua: `local ____lualib = require("lualib_bundle")
local __TS__ArrayPush = ____lualib.__TS__ArrayPush
local __TS__Promise = ____lualib.__TS__Promise
local __TS__New = ____lualib.__TS__New
local __TS__AsyncAwaiter = ____lualib.__TS__AsyncAwaiter
local __TS__Await = ____lualib.__TS__Await
local ____exports = {}
local allLogs = {}
local function log(self, ...)
    __TS__ArrayPush(allLogs, ...)
end
local function defer(self)
    local function resolve()
    end
    local function reject()
    end
    local promise = __TS__New(
        __TS__Promise,
        function(____, res, rej)
            resolve = res
            reject = rej
        end
    )
    return {promise = promise, resolve = resolve, reject = reject}
end
function ____exports.__main(self)
    local function receive(self)
        return __TS__AsyncAwaiter(function(____awaiter_resolve)
            return ____awaiter_resolve(
                nil,
                __TS__New(
                    __TS__Promise,
                    function(____, _, reject)
                        reject(nil, "rejected")
                    end
                )
            )
        end)
    end
    receive(nil):catch(function(____, err)
        log(nil, err)
    end)
    return allLogs
end
return ____exports`},
		{name: "return in catch aborts async method", tsCode: `
// Some logging utility, useful for asserting orders of operations

const allLogs: any[] = [];
function log(...values: any[]) {
    allLogs.push(...values);
}

// Create a promise and store its resolve and reject functions, useful for creating pending promises

function defer<T>() {
    let resolve: (data: any) => void = () => {};
    let reject: (reason: string) => void = () => {};
    const promise = new Promise<T>((res, rej) => {
        resolve = res;
        reject = rej;
    });
    return { promise, resolve, reject };
}
export function __main() {async function asyncFunc() {
            try {
                await Promise.reject("rejection");
                log("Should not be seen");
            } catch {
                log("C");
                return "result";
            }
            log("Should also not be seen");
        }

        asyncFunc().then(v => log("resolved", v));

        return allLogs;}`, accessor: `mod.__main()`, want: `{"C", "resolved", "result"}`, refLua: `local ____lualib = require("lualib_bundle")
local __TS__ArrayPush = ____lualib.__TS__ArrayPush
local __TS__Promise = ____lualib.__TS__Promise
local __TS__New = ____lualib.__TS__New
local __TS__AsyncAwaiter = ____lualib.__TS__AsyncAwaiter
local __TS__Await = ____lualib.__TS__Await
local ____exports = {}
local allLogs = {}
local function log(self, ...)
    __TS__ArrayPush(allLogs, ...)
end
local function defer(self)
    local function resolve()
    end
    local function reject()
    end
    local promise = __TS__New(
        __TS__Promise,
        function(____, res, rej)
            resolve = res
            reject = rej
        end
    )
    return {promise = promise, resolve = resolve, reject = reject}
end
function ____exports.__main(self)
    local function asyncFunc(self)
        return __TS__AsyncAwaiter(function(____awaiter_resolve)
            local ____try = __TS__AsyncAwaiter(function()
                __TS__Await(__TS__Promise.reject("rejection"))
                log(nil, "Should not be seen")
            end)
            __TS__Await(____try.catch(
                ____try,
                function(____)
                    log(nil, "C")
                    return ____awaiter_resolve(nil, "result")
                end
            ))
            log(nil, "Should also not be seen")
        end)
    end
    local ____self_0 = asyncFunc(nil)
    ____self_0["then"](
        ____self_0,
        function(____, v) return log(nil, "resolved", v) end
    )
    return allLogs
end
return ____exports`},
		{name: "can throw error after await in async function (\"async function abc() {\")", tsCode: `
// Some logging utility, useful for asserting orders of operations

const allLogs: any[] = [];
function log(...values: any[]) {
    allLogs.push(...values);
}

// Create a promise and store its resolve and reject functions, useful for creating pending promises

function defer<T>() {
    let resolve: (data: any) => void = () => {};
    let reject: (reason: string) => void = () => {};
    const promise = new Promise<T>((res, rej) => {
        resolve = res;
        reject = rej;
    });
    return { promise, resolve, reject };
}
export function __main() {const { promise, resolve } = defer<string>();
        promise.then(data => log("resolving first promise", data));

        async function abc() {
            await promise;
            log("run abc");
            throw "test throw";
        }

        const awaitingPromise = abc();
        awaitingPromise.catch(error => log("caught error", error));

        resolve("resolved data");
        return allLogs;}`, accessor: `mod.__main()`, want: `{"resolving first promise", "resolved data", "run abc", "caught error", "test throw"}`, refLua: `local ____lualib = require("lualib_bundle")
local __TS__ArrayPush = ____lualib.__TS__ArrayPush
local __TS__Promise = ____lualib.__TS__Promise
local __TS__New = ____lualib.__TS__New
local __TS__AsyncAwaiter = ____lualib.__TS__AsyncAwaiter
local __TS__Await = ____lualib.__TS__Await
local ____exports = {}
local allLogs = {}
local function log(self, ...)
    __TS__ArrayPush(allLogs, ...)
end
local function defer(self)
    local function resolve()
    end
    local function reject()
    end
    local promise = __TS__New(
        __TS__Promise,
        function(____, res, rej)
            resolve = res
            reject = rej
        end
    )
    return {promise = promise, resolve = resolve, reject = reject}
end
function ____exports.__main(self)
    local ____defer_result_0 = defer(nil)
    local promise = ____defer_result_0.promise
    local resolve = ____defer_result_0.resolve
    promise["then"](
        promise,
        function(____, data) return log(nil, "resolving first promise", data) end
    )
    local function abc(self)
        return __TS__AsyncAwaiter(function(____awaiter_resolve)
            __TS__Await(promise)
            log(nil, "run abc")
            error("test throw", 0)
        end)
    end
    local awaitingPromise = abc(nil)
    awaitingPromise:catch(function(____, ____error) return log(nil, "caught error", ____error) end)
    resolve(nil, "resolved data")
    return allLogs
end
return ____exports`},
		{name: "can throw error after await in async function (\"const abc = async () => {\")", tsCode: `
// Some logging utility, useful for asserting orders of operations

const allLogs: any[] = [];
function log(...values: any[]) {
    allLogs.push(...values);
}

// Create a promise and store its resolve and reject functions, useful for creating pending promises

function defer<T>() {
    let resolve: (data: any) => void = () => {};
    let reject: (reason: string) => void = () => {};
    const promise = new Promise<T>((res, rej) => {
        resolve = res;
        reject = rej;
    });
    return { promise, resolve, reject };
}
export function __main() {const { promise, resolve } = defer<string>();
        promise.then(data => log("resolving first promise", data));

        const abc = async () => {
            await promise;
            log("run abc");
            throw "test throw";
        }

        const awaitingPromise = abc();
        awaitingPromise.catch(error => log("caught error", error));

        resolve("resolved data");
        return allLogs;}`, accessor: `mod.__main()`, want: `{"resolving first promise", "resolved data", "run abc", "caught error", "test throw"}`, refLua: `local ____lualib = require("lualib_bundle")
local __TS__ArrayPush = ____lualib.__TS__ArrayPush
local __TS__Promise = ____lualib.__TS__Promise
local __TS__New = ____lualib.__TS__New
local __TS__AsyncAwaiter = ____lualib.__TS__AsyncAwaiter
local __TS__Await = ____lualib.__TS__Await
local ____exports = {}
local allLogs = {}
local function log(self, ...)
    __TS__ArrayPush(allLogs, ...)
end
local function defer(self)
    local function resolve()
    end
    local function reject()
    end
    local promise = __TS__New(
        __TS__Promise,
        function(____, res, rej)
            resolve = res
            reject = rej
        end
    )
    return {promise = promise, resolve = resolve, reject = reject}
end
function ____exports.__main(self)
    local ____defer_result_0 = defer(nil)
    local promise = ____defer_result_0.promise
    local resolve = ____defer_result_0.resolve
    promise["then"](
        promise,
        function(____, data) return log(nil, "resolving first promise", data) end
    )
    local function abc()
        return __TS__AsyncAwaiter(function(____awaiter_resolve)
            __TS__Await(promise)
            log(nil, "run abc")
            error("test throw", 0)
        end)
    end
    local awaitingPromise = abc(nil)
    awaitingPromise:catch(function(____, ____error) return log(nil, "caught error", ____error) end)
    resolve(nil, "resolved data")
    return allLogs
end
return ____exports`},
		{name: "can throw object after await in async function (\"async function abc() {\")", tsCode: `
// Some logging utility, useful for asserting orders of operations

const allLogs: any[] = [];
function log(...values: any[]) {
    allLogs.push(...values);
}

// Create a promise and store its resolve and reject functions, useful for creating pending promises

function defer<T>() {
    let resolve: (data: any) => void = () => {};
    let reject: (reason: string) => void = () => {};
    const promise = new Promise<T>((res, rej) => {
        resolve = res;
        reject = rej;
    });
    return { promise, resolve, reject };
}
export function __main() {const { promise, resolve } = defer<string>();
        promise.then(data => log("resolving first promise", data));

        async function abc() {
            await promise;
            log("run abc");
            throw new Error("test throw");
        }

        const awaitingPromise = abc();
        awaitingPromise.catch(error => log("caught error", error));

        resolve("resolved data");
        return allLogs;}`, accessor: `mod.__main()`, want: `{"resolving first promise", "resolved data", "run abc", "caught error", {message = "test throw", name = "Error", stack = ~contains:stack traceback}}`, refLua: `local ____lualib = require("lualib_bundle")
local __TS__ArrayPush = ____lualib.__TS__ArrayPush
local __TS__Promise = ____lualib.__TS__Promise
local __TS__New = ____lualib.__TS__New
local __TS__AsyncAwaiter = ____lualib.__TS__AsyncAwaiter
local __TS__Await = ____lualib.__TS__Await
local Error = ____lualib.Error
local RangeError = ____lualib.RangeError
local ReferenceError = ____lualib.ReferenceError
local SyntaxError = ____lualib.SyntaxError
local TypeError = ____lualib.TypeError
local URIError = ____lualib.URIError
local ____exports = {}
local allLogs = {}
local function log(self, ...)
    __TS__ArrayPush(allLogs, ...)
end
local function defer(self)
    local function resolve()
    end
    local function reject()
    end
    local promise = __TS__New(
        __TS__Promise,
        function(____, res, rej)
            resolve = res
            reject = rej
        end
    )
    return {promise = promise, resolve = resolve, reject = reject}
end
function ____exports.__main(self)
    local ____defer_result_0 = defer(nil)
    local promise = ____defer_result_0.promise
    local resolve = ____defer_result_0.resolve
    promise["then"](
        promise,
        function(____, data) return log(nil, "resolving first promise", data) end
    )
    local function abc(self)
        return __TS__AsyncAwaiter(function(____awaiter_resolve)
            __TS__Await(promise)
            log(nil, "run abc")
            error(
                __TS__New(Error, "test throw"),
                0
            )
        end)
    end
    local awaitingPromise = abc(nil)
    awaitingPromise:catch(function(____, ____error) return log(nil, "caught error", ____error) end)
    resolve(nil, "resolved data")
    return allLogs
end
return ____exports`},
		{name: "can throw object after await in async function (\"const abc = async () => {\")", tsCode: `
// Some logging utility, useful for asserting orders of operations

const allLogs: any[] = [];
function log(...values: any[]) {
    allLogs.push(...values);
}

// Create a promise and store its resolve and reject functions, useful for creating pending promises

function defer<T>() {
    let resolve: (data: any) => void = () => {};
    let reject: (reason: string) => void = () => {};
    const promise = new Promise<T>((res, rej) => {
        resolve = res;
        reject = rej;
    });
    return { promise, resolve, reject };
}
export function __main() {const { promise, resolve } = defer<string>();
        promise.then(data => log("resolving first promise", data));

        const abc = async () => {
            await promise;
            log("run abc");
            throw new Error("test throw");
        }

        const awaitingPromise = abc();
        awaitingPromise.catch(error => log("caught error", error));

        resolve("resolved data");
        return allLogs;}`, accessor: `mod.__main()`, want: `{"resolving first promise", "resolved data", "run abc", "caught error", {message = "test throw", name = "Error", stack = ~contains:stack traceback}}`, refLua: `local ____lualib = require("lualib_bundle")
local __TS__ArrayPush = ____lualib.__TS__ArrayPush
local __TS__Promise = ____lualib.__TS__Promise
local __TS__New = ____lualib.__TS__New
local __TS__AsyncAwaiter = ____lualib.__TS__AsyncAwaiter
local __TS__Await = ____lualib.__TS__Await
local Error = ____lualib.Error
local RangeError = ____lualib.RangeError
local ReferenceError = ____lualib.ReferenceError
local SyntaxError = ____lualib.SyntaxError
local TypeError = ____lualib.TypeError
local URIError = ____lualib.URIError
local ____exports = {}
local allLogs = {}
local function log(self, ...)
    __TS__ArrayPush(allLogs, ...)
end
local function defer(self)
    local function resolve()
    end
    local function reject()
    end
    local promise = __TS__New(
        __TS__Promise,
        function(____, res, rej)
            resolve = res
            reject = rej
        end
    )
    return {promise = promise, resolve = resolve, reject = reject}
end
function ____exports.__main(self)
    local ____defer_result_0 = defer(nil)
    local promise = ____defer_result_0.promise
    local resolve = ____defer_result_0.resolve
    promise["then"](
        promise,
        function(____, data) return log(nil, "resolving first promise", data) end
    )
    local function abc()
        return __TS__AsyncAwaiter(function(____awaiter_resolve)
            __TS__Await(promise)
            log(nil, "run abc")
            error(
                __TS__New(Error, "test throw"),
                0
            )
        end)
    end
    local awaitingPromise = abc(nil)
    awaitingPromise:catch(function(____, ____error) return log(nil, "caught error", ____error) end)
    resolve(nil, "resolved data")
    return allLogs
end
return ____exports`},
		{name: "try/catch in async function async function adopts pending promise in try", tsCode: `
// Some logging utility, useful for asserting orders of operations

const allLogs: any[] = [];
function log(...values: any[]) {
    allLogs.push(...values);
}

// Create a promise and store its resolve and reject functions, useful for creating pending promises

function defer<T>() {
    let resolve: (data: any) => void = () => {};
    let reject: (reason: string) => void = () => {};
    const promise = new Promise<T>((res, rej) => {
        resolve = res;
        reject = rej;
    });
    return { promise, resolve, reject };
}
export function __main() {let resolve: (v: string) => void = () => {};
            async function receive(): Promise<string> {
                try
                {
                    return new Promise(res => {
                        resolve = res;
                    });
                }
                catch
                {
                    return "" as string;
                }
            }

            receive().then(v => {
                log(v);
            });

            resolve("delayed resolve");

            return allLogs;}`, accessor: `mod.__main()`, want: `{"delayed resolve"}`, refLua: `local ____lualib = require("lualib_bundle")
local __TS__ArrayPush = ____lualib.__TS__ArrayPush
local __TS__Promise = ____lualib.__TS__Promise
local __TS__New = ____lualib.__TS__New
local __TS__AsyncAwaiter = ____lualib.__TS__AsyncAwaiter
local __TS__Await = ____lualib.__TS__Await
local ____exports = {}
local allLogs = {}
local function log(self, ...)
    __TS__ArrayPush(allLogs, ...)
end
local function defer(self)
    local function resolve()
    end
    local function reject()
    end
    local promise = __TS__New(
        __TS__Promise,
        function(____, res, rej)
            resolve = res
            reject = rej
        end
    )
    return {promise = promise, resolve = resolve, reject = reject}
end
function ____exports.__main(self)
    local function resolve()
    end
    local function receive(self)
        return __TS__AsyncAwaiter(function(____awaiter_resolve)
            local ____try = __TS__AsyncAwaiter(function()
                return ____awaiter_resolve(
                    nil,
                    __TS__New(
                        __TS__Promise,
                        function(____, res)
                            resolve = res
                        end
                    )
                )
            end)
            __TS__Await(____try.catch(
                ____try,
                function(____)
                    return ____awaiter_resolve(nil, "")
                end
            ))
        end)
    end
    local ____self_0 = receive(nil)
    ____self_0["then"](
        ____self_0,
        function(____, v)
            log(nil, v)
        end
    )
    resolve(nil, "delayed resolve")
    return allLogs
end
return ____exports`},
	})

	batchExpectDiagnostics(t, []diagTestCase{
		{"cannot await at top-level (\"await a();\")", "module", `async function a() {
            return 42;
        }

        await a();
        export {} // Required to make TS happy, cannot await without import/exports`, []int32{100039}, nil},
		{"cannot await at top-level (\"const b = await a();\")", "module", `async function a() {
            return 42;
        }

        const b = await a();
        export {} // Required to make TS happy, cannot await without import/exports`, []int32{100039}, nil},
		{"cannot await at top-level (\"export const b = await a();\")", "module", `async function a() {
            return 42;
        }

        export const b = await a();
        export {} // Required to make TS happy, cannot await without import/exports`, []int32{100039}, nil},
		{"cannot await at top-level (\"declare function foo(n: number): number; foo(await a());\")", "module", `async function a() {
            return 42;
        }

        declare function foo(n: number): number; foo(await a());
        export {} // Required to make TS happy, cannot await without import/exports`, []int32{100039}, nil},
		{"cannot await at top-level (\"declare function foo(n: number): number; const b = foo(await a());\")", "module", `async function a() {
            return 42;
        }

        declare function foo(n: number): number; const b = foo(await a());
        export {} // Required to make TS happy, cannot await without import/exports`, []int32{100039}, nil},
		{"cannot await at top-level (\"const b = [await a()];\")", "module", `async function a() {
            return 42;
        }

        const b = [await a()];
        export {} // Required to make TS happy, cannot await without import/exports`, []int32{100039}, nil},
		{"cannot await at top-level (\"const b = [4, await a()];\")", "module", `async function a() {
            return 42;
        }

        const b = [4, await a()];
        export {} // Required to make TS happy, cannot await without import/exports`, []int32{100039}, nil},
		{"cannot await at top-level (\"const b = true ? 4 : await a();\")", "module", `async function a() {
            return 42;
        }

        const b = true ? 4 : await a();
        export {} // Required to make TS happy, cannot await without import/exports`, []int32{100039}, nil},
	})

	batchExpectDiagnostics(t, []diagTestCase{
		{"await inside try/catch returns inside async function [5.0]", "module", `export let result = 0;
            async function foo(): Promise<number> {
                try {
                    return await new Promise(resolve => resolve(4));
                } catch {
                    throw "an error occurred in the async function"
                }
            }
            foo().then(value => {
                result = value;
            });`, []int32{100028}, nil},
		{"await inside try/catch throws inside async function [5.0]", "module", `export let reason = "";
            async function foo(): Promise<number> {
                try {
                    return await new Promise((resolve, reject) => reject("test error"));
                } catch (e) {
                    throw "an error occurred in the async function: " + e;
                }
            }
            foo().catch(e => {
                reason = e;
            });`, []int32{100028}, nil},
		{"await inside try/catch deferred rejection uses catch clause [5.0]", "module", `export let reason = "";
            let reject: (reason: string) => void = () => {};

            async function foo(): Promise<number> {
                try {
                    return await new Promise((res, rej) => { reject = rej; });
                } catch (e) {
                    throw "an error occurred in the async function: " + e;
                }
            }
            foo().catch(e => {
                reason = e;
            });
            reject("test error");`, []int32{100028}, nil},
	}, WithLuaTarget(transpiler.LuaTargetLua50))

	batchExpectDiagnostics(t, []diagTestCase{
		{"await inside try/catch returns inside async function [5.1]", "module", `export let result = 0;
            async function foo(): Promise<number> {
                try {
                    return await new Promise(resolve => resolve(4));
                } catch {
                    throw "an error occurred in the async function"
                }
            }
            foo().then(value => {
                result = value;
            });`, []int32{100028}, nil},
		{"await inside try/catch throws inside async function [5.1]", "module", `export let reason = "";
            async function foo(): Promise<number> {
                try {
                    return await new Promise((resolve, reject) => reject("test error"));
                } catch (e) {
                    throw "an error occurred in the async function: " + e;
                }
            }
            foo().catch(e => {
                reason = e;
            });`, []int32{100028}, nil},
		{"await inside try/catch deferred rejection uses catch clause [5.1]", "module", `export let reason = "";
            let reject: (reason: string) => void = () => {};

            async function foo(): Promise<number> {
                try {
                    return await new Promise((res, rej) => { reject = rej; });
                } catch (e) {
                    throw "an error occurred in the async function: " + e;
                }
            }
            foo().catch(e => {
                reason = e;
            });
            reject("test error");`, []int32{100028}, nil},
	}, WithLuaTarget(transpiler.LuaTargetLua51))

	batchExpectDiagnostics(t, []diagTestCase{
		{"await inside try/catch returns inside async function [universal]", "module", `export let result = 0;
            async function foo(): Promise<number> {
                try {
                    return await new Promise(resolve => resolve(4));
                } catch {
                    throw "an error occurred in the async function"
                }
            }
            foo().then(value => {
                result = value;
            });`, []int32{100028}, nil},
		{"await inside try/catch throws inside async function [universal]", "module", `export let reason = "";
            async function foo(): Promise<number> {
                try {
                    return await new Promise((resolve, reject) => reject("test error"));
                } catch (e) {
                    throw "an error occurred in the async function: " + e;
                }
            }
            foo().catch(e => {
                reason = e;
            });`, []int32{100028}, nil},
		{"await inside try/catch deferred rejection uses catch clause [universal]", "module", `export let reason = "";
            let reject: (reason: string) => void = () => {};

            async function foo(): Promise<number> {
                try {
                    return await new Promise((res, rej) => { reject = rej; });
                } catch (e) {
                    throw "an error occurred in the async function: " + e;
                }
            }
            foo().catch(e => {
                reason = e;
            });
            reject("test error");`, []int32{100028}, nil},
	}, WithLuaTarget(transpiler.LuaTargetUniversal))

	t.Run("can call async function at top-level", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `export let aStarted = false;
        async function a() {
            aStarted = true;
            return 42;
        }

        a(); // Call async function (but cannot await)`, `{aStarted = true}`, WithOptions(map[string]any{"module": 99, "target": 4}))
	})

	t.Run("await inside try/catch returns inside async function [JIT]", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `export let result = 0;
            async function foo(): Promise<number> {
                try {
                    return await new Promise(resolve => resolve(4));
                } catch {
                    throw "an error occurred in the async function"
                }
            }
            foo().then(value => {
                result = value;
            });`, `{result = 4}`, WithLuaTarget(transpiler.LuaTargetLuaJIT))
	})

	t.Run("await inside try/catch returns inside async function [5.2]", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `export let result = 0;
            async function foo(): Promise<number> {
                try {
                    return await new Promise(resolve => resolve(4));
                } catch {
                    throw "an error occurred in the async function"
                }
            }
            foo().then(value => {
                result = value;
            });`, `{result = 4}`, WithLuaTarget(transpiler.LuaTargetLua52))
	})

	t.Run("await inside try/catch returns inside async function [5.3]", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `export let result = 0;
            async function foo(): Promise<number> {
                try {
                    return await new Promise(resolve => resolve(4));
                } catch {
                    throw "an error occurred in the async function"
                }
            }
            foo().then(value => {
                result = value;
            });`, `{result = 4}`, WithLuaTarget(transpiler.LuaTargetLua53))
	})

	t.Run("await inside try/catch returns inside async function [5.4]", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `export let result = 0;
            async function foo(): Promise<number> {
                try {
                    return await new Promise(resolve => resolve(4));
                } catch {
                    throw "an error occurred in the async function"
                }
            }
            foo().then(value => {
                result = value;
            });`, `{result = 4}`, WithLuaTarget(transpiler.LuaTargetLua54))
	})

	t.Run("await inside try/catch returns inside async function [5.5]", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `export let result = 0;
            async function foo(): Promise<number> {
                try {
                    return await new Promise(resolve => resolve(4));
                } catch {
                    throw "an error occurred in the async function"
                }
            }
            foo().then(value => {
                result = value;
            });`, `{result = 4}`, WithLuaTarget(transpiler.LuaTargetLua55))
	})

	t.Run("await inside try/catch throws inside async function [JIT]", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `export let reason = "";
            async function foo(): Promise<number> {
                try {
                    return await new Promise((resolve, reject) => reject("test error"));
                } catch (e) {
                    throw "an error occurred in the async function: " + e;
                }
            }
            foo().catch(e => {
                reason = e;
            });`, `{reason = "an error occurred in the async function: test error"}`, WithLuaTarget(transpiler.LuaTargetLuaJIT))
	})

	t.Run("await inside try/catch throws inside async function [5.2]", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `export let reason = "";
            async function foo(): Promise<number> {
                try {
                    return await new Promise((resolve, reject) => reject("test error"));
                } catch (e) {
                    throw "an error occurred in the async function: " + e;
                }
            }
            foo().catch(e => {
                reason = e;
            });`, `{reason = "an error occurred in the async function: test error"}`, WithLuaTarget(transpiler.LuaTargetLua52))
	})

	t.Run("await inside try/catch throws inside async function [5.3]", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `export let reason = "";
            async function foo(): Promise<number> {
                try {
                    return await new Promise((resolve, reject) => reject("test error"));
                } catch (e) {
                    throw "an error occurred in the async function: " + e;
                }
            }
            foo().catch(e => {
                reason = e;
            });`, `{reason = "an error occurred in the async function: test error"}`, WithLuaTarget(transpiler.LuaTargetLua53))
	})

	t.Run("await inside try/catch throws inside async function [5.4]", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `export let reason = "";
            async function foo(): Promise<number> {
                try {
                    return await new Promise((resolve, reject) => reject("test error"));
                } catch (e) {
                    throw "an error occurred in the async function: " + e;
                }
            }
            foo().catch(e => {
                reason = e;
            });`, `{reason = "an error occurred in the async function: test error"}`, WithLuaTarget(transpiler.LuaTargetLua54))
	})

	t.Run("await inside try/catch throws inside async function [5.5]", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `export let reason = "";
            async function foo(): Promise<number> {
                try {
                    return await new Promise((resolve, reject) => reject("test error"));
                } catch (e) {
                    throw "an error occurred in the async function: " + e;
                }
            }
            foo().catch(e => {
                reason = e;
            });`, `{reason = "an error occurred in the async function: test error"}`, WithLuaTarget(transpiler.LuaTargetLua55))
	})

	t.Run("await inside try/catch deferred rejection uses catch clause [JIT]", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `export let reason = "";
            let reject: (reason: string) => void = () => {};

            async function foo(): Promise<number> {
                try {
                    return await new Promise((res, rej) => { reject = rej; });
                } catch (e) {
                    throw "an error occurred in the async function: " + e;
                }
            }
            foo().catch(e => {
                reason = e;
            });
            reject("test error");`, `{reason = "an error occurred in the async function: test error"}`, WithLuaTarget(transpiler.LuaTargetLuaJIT))
	})

	t.Run("await inside try/catch deferred rejection uses catch clause [5.2]", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `export let reason = "";
            let reject: (reason: string) => void = () => {};

            async function foo(): Promise<number> {
                try {
                    return await new Promise((res, rej) => { reject = rej; });
                } catch (e) {
                    throw "an error occurred in the async function: " + e;
                }
            }
            foo().catch(e => {
                reason = e;
            });
            reject("test error");`, `{reason = "an error occurred in the async function: test error"}`, WithLuaTarget(transpiler.LuaTargetLua52))
	})

	t.Run("await inside try/catch deferred rejection uses catch clause [5.3]", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `export let reason = "";
            let reject: (reason: string) => void = () => {};

            async function foo(): Promise<number> {
                try {
                    return await new Promise((res, rej) => { reject = rej; });
                } catch (e) {
                    throw "an error occurred in the async function: " + e;
                }
            }
            foo().catch(e => {
                reason = e;
            });
            reject("test error");`, `{reason = "an error occurred in the async function: test error"}`, WithLuaTarget(transpiler.LuaTargetLua53))
	})

	t.Run("await inside try/catch deferred rejection uses catch clause [5.4]", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `export let reason = "";
            let reject: (reason: string) => void = () => {};

            async function foo(): Promise<number> {
                try {
                    return await new Promise((res, rej) => { reject = rej; });
                } catch (e) {
                    throw "an error occurred in the async function: " + e;
                }
            }
            foo().catch(e => {
                reason = e;
            });
            reject("test error");`, `{reason = "an error occurred in the async function: test error"}`, WithLuaTarget(transpiler.LuaTargetLua54))
	})

	t.Run("await inside try/catch deferred rejection uses catch clause [5.5]", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `export let reason = "";
            let reject: (reason: string) => void = () => {};

            async function foo(): Promise<number> {
                try {
                    return await new Promise((res, rej) => { reject = rej; });
                } catch (e) {
                    throw "an error occurred in the async function: " + e;
                }
            }
            foo().catch(e => {
                reason = e;
            });
            reject("test error");`, `{reason = "an error occurred in the async function: test error"}`, WithLuaTarget(transpiler.LuaTargetLua55))
	})
}
