// Code generated by scripts/migrate from extern/tstl/test/unit/annotations/compileMembersOnly.spec.ts. DO NOT EDIT.
package tstltest

import "testing"

func TestEval_CompileMembersOnly(t *testing.T) {
	t.Parallel()

	batchExpectFunctions(t, []funcTestCase{
		{"@compileMembersOnly", `/** @compileMembersOnly */
        enum TestEnum {
            A = 0,
            B = 2,
            C,
            D = "D",
        }

        return { A: TestEnum.A, B: TestEnum.B, C: TestEnum.C, D: TestEnum.D };`, `{A = 0, B = 2, C = 3, D = "D"}`, `local ____exports = {}
function ____exports.__main(self)
    local TestEnum = TestEnum or ({})
    TestEnum.A = 0
    TestEnum[TestEnum.A] = "A"
    TestEnum.B = 2
    TestEnum[TestEnum.B] = "B"
    TestEnum.C = 3
    TestEnum[TestEnum.C] = "C"
    TestEnum.D = "D"
    return {A = TestEnum.A, B = TestEnum.B, C = TestEnum.C, D = TestEnum.D}
end
return ____exports`, false, false},
	})

	batchRunTests(t, []batchTestCase{
		{name: "@compileMembersOnly in a namespace", tsCode: `namespace Test {
            /** @compileMembersOnly */
            export enum TestEnum {
                A = "A",
                B = "B",
            }
        }

        export const A = Test.TestEnum.A;`, accessor: `mod["A"]`, want: `"A"`, refLua: `local ____exports = {}
local Test = {}
do
    ---
    -- @compileMembersOnly
    Test.A = "A"
    ---
    -- @compileMembersOnly
    Test.B = "B"
end
____exports.A = Test.A
return ____exports`},
	})

	batchExpectCodegen(t, []codegenTestCase{
		{"@compileMembersOnly", "function", `/** @compileMembersOnly */
        enum TestEnum {
            A = 0,
            B = 2,
            C,
            D = "D",
        }

        return { A: TestEnum.A, B: TestEnum.B, C: TestEnum.C, D: TestEnum.D };`, nil, []string{`TestEnum`}, nil, nil},
		{"@compileMembersOnly in a namespace", "module", `namespace Test {
            /** @compileMembersOnly */
            export enum TestEnum {
                A = "A",
                B = "B",
            }
        }

        export const A = Test.TestEnum.A;`, []string{`Test.A`}, nil, nil, nil},
	})
}
