// Code generated by scripts/migrate from extern/tstl/test/unit/conditionals.spec.ts. DO NOT EDIT.
package tstltest

import (
	"testing"

	"github.com/realcoldfry/tslua/internal/transpiler"
)

func TestEval_Conditionals(t *testing.T) {
	t.Parallel()

	batchExpectExpressions(t, []exprTestCase{
		{"Ternary Conditional ({\"condition\":true,\"lhs\":4,\"rhs\":5})", `true ? 4 : 5`, `4`, `local ____exports = {}
____exports.__result = true and 4 or 5
return ____exports`, false, true},
		{"Ternary Conditional ({\"condition\":false,\"lhs\":4,\"rhs\":5})", `false ? 4 : 5`, `5`, `local ____exports = {}
____exports.__result = false and 4 or 5
return ____exports`, false, true},
		{"Ternary Conditional ({\"condition\":3,\"lhs\":4,\"rhs\":5})", `3 ? 4 : 5`, `4`, `local ____exports = {}
____exports.__result = 3 and 4 or 5
return ____exports`, false, true},
	})

	batchExpectFunctions(t, []funcTestCase{
		{"if (0)", `let input: number = 0;
        if (input === 0) {
            return 0;
        }
        return 1;`, `0`, `local ____exports = {}
function ____exports.__main(self)
    local input = 0
    if input == 0 then
        return 0
    end
    return 1
end
return ____exports`, false, false},
		{"if (1)", `let input: number = 1;
        if (input === 0) {
            return 0;
        }
        return 1;`, `1`, `local ____exports = {}
function ____exports.__main(self)
    local input = 1
    if input == 0 then
        return 0
    end
    return 1
end
return ____exports`, false, false},
		{"ifelse (0)", `let input: number = 0;
        if (input === 0) {
            return 0;
        } else {
            return 1;
        }`, `0`, `local ____exports = {}
function ____exports.__main(self)
    local input = 0
    if input == 0 then
        return 0
    else
        return 1
    end
end
return ____exports`, false, false},
		{"ifelse (1)", `let input: number = 1;
        if (input === 0) {
            return 0;
        } else {
            return 1;
        }`, `1`, `local ____exports = {}
function ____exports.__main(self)
    local input = 1
    if input == 0 then
        return 0
    else
        return 1
    end
end
return ____exports`, false, false},
		{"ifelseif (0)", `let input: number = 0;
        if (input === 0) {
            return 0;
        } else if (input === 1){
            return 1;
        } else if (input === 2){
            return 2;
        }
        return 3;`, `0`, `local ____exports = {}
function ____exports.__main(self)
    local input = 0
    if input == 0 then
        return 0
    elseif input == 1 then
        return 1
    elseif input == 2 then
        return 2
    end
    return 3
end
return ____exports`, false, false},
		{"ifelseif (1)", `let input: number = 1;
        if (input === 0) {
            return 0;
        } else if (input === 1){
            return 1;
        } else if (input === 2){
            return 2;
        }
        return 3;`, `1`, `local ____exports = {}
function ____exports.__main(self)
    local input = 1
    if input == 0 then
        return 0
    elseif input == 1 then
        return 1
    elseif input == 2 then
        return 2
    end
    return 3
end
return ____exports`, false, false},
		{"ifelseif (2)", `let input: number = 2;
        if (input === 0) {
            return 0;
        } else if (input === 1){
            return 1;
        } else if (input === 2){
            return 2;
        }
        return 3;`, `2`, `local ____exports = {}
function ____exports.__main(self)
    local input = 2
    if input == 0 then
        return 0
    elseif input == 1 then
        return 1
    elseif input == 2 then
        return 2
    end
    return 3
end
return ____exports`, false, false},
		{"ifelseif (3)", `let input: number = 3;
        if (input === 0) {
            return 0;
        } else if (input === 1){
            return 1;
        } else if (input === 2){
            return 2;
        }
        return 3;`, `3`, `local ____exports = {}
function ____exports.__main(self)
    local input = 3
    if input == 0 then
        return 0
    elseif input == 1 then
        return 1
    elseif input == 2 then
        return 2
    end
    return 3
end
return ____exports`, false, false},
		{"ifelseifelse (0)", `let input: number = 0;
        if (input === 0) {
            return 0;
        } else if (input === 1){
            return 1;
        } else if (input === 2){
            return 2;
        } else {
            return 3;
        }`, `0`, `local ____exports = {}
function ____exports.__main(self)
    local input = 0
    if input == 0 then
        return 0
    elseif input == 1 then
        return 1
    elseif input == 2 then
        return 2
    else
        return 3
    end
end
return ____exports`, false, false},
		{"ifelseifelse (1)", `let input: number = 1;
        if (input === 0) {
            return 0;
        } else if (input === 1){
            return 1;
        } else if (input === 2){
            return 2;
        } else {
            return 3;
        }`, `1`, `local ____exports = {}
function ____exports.__main(self)
    local input = 1
    if input == 0 then
        return 0
    elseif input == 1 then
        return 1
    elseif input == 2 then
        return 2
    else
        return 3
    end
end
return ____exports`, false, false},
		{"ifelseifelse (2)", `let input: number = 2;
        if (input === 0) {
            return 0;
        } else if (input === 1){
            return 1;
        } else if (input === 2){
            return 2;
        } else {
            return 3;
        }`, `2`, `local ____exports = {}
function ____exports.__main(self)
    local input = 2
    if input == 0 then
        return 0
    elseif input == 1 then
        return 1
    elseif input == 2 then
        return 2
    else
        return 3
    end
end
return ____exports`, false, false},
		{"ifelseifelse (3)", `let input: number = 3;
        if (input === 0) {
            return 0;
        } else if (input === 1){
            return 1;
        } else if (input === 2){
            return 2;
        } else {
            return 3;
        }`, `3`, `local ____exports = {}
function ____exports.__main(self)
    local input = 3
    if input == 0 then
        return 0
    elseif input == 1 then
        return 1
    elseif input == 2 then
        return 2
    else
        return 3
    end
end
return ____exports`, false, false},
		{"Ternary Conditional Delayed (\"true\")", `let a = 3;
        let delay = () => true ? a + 3 : a + 5;
        a = 8;
        return delay();`, `11`, `local ____exports = {}
function ____exports.__main(self)
    local a = 3
    local function delay()
        local ____temp_0
        if true then
            ____temp_0 = a + 3
        else
            ____temp_0 = a + 5
        end
        return ____temp_0
    end
    a = 8
    return delay(nil)
end
return ____exports`, false, false},
		{"Ternary Conditional Delayed (\"false\")", `let a = 3;
        let delay = () => false ? a + 3 : a + 5;
        a = 8;
        return delay();`, `13`, `local ____exports = {}
function ____exports.__main(self)
    local a = 3
    local function delay()
        local ____temp_0
        if false then
            ____temp_0 = a + 3
        else
            ____temp_0 = a + 5
        end
        return ____temp_0
    end
    a = 8
    return delay(nil)
end
return ____exports`, false, false},
		{"Ternary Conditional Delayed (\"a < 4\")", `let a = 3;
        let delay = () => a < 4 ? a + 3 : a + 5;
        a = 8;
        return delay();`, `13`, `local ____exports = {}
function ____exports.__main(self)
    local a = 3
    local function delay()
        local ____temp_0
        if a < 4 then
            ____temp_0 = a + 3
        else
            ____temp_0 = a + 5
        end
        return ____temp_0
    end
    a = 8
    return delay(nil)
end
return ____exports`, false, false},
		{"Ternary Conditional Delayed (\"a == 8\")", `let a = 3;
        let delay = () => a == 8 ? a + 3 : a + 5;
        a = 8;
        return delay();`, `11`, `local ____exports = {}
function ____exports.__main(self)
    local a = 3
    local function delay()
        local ____temp_0
        if a == 8 then
            ____temp_0 = a + 3
        else
            ____temp_0 = a + 5
        end
        return ____temp_0
    end
    a = 8
    return delay(nil)
end
return ____exports`, false, false},
	})

	batchExpectDiagnostics(t, []diagTestCase{
		{"Warning when using if statement that cannot evaluate to false undefined or null (\"string\")", "function", `declare var condition: string;
if (condition) {}`, nil, nil},
		{"Warning when using if statement that cannot evaluate to false undefined or null (\"number\")", "function", `declare var condition: number;
if (condition) {}`, nil, nil},
		{"Warning when using if statement that cannot evaluate to false undefined or null (\"string | number\")", "function", `declare var condition: string | number;
if (condition) {}`, nil, nil},
		{"Warning when using while statement that cannot evaluate to false undefined or null (\"string\")", "function", `declare var condition: string;
while (condition) {}`, nil, nil},
		{"Warning when using while statement that cannot evaluate to false undefined or null (\"number\")", "function", `declare var condition: number;
while (condition) {}`, nil, nil},
		{"Warning when using while statement that cannot evaluate to false undefined or null (\"string | number\")", "function", `declare var condition: string | number;
while (condition) {}`, nil, nil},
		{"Warning when using do while statement that cannot evaluate to false undefined or null (\"string\")", "function", `declare var condition: string;
do {} while (condition)`, nil, nil},
		{"Warning when using do while statement that cannot evaluate to false undefined or null (\"number\")", "function", `declare var condition: number;
do {} while (condition)`, nil, nil},
		{"Warning when using do while statement that cannot evaluate to false undefined or null (\"string | number\")", "function", `declare var condition: string | number;
do {} while (condition)`, nil, nil},
		{"Warning when using ternary that cannot evaluate to false undefined or null (\"string\")", "module", `declare var condition: string;
export const __result = condition ? 1 : 0;`, nil, nil},
		{"Warning when using ternary that cannot evaluate to false undefined or null (\"number\")", "module", `declare var condition: number;
export const __result = condition ? 1 : 0;`, nil, nil},
		{"Warning when using ternary that cannot evaluate to false undefined or null (\"string | number\")", "module", `declare var condition: string | number;
export const __result = condition ? 1 : 0;`, nil, nil},
	})

	t.Run("Ternary operator ({\"input\":\"true ? maybeUndefinedValue : true\",\"options\":{\"strictNullChecks\":true}})", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `const literalValue = "literal";
        let variableValue: string = "variable";
        let maybeBooleanValue: string | boolean = false;
        let maybeUndefinedValue: string | undefined;
        return true ? maybeUndefinedValue : true;`, `nil`, WithOptions(map[string]any{"strictNullChecks": true}))
	})

	t.Run("Ternary operator ({\"input\":\"true ? maybeBooleanValue : true\",\"options\":{\"strictNullChecks\":true}})", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `const literalValue = "literal";
        let variableValue: string = "variable";
        let maybeBooleanValue: string | boolean = false;
        let maybeUndefinedValue: string | undefined;
        return true ? maybeBooleanValue : true;`, `false`, WithOptions(map[string]any{"strictNullChecks": true}))
	})

	t.Run("Ternary operator ({\"input\":\"true ? undefined : true\",\"options\":{\"strictNullChecks\":true}})", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `const literalValue = "literal";
        let variableValue: string = "variable";
        let maybeBooleanValue: string | boolean = false;
        let maybeUndefinedValue: string | undefined;
        return true ? undefined : true;`, `nil`, WithOptions(map[string]any{"strictNullChecks": true}))
	})

	t.Run("Ternary operator ({\"input\":\"true ? null : true\",\"options\":{\"strictNullChecks\":true}})", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `const literalValue = "literal";
        let variableValue: string = "variable";
        let maybeBooleanValue: string | boolean = false;
        let maybeUndefinedValue: string | undefined;
        return true ? null : true;`, `nil`, WithOptions(map[string]any{"strictNullChecks": true}))
	})

	t.Run("Ternary operator ({\"input\":\"true ? false : true\",\"options\":{\"luaTarget\":\"Lua 5.1\"}})", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `const literalValue = "literal";
        let variableValue: string = "variable";
        let maybeBooleanValue: string | boolean = false;
        let maybeUndefinedValue: string | undefined;
        return true ? false : true;`, `false`, WithLuaTarget(transpiler.LuaTargetLua51))
	})

	t.Run("Ternary operator ({\"input\":\"false ? false : true\",\"options\":{\"luaTarget\":\"Lua 5.1\"}})", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `const literalValue = "literal";
        let variableValue: string = "variable";
        let maybeBooleanValue: string | boolean = false;
        let maybeUndefinedValue: string | undefined;
        return false ? false : true;`, `true`, WithLuaTarget(transpiler.LuaTargetLua51))
	})

	t.Run("Ternary operator ({\"input\":\"true ? undefined : true\",\"options\":{\"luaTarget\":\"Lua 5.1\"}})", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `const literalValue = "literal";
        let variableValue: string = "variable";
        let maybeBooleanValue: string | boolean = false;
        let maybeUndefinedValue: string | undefined;
        return true ? undefined : true;`, `nil`, WithLuaTarget(transpiler.LuaTargetLua51))
	})

	t.Run("Ternary conditional with generic whenTrue branch (false)", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function ternary<B, C>(a: boolean, b: B, c: C) {
            return a ? b : c
        }
        return ternary(true, false, "wasFalse")`, `false`, WithOptions(map[string]any{"strictNullChecks": true}))
	})

	t.Run("Ternary conditional with generic whenTrue branch (true)", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function ternary<B, C>(a: boolean, b: B, c: C) {
            return a ? b : c
        }
        return ternary(true, true, "wasFalse")`, `true`, WithOptions(map[string]any{"strictNullChecks": true}))
	})

	t.Run("Ternary conditional with generic whenTrue branch (null)", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function ternary<B, C>(a: boolean, b: B, c: C) {
            return a ? b : c
        }
        return ternary(true, null, "wasFalse")`, `nil`, WithOptions(map[string]any{"strictNullChecks": true}))
	})

	t.Run("Ternary conditional with preceding statements in true branch (false)", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `let i = 0;
        const result = false ? i += 1 : i;
        return { result, i };`, `{i = 0, result = 0}`, WithOptions(map[string]any{"strictNullChecks": true}))
	})

	t.Run("Ternary conditional with preceding statements in true branch (true)", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `let i = 0;
        const result = true ? i += 1 : i;
        return { result, i };`, `{i = 1, result = 1}`, WithOptions(map[string]any{"strictNullChecks": true}))
	})

	t.Run("Ternary conditional with preceding statements in false branch (false)", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `let i = 0;
        const result = false ? i : i += 2;
        return { result, i };`, `{i = 2, result = 2}`, WithOptions(map[string]any{"strictNullChecks": true}))
	})

	t.Run("Ternary conditional with preceding statements in false branch (true)", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `let i = 0;
        const result = true ? i : i += 2;
        return { result, i };`, `{i = 0, result = 0}`, WithOptions(map[string]any{"strictNullChecks": true}))
	})
}
