// Code generated by scripts/migrate from extern/tstl/test/unit/builtins/console.spec.ts. DO NOT EDIT.
package tstltest

import "testing"

func TestEval_Console(t *testing.T) {
	t.Parallel()

	batchRunTests(t, []batchTestCase{
		{name: "console.differentiation", tsCode: `export class Console {
            public test() {
                return 42;
            }
        }

        function test() {
            const console = new Console();
            return console.test();
        }

        export const result = test();`, accessor: `mod["result"]`, want: `42`, refLua: `local ____lualib = require("lualib_bundle")
local __TS__Class = ____lualib.__TS__Class
local __TS__New = ____lualib.__TS__New
local ____exports = {}
____exports.Console = __TS__Class()
local Console = ____exports.Console
Console.name = "Console"
function Console.prototype.____constructor(self)
end
function Console.prototype.test(self)
    return 42
end
local function test(self)
    local console = __TS__New(____exports.Console)
    return console:test()
end
____exports.result = test(nil)
return ____exports`},
	})

	batchCompareCodegen(t, []batchTestCase{
		{name: "console.log (\"console.log()\")", tsCode: `export function __main() {console.log()}`, refLua: `local ____exports = {}
function ____exports.__main(self)
    print()
end
return ____exports`},
		{name: "console.log (\"console.log(\\\"Hello\\\")\")", tsCode: `export function __main() {console.log("Hello")}`, refLua: `local ____exports = {}
function ____exports.__main(self)
    print("Hello")
end
return ____exports`},
		{name: "console.log (\"console.log(\\\"Hello %s\\\", \\\"there\\\")\")", tsCode: `export function __main() {console.log("Hello %s", "there")}`, refLua: `local ____exports = {}
function ____exports.__main(self)
    print(string.format("Hello %s", "there"))
end
return ____exports`},
		{name: "console.log (\"console.log(\\\"Hello %%s\\\", \\\"there\\\")\")", tsCode: `export function __main() {console.log("Hello %%s", "there")}`, refLua: `local ____exports = {}
function ____exports.__main(self)
    print(string.format("Hello %%s", "there"))
end
return ____exports`},
		{name: "console.log (\"console.log(\\\"Hello\\\", \\\"There\\\")\")", tsCode: `export function __main() {console.log("Hello", "There")}`, refLua: `local ____exports = {}
function ____exports.__main(self)
    print("Hello", "There")
end
return ____exports`},
		{name: "console.info (\"console.info()\")", tsCode: `export function __main() {console.info()}`, refLua: `local ____exports = {}
function ____exports.__main(self)
    print()
end
return ____exports`},
		{name: "console.info (\"console.info(\\\"Hello\\\")\")", tsCode: `export function __main() {console.info("Hello")}`, refLua: `local ____exports = {}
function ____exports.__main(self)
    print("Hello")
end
return ____exports`},
		{name: "console.info (\"console.info(\\\"Hello %s\\\", \\\"there\\\")\")", tsCode: `export function __main() {console.info("Hello %s", "there")}`, refLua: `local ____exports = {}
function ____exports.__main(self)
    print(string.format("Hello %s", "there"))
end
return ____exports`},
		{name: "console.info (\"console.info(\\\"Hello %%s\\\", \\\"there\\\")\")", tsCode: `export function __main() {console.info("Hello %%s", "there")}`, refLua: `local ____exports = {}
function ____exports.__main(self)
    print(string.format("Hello %%s", "there"))
end
return ____exports`},
		{name: "console.info (\"console.info(\\\"Hello\\\", \\\"There\\\")\")", tsCode: `export function __main() {console.info("Hello", "There")}`, refLua: `local ____exports = {}
function ____exports.__main(self)
    print("Hello", "There")
end
return ____exports`},
		{name: "console.error (\"console.error()\")", tsCode: `export function __main() {console.error()}`, refLua: `local ____exports = {}
function ____exports.__main(self)
    print()
end
return ____exports`},
		{name: "console.error (\"console.error(\\\"Hello\\\")\")", tsCode: `export function __main() {console.error("Hello")}`, refLua: `local ____exports = {}
function ____exports.__main(self)
    print("Hello")
end
return ____exports`},
		{name: "console.error (\"console.error(\\\"Hello %s\\\", \\\"there\\\")\")", tsCode: `export function __main() {console.error("Hello %s", "there")}`, refLua: `local ____exports = {}
function ____exports.__main(self)
    print(string.format("Hello %s", "there"))
end
return ____exports`},
		{name: "console.error (\"console.error(\\\"Hello %%s\\\", \\\"there\\\")\")", tsCode: `export function __main() {console.error("Hello %%s", "there")}`, refLua: `local ____exports = {}
function ____exports.__main(self)
    print(string.format("Hello %%s", "there"))
end
return ____exports`},
		{name: "console.error (\"console.error(\\\"Hello\\\", \\\"There\\\")\")", tsCode: `export function __main() {console.error("Hello", "There")}`, refLua: `local ____exports = {}
function ____exports.__main(self)
    print("Hello", "There")
end
return ____exports`},
		{name: "console.warn (\"console.warn()\")", tsCode: `export function __main() {console.warn()}`, refLua: `local ____exports = {}
function ____exports.__main(self)
    print()
end
return ____exports`},
		{name: "console.warn (\"console.warn(\\\"Hello\\\")\")", tsCode: `export function __main() {console.warn("Hello")}`, refLua: `local ____exports = {}
function ____exports.__main(self)
    print("Hello")
end
return ____exports`},
		{name: "console.warn (\"console.warn(\\\"Hello %s\\\", \\\"there\\\")\")", tsCode: `export function __main() {console.warn("Hello %s", "there")}`, refLua: `local ____exports = {}
function ____exports.__main(self)
    print(string.format("Hello %s", "there"))
end
return ____exports`},
		{name: "console.warn (\"console.warn(\\\"Hello %%s\\\", \\\"there\\\")\")", tsCode: `export function __main() {console.warn("Hello %%s", "there")}`, refLua: `local ____exports = {}
function ____exports.__main(self)
    print(string.format("Hello %%s", "there"))
end
return ____exports`},
		{name: "console.warn (\"console.warn(\\\"Hello\\\", \\\"There\\\")\")", tsCode: `export function __main() {console.warn("Hello", "There")}`, refLua: `local ____exports = {}
function ____exports.__main(self)
    print("Hello", "There")
end
return ____exports`},
		{name: "console.trace (\"console.trace()\")", tsCode: `export function __main() {console.trace()}`, refLua: `local ____exports = {}
function ____exports.__main(self)
    print(debug.traceback())
end
return ____exports`},
		{name: "console.trace (\"console.trace(\\\"message\\\")\")", tsCode: `export function __main() {console.trace("message")}`, refLua: `local ____exports = {}
function ____exports.__main(self)
    print(debug.traceback("message"))
end
return ____exports`},
		{name: "console.trace (\"console.trace(\\\"Hello %s\\\", \\\"there\\\")\")", tsCode: `export function __main() {console.trace("Hello %s", "there")}`, refLua: `local ____exports = {}
function ____exports.__main(self)
    print(debug.traceback(string.format("Hello %s", "there")))
end
return ____exports`},
		{name: "console.trace (\"console.trace(\\\"Hello %%s\\\", \\\"there\\\")\")", tsCode: `export function __main() {console.trace("Hello %%s", "there")}`, refLua: `local ____exports = {}
function ____exports.__main(self)
    print(debug.traceback(string.format("Hello %%s", "there")))
end
return ____exports`},
		{name: "console.trace (\"console.trace(\\\"Hello\\\", \\\"there\\\")\")", tsCode: `export function __main() {console.trace("Hello", "there")}`, refLua: `local ____exports = {}
function ____exports.__main(self)
    print(debug.traceback("Hello", "there"))
end
return ____exports`},
		{name: "console.assert (\"console.assert(false)\")", tsCode: `export function __main() {console.assert(false)}`, refLua: `local ____exports = {}
function ____exports.__main(self)
    assert(false)
end
return ____exports`},
		{name: "console.assert (\"console.assert(false, \\\"message\\\")\")", tsCode: `export function __main() {console.assert(false, "message")}`, refLua: `local ____exports = {}
function ____exports.__main(self)
    assert(false, "message")
end
return ____exports`},
		{name: "console.assert (\"console.assert(false, \\\"message %s\\\", \\\"info\\\")\")", tsCode: `export function __main() {console.assert(false, "message %s", "info")}`, refLua: `local ____exports = {}
function ____exports.__main(self)
    assert(
        false,
        string.format("message %s", "info")
    )
end
return ____exports`},
		{name: "console.assert (\"console.assert(false, \\\"message %%s\\\", \\\"info\\\")\")", tsCode: `export function __main() {console.assert(false, "message %%s", "info")}`, refLua: `local ____exports = {}
function ____exports.__main(self)
    assert(
        false,
        string.format("message %%s", "info")
    )
end
return ____exports`},
		{name: "console.assert (\"console.assert(false, \\\"message\\\", \\\"more\\\")\")", tsCode: `export function __main() {console.assert(false, "message", "more")}`, refLua: `local ____exports = {}
function ____exports.__main(self)
    assert(false, "message", "more")
end
return ____exports`},
	})
}
