// Code generated by scripts/migrate from extern/tstl/test/unit/enum.spec.ts. DO NOT EDIT.
package tstltest

import "testing"

func TestEval_Enum(t *testing.T) {
	t.Parallel()

	batchExpectFunctions(t, []funcTestCase{
		{"initializers string", `enum TestEnum {
                A = "A",
                B = "B",
            }

            return (() => {
    const mappedTestEnum: any = {};
    for (const key in TestEnum) {
        mappedTestEnum[(key as any).toString()] = (TestEnum as any)[key];
    }
    return mappedTestEnum;
})()`, `{A = "A", B = "B"}`, `local ____exports = {}
function ____exports.__main(self)
    local TestEnum = TestEnum or ({})
    TestEnum.A = "A"
    TestEnum.B = "B"
    return (function()
        local mappedTestEnum = {}
        for key in pairs(TestEnum) do
            mappedTestEnum[tostring(key)] = TestEnum[key]
        end
        return mappedTestEnum
    end)(nil)
end
return ____exports`, false, false},
		{"initializers expression", `const value = 6;
            enum TestEnum {
                A,
                B = value,
            }

            return (() => {
    const mappedTestEnum: any = {};
    for (const key in TestEnum) {
        mappedTestEnum[(key as any).toString()] = (TestEnum as any)[key];
    }
    return mappedTestEnum;
})()`, `{0 = "A", 6 = "B", A = 0, B = 6}`, `local ____exports = {}
function ____exports.__main(self)
    local value = 6
    local TestEnum = TestEnum or ({})
    TestEnum.A = 0
    TestEnum[TestEnum.A] = "A"
    TestEnum.B = 6
    TestEnum[TestEnum.B] = "B"
    return (function()
        local mappedTestEnum = {}
        for key in pairs(TestEnum) do
            mappedTestEnum[tostring(key)] = TestEnum[key]
        end
        return mappedTestEnum
    end)(nil)
end
return ____exports`, false, false},
		{"initializers expression with side effect", `let value = 0;
            enum TestEnum {
                A = value++,
                B = A,
            }

            return (() => {
    const mappedTestEnum: any = {};
    for (const key in TestEnum) {
        mappedTestEnum[(key as any).toString()] = (TestEnum as any)[key];
    }
    return mappedTestEnum;
})()`, `{0 = "B", A = 0, B = 0}`, `local ____exports = {}
function ____exports.__main(self)
    local value = 0
    local ____value_0 = value
    value = ____value_0 + 1
    local TestEnum = TestEnum or ({})
    TestEnum.A = ____value_0
    TestEnum[TestEnum.A] = "A"
    TestEnum.B = TestEnum.A
    TestEnum[TestEnum.B] = "B"
    return (function()
        local mappedTestEnum = {}
        for key in pairs(TestEnum) do
            mappedTestEnum[tostring(key)] = TestEnum[key]
        end
        return mappedTestEnum
    end)(nil)
end
return ____exports`, false, false},
		{"initializers inference", `enum TestEnum {
                A,
                B,
                C,
            }

            return (() => {
    const mappedTestEnum: any = {};
    for (const key in TestEnum) {
        mappedTestEnum[(key as any).toString()] = (TestEnum as any)[key];
    }
    return mappedTestEnum;
})()`, `{0 = "A", 1 = "B", 2 = "C", A = 0, B = 1, C = 2}`, `local ____exports = {}
function ____exports.__main(self)
    local TestEnum = TestEnum or ({})
    TestEnum.A = 0
    TestEnum[TestEnum.A] = "A"
    TestEnum.B = 1
    TestEnum[TestEnum.B] = "B"
    TestEnum.C = 2
    TestEnum[TestEnum.C] = "C"
    return (function()
        local mappedTestEnum = {}
        for key in pairs(TestEnum) do
            mappedTestEnum[tostring(key)] = TestEnum[key]
        end
        return mappedTestEnum
    end)(nil)
end
return ____exports`, false, false},
		{"initializers partial inference", `enum TestEnum {
                A = 3,
                B,
                C = 5,
            }

            return (() => {
    const mappedTestEnum: any = {};
    for (const key in TestEnum) {
        mappedTestEnum[(key as any).toString()] = (TestEnum as any)[key];
    }
    return mappedTestEnum;
})()`, `{3 = "A", 4 = "B", 5 = "C", A = 3, B = 4, C = 5}`, `local ____exports = {}
function ____exports.__main(self)
    local TestEnum = TestEnum or ({})
    TestEnum.A = 3
    TestEnum[TestEnum.A] = "A"
    TestEnum.B = 4
    TestEnum[TestEnum.B] = "B"
    TestEnum.C = 5
    TestEnum[TestEnum.C] = "C"
    return (function()
        local mappedTestEnum = {}
        for key in pairs(TestEnum) do
            mappedTestEnum[tostring(key)] = TestEnum[key]
        end
        return mappedTestEnum
    end)(nil)
end
return ____exports`, false, false},
		{"initializers member reference", `enum TestEnum {
                A,
                B = A,
                C = B,
            }

            return (() => {
    const mappedTestEnum: any = {};
    for (const key in TestEnum) {
        mappedTestEnum[(key as any).toString()] = (TestEnum as any)[key];
    }
    return mappedTestEnum;
})()`, `{0 = "C", A = 0, B = 0, C = 0}`, `local ____exports = {}
function ____exports.__main(self)
    local TestEnum = TestEnum or ({})
    TestEnum.A = 0
    TestEnum[TestEnum.A] = "A"
    TestEnum.B = 0
    TestEnum[TestEnum.B] = "B"
    TestEnum.C = 0
    TestEnum[TestEnum.C] = "C"
    return (function()
        local mappedTestEnum = {}
        for key in pairs(TestEnum) do
            mappedTestEnum[tostring(key)] = TestEnum[key]
        end
        return mappedTestEnum
    end)(nil)
end
return ____exports`, false, false},
		{"initializers string literal member reference", `enum TestEnum {
                ["A"],
                "B" = A,
                C = B,
            }

            return (() => {
    const mappedTestEnum: any = {};
    for (const key in TestEnum) {
        mappedTestEnum[(key as any).toString()] = (TestEnum as any)[key];
    }
    return mappedTestEnum;
})()`, `{0 = "C", A = 0, B = 0, C = 0}`, `local ____exports = {}
function ____exports.__main(self)
    local TestEnum = TestEnum or ({})
    TestEnum.A = 0
    TestEnum[TestEnum.A] = "A"
    TestEnum.B = 0
    TestEnum[TestEnum.B] = "B"
    TestEnum.C = 0
    TestEnum[TestEnum.C] = "C"
    return (function()
        local mappedTestEnum = {}
        for key in pairs(TestEnum) do
            mappedTestEnum[tostring(key)] = TestEnum[key]
        end
        return mappedTestEnum
    end)(nil)
end
return ____exports`, false, false},
		{"const enum with string initializer", `const enum TestEnum {
                A = "ONE",
                B = "TWO",
            }

            return TestEnum.A;`, `"ONE"`, `local ____exports = {}
function ____exports.__main(self)
    return "ONE"
end
return ____exports`, false, false},
		{"const enum access with string literal", `const enum TestEnum {
                A,
                B,
                C,
            }

            return TestEnum["C"];`, `2`, `local ____exports = {}
function ____exports.__main(self)
    return 2
end
return ____exports`, false, false},
		{"toString", `enum TestEnum {
            A,
            B,
            C,
        }

        function foo(value: TestEnum) {
            return value.toString();
        }

        return foo(TestEnum.A);`, `"0"`, `local ____exports = {}
function ____exports.__main(self)
    local TestEnum = TestEnum or ({})
    TestEnum.A = 0
    TestEnum[TestEnum.A] = "A"
    TestEnum.B = 1
    TestEnum[TestEnum.B] = "B"
    TestEnum.C = 2
    TestEnum[TestEnum.C] = "C"
    local function foo(self, value)
        return tostring(value)
    end
    return foo(nil, TestEnum.A)
end
return ____exports`, false, false},
		{"enum merging", `enum TestEnum {
            A, B
        }

        enum TestEnum {
            C = 3,
            D
        }

        return (() => {
    const mappedTestEnum: any = {};
    for (const key in TestEnum) {
        mappedTestEnum[(key as any).toString()] = (TestEnum as any)[key];
    }
    return mappedTestEnum;
})()`, `{0 = "A", 1 = "B", 3 = "C", 4 = "D", A = 0, B = 1, C = 3, D = 4}`, `local ____exports = {}
function ____exports.__main(self)
    local TestEnum = TestEnum or ({})
    TestEnum.A = 0
    TestEnum[TestEnum.A] = "A"
    TestEnum.B = 1
    TestEnum[TestEnum.B] = "B"
    TestEnum.C = 3
    TestEnum[TestEnum.C] = "C"
    TestEnum.D = 4
    TestEnum[TestEnum.D] = "D"
    return (function()
        local mappedTestEnum = {}
        for key in pairs(TestEnum) do
            mappedTestEnum[tostring(key)] = TestEnum[key]
        end
        return mappedTestEnum
    end)(nil)
end
return ____exports`, false, false},
		{"enum merging with overlap", `enum TestEnum {
            A, B
        }

        enum TestEnum {
            C = 1,
            D
        }

        return (() => {
    const mappedTestEnum: any = {};
    for (const key in TestEnum) {
        mappedTestEnum[(key as any).toString()] = (TestEnum as any)[key];
    }
    return mappedTestEnum;
})()`, `{0 = "A", 1 = "C", 2 = "D", A = 0, B = 1, C = 1, D = 2}`, `local ____exports = {}
function ____exports.__main(self)
    local TestEnum = TestEnum or ({})
    TestEnum.A = 0
    TestEnum[TestEnum.A] = "A"
    TestEnum.B = 1
    TestEnum[TestEnum.B] = "B"
    TestEnum.C = 1
    TestEnum[TestEnum.C] = "C"
    TestEnum.D = 2
    TestEnum[TestEnum.D] = "D"
    return (function()
        local mappedTestEnum = {}
        for key in pairs(TestEnum) do
            mappedTestEnum[tostring(key)] = TestEnum[key]
        end
        return mappedTestEnum
    end)(nil)
end
return ____exports`, false, false},
	})

	batchExpectModules(t, []moduleTestCase{
		{"const enum without initializer", `const enum TestEnum {
                A,
                B,
            }

            export const A = TestEnum.A;`, `{A = 0}`, `local ____exports = {}
____exports.A = 0
return ____exports`, false, false},
		{"const enum declare without initializer", `declare  const enum TestEnum {
                A,
                B,
            }

            export const A = TestEnum.A;`, `{A = 0}`, `local ____exports = {}
____exports.A = 0
return ____exports`, false, false},
	})

	batchRunTests(t, []batchTestCase{
		{name: "enum merging multiple files", tsCode: `import "./otherfile"
        enum TestEnum {
            A, B
        }

        export default (() => {
    const mappedTestEnum: any = {};
    for (const key in TestEnum) {
        mappedTestEnum[(key as any).toString()] = (TestEnum as any)[key];
    }
    return mappedTestEnum;
})()`, accessor: `mod`, want: `{default = {0 = "A", 1 = "B", 3 = "C", 4 = "D", A = 0, B = 1, C = 3, D = 4}}`, refLua: `local ____exports = {}
require("otherfile")
local TestEnum = TestEnum or ({})
TestEnum.A = 0
TestEnum[TestEnum.A] = "A"
TestEnum.B = 1
TestEnum[TestEnum.B] = "B"
____exports.default = (function()
    local mappedTestEnum = {}
    for key in pairs(TestEnum) do
        mappedTestEnum[tostring(key)] = TestEnum[key]
    end
    return mappedTestEnum
end)(nil)
return ____exports`, extraFiles: map[string]string{"otherfile.ts": `enum TestEnum {
                C = 3,
                D
            }`}},
	})

	batchExpectCodegen(t, []codegenTestCase{
		{"const enum without initializer", "module", `const enum TestEnum {
                A,
                B,
            }

            export const A = TestEnum.A;`, nil, []string{`TestEnum`}, nil, nil},
		{"const enum declare without initializer", "module", `declare  const enum TestEnum {
                A,
                B,
            }

            export const A = TestEnum.A;`, nil, []string{`TestEnum`}, nil, nil},
		{"const enum with string initializer", "function", `const enum TestEnum {
                A = "ONE",
                B = "TWO",
            }

            return TestEnum.A;`, nil, []string{`TestEnum`}, nil, nil},
		{"const enum access with string literal", "function", `const enum TestEnum {
                A,
                B,
                C,
            }

            return TestEnum["C"];`, nil, []string{`TestEnum`}, nil, nil},
	})

	batchCompareCodegen(t, []batchTestCase{
		{name: "enum nested in namespace", tsCode: `namespace A {
            export enum TestEnum {
                B,
                C
            }
        }`, refLua: `A = A or ({})
do
    A.TestEnum = A.TestEnum or ({})
    A.TestEnum.B = 0
    A.TestEnum[A.TestEnum.B] = "B"
    A.TestEnum.C = 1
    A.TestEnum[A.TestEnum.C] = "C"
end`, tstlBug: `tslua-improvement: same-file namespace enum uses plain {} init`},
	})
}
