// Code generated by scripts/migrate from extern/tstl/test/unit/file.spec.ts. DO NOT EDIT.
package tstltest

import "testing"

func TestEval_File(t *testing.T) {
	t.Parallel()

	batchRunTests(t, []batchTestCase{
		{name: "JSON JSON (0)", tsCode: `0`, accessor: `mod`, want: `0`, refLua: `local ____ = 0`, entryPoint: "main.json"},
		{name: "JSON JSON (\"\")", tsCode: `""`, accessor: `mod`, want: `""`, refLua: `local ____ = ""`, entryPoint: "main.json"},
		{name: "JSON JSON ([])", tsCode: `[]`, accessor: `mod`, want: `{}`, refLua: `local ____ = {}`, entryPoint: "main.json"},
		{name: "JSON JSON ([1,\"2\",[]])", tsCode: `[1,"2",[]]`, accessor: `mod`, want: `{1, "2", {}}`, refLua: `local ____ = {1, "2", {}}`, entryPoint: "main.json"},
		{name: "JSON JSON ({\"a\":\"b\"})", tsCode: `{"a":"b"}`, accessor: `mod`, want: `{a = "b"}`, refLua: `do
    local ____ = "a"
    local ____ = "b"
end`, entryPoint: "main.json"},
		{name: "JSON JSON ({\"a\":{\"b\":\"c\"}})", tsCode: `{"a":{"b":"c"}}`, accessor: `mod`, want: `{a = {b = "c"}}`, refLua: `do
    local ____ = "a"
    do
        local ____ = "b"
        local ____ = "c"
    end
end`, entryPoint: "main.json"},
		{name: "JSON empty file throws runtime error", tsCode: ``, accessor: `mod`, want: `{message = "Unexpected end of JSON input", name = "ExecutionError"}`, refLua: ``, entryPoint: "main.json"},
		{name: "JSON JSON modules can be imported", tsCode: `import * as jsonData from "./jsonModule.json";
            export const result = jsonData;`, accessor: `mod`, want: `{result = {jsonField1 = "hello, this is JSON", jsonField2 = {"a", "b", "c"}}}`, refLua: `local ____exports = {}
local jsonData = require("jsonModule")
____exports.result = jsonData
return ____exports`, extraFiles: map[string]string{"jsonModule.json": `{ "jsonField1": "hello, this is JSON", "jsonField2": ["a", "b", "c"] }`}},
	}, WithOptions(map[string]any{"resolveJsonModule": true}))

	batchCompareCodegen(t, []batchTestCase{
		{name: "shebang LF", tsCode: `#!/usr/bin/env lua

            const foo = true;`, refLua: `#!/usr/bin/env lua
foo = true`},
		{name: "shebang CRLF", tsCode: `#!/usr/bin/env lua

            const foo = true;`, refLua: `#!/usr/bin/env lua
foo = true`},
	})
}
