// Code generated by scripts/migrate from extern/tstl/test/unit/functions/validation/functionExpressionTypeInference.spec.ts. DO NOT EDIT.
package tstltest

import "testing"

func TestEval_FunctionExpressionTypeInference(t *testing.T) {
	t.Parallel()

	batchExpectFunctions(t, []funcTestCase{
		{"Function expression type inference in class (\"s => s\")", `class Foo {
                func: (this: void, s: string) => string = s => s;
                method: (s: string) => string = s => s;
                static staticFunc: (this: void, s: string) => string = s => s;
                static staticMethod: (s: string) => string = s => s;
            }
            const foo = new Foo();
            return foo.func("a") + foo.method("b") + Foo.staticFunc("c") + Foo.staticMethod("d");`, `"abcd"`, `local ____lualib = require("lualib_bundle")
local __TS__Class = ____lualib.__TS__Class
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local Foo = __TS__Class()
    Foo.name = "Foo"
    function Foo.prototype.____constructor(self)
        self.func = function(s) return s end
        self.method = function(____, s) return s end
    end
    Foo.staticFunc = function(s) return s end
    Foo.staticMethod = function(____, s) return s end
    local foo = __TS__New(Foo)
    return ((foo.func("a") .. foo:method("b")) .. Foo.staticFunc("c")) .. Foo:staticMethod("d")
end
return ____exports`, false, false},
		{"Function expression type inference in class (\"(s => s)\")", `class Foo {
                func: (this: void, s: string) => string = (s => s);
                method: (s: string) => string = (s => s);
                static staticFunc: (this: void, s: string) => string = (s => s);
                static staticMethod: (s: string) => string = (s => s);
            }
            const foo = new Foo();
            return foo.func("a") + foo.method("b") + Foo.staticFunc("c") + Foo.staticMethod("d");`, `"abcd"`, `local ____lualib = require("lualib_bundle")
local __TS__Class = ____lualib.__TS__Class
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local Foo = __TS__Class()
    Foo.name = "Foo"
    function Foo.prototype.____constructor(self)
        self.func = function(s) return s end
        self.method = function(____, s) return s end
    end
    Foo.staticFunc = function(s) return s end
    Foo.staticMethod = function(____, s) return s end
    local foo = __TS__New(Foo)
    return ((foo.func("a") .. foo:method("b")) .. Foo.staticFunc("c")) .. Foo:staticMethod("d")
end
return ____exports`, false, false},
		{"Function expression type inference in class (\"function(s) { return s; }\")", `class Foo {
                func: (this: void, s: string) => string = function(s) { return s; };
                method: (s: string) => string = function(s) { return s; };
                static staticFunc: (this: void, s: string) => string = function(s) { return s; };
                static staticMethod: (s: string) => string = function(s) { return s; };
            }
            const foo = new Foo();
            return foo.func("a") + foo.method("b") + Foo.staticFunc("c") + Foo.staticMethod("d");`, `"abcd"`, `local ____lualib = require("lualib_bundle")
local __TS__Class = ____lualib.__TS__Class
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local Foo = __TS__Class()
    Foo.name = "Foo"
    function Foo.prototype.____constructor(self)
        self.func = function(s)
            return s
        end
        self.method = function(self, s)
            return s
        end
    end
    Foo.staticFunc = function(s)
        return s
    end
    Foo.staticMethod = function(self, s)
        return s
    end
    local foo = __TS__New(Foo)
    return ((foo.func("a") .. foo:method("b")) .. Foo.staticFunc("c")) .. Foo:staticMethod("d")
end
return ____exports`, false, false},
		{"Function expression type inference in class (\"(function(s) { return s; })\")", `class Foo {
                func: (this: void, s: string) => string = (function(s) { return s; });
                method: (s: string) => string = (function(s) { return s; });
                static staticFunc: (this: void, s: string) => string = (function(s) { return s; });
                static staticMethod: (s: string) => string = (function(s) { return s; });
            }
            const foo = new Foo();
            return foo.func("a") + foo.method("b") + Foo.staticFunc("c") + Foo.staticMethod("d");`, `"abcd"`, `local ____lualib = require("lualib_bundle")
local __TS__Class = ____lualib.__TS__Class
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local Foo = __TS__Class()
    Foo.name = "Foo"
    function Foo.prototype.____constructor(self)
        self.func = function(s)
            return s
        end
        self.method = function(self, s)
            return s
        end
    end
    Foo.staticFunc = function(s)
        return s
    end
    Foo.staticMethod = function(self, s)
        return s
    end
    local foo = __TS__New(Foo)
    return ((foo.func("a") .. foo:method("b")) .. Foo.staticFunc("c")) .. Foo:staticMethod("d")
end
return ____exports`, false, false},
		{"Function expression type inference in object literal ({\"assignTo\":\"const foo: Foo\",\"funcExp\":\"s => s\"})", `interface Foo {
            func(this: void, s: string): string;
            method(this: this, s: string): string;
        }
        const foo: Foo = {func: s => s, method: s => s};
        return foo.method("foo") + foo.func("bar");`, `"foobar"`, `local ____exports = {}
function ____exports.__main(self)
    local foo = {
        func = function(s) return s end,
        method = function(____, s) return s end
    }
    return foo:method("foo") .. foo.func("bar")
end
return ____exports`, false, false},
		{"Function expression type inference in object literal ({\"assignTo\":\"const foo: Foo\",\"funcExp\":\"(s => s)\"})", `interface Foo {
            func(this: void, s: string): string;
            method(this: this, s: string): string;
        }
        const foo: Foo = {func: (s => s), method: (s => s)};
        return foo.method("foo") + foo.func("bar");`, `"foobar"`, `local ____exports = {}
function ____exports.__main(self)
    local foo = {
        func = function(s) return s end,
        method = function(____, s) return s end
    }
    return foo:method("foo") .. foo.func("bar")
end
return ____exports`, false, false},
		{"Function expression type inference in object literal ({\"assignTo\":\"const foo: Foo\",\"funcExp\":\"function(s) { return s; }\"})", `interface Foo {
            func(this: void, s: string): string;
            method(this: this, s: string): string;
        }
        const foo: Foo = {func: function(s) { return s; }, method: function(s) { return s; }};
        return foo.method("foo") + foo.func("bar");`, `"foobar"`, `local ____exports = {}
function ____exports.__main(self)
    local foo = {
        func = function(s)
            return s
        end,
        method = function(self, s)
            return s
        end
    }
    return foo:method("foo") .. foo.func("bar")
end
return ____exports`, false, false},
		{"Function expression type inference in object literal ({\"assignTo\":\"const foo: Foo\",\"funcExp\":\"(function(s) { return s; })\"})", `interface Foo {
            func(this: void, s: string): string;
            method(this: this, s: string): string;
        }
        const foo: Foo = {func: (function(s) { return s; }), method: (function(s) { return s; })};
        return foo.method("foo") + foo.func("bar");`, `"foobar"`, `local ____exports = {}
function ____exports.__main(self)
    local foo = {
        func = function(s)
            return s
        end,
        method = function(self, s)
            return s
        end
    }
    return foo:method("foo") .. foo.func("bar")
end
return ____exports`, false, false},
		{"Function expression type inference in object literal ({\"assignTo\":\"let foo: Foo; foo\",\"funcExp\":\"s => s\"})", `interface Foo {
            func(this: void, s: string): string;
            method(this: this, s: string): string;
        }
        let foo: Foo; foo = {func: s => s, method: s => s};
        return foo.method("foo") + foo.func("bar");`, `"foobar"`, `local ____exports = {}
function ____exports.__main(self)
    local foo
    foo = {
        func = function(s) return s end,
        method = function(____, s) return s end
    }
    return foo:method("foo") .. foo.func("bar")
end
return ____exports`, false, false},
		{"Function expression type inference in object literal ({\"assignTo\":\"let foo: Foo; foo\",\"funcExp\":\"(s => s)\"})", `interface Foo {
            func(this: void, s: string): string;
            method(this: this, s: string): string;
        }
        let foo: Foo; foo = {func: (s => s), method: (s => s)};
        return foo.method("foo") + foo.func("bar");`, `"foobar"`, `local ____exports = {}
function ____exports.__main(self)
    local foo
    foo = {
        func = function(s) return s end,
        method = function(____, s) return s end
    }
    return foo:method("foo") .. foo.func("bar")
end
return ____exports`, false, false},
		{"Function expression type inference in object literal ({\"assignTo\":\"let foo: Foo; foo\",\"funcExp\":\"function(s) { return s; }\"})", `interface Foo {
            func(this: void, s: string): string;
            method(this: this, s: string): string;
        }
        let foo: Foo; foo = {func: function(s) { return s; }, method: function(s) { return s; }};
        return foo.method("foo") + foo.func("bar");`, `"foobar"`, `local ____exports = {}
function ____exports.__main(self)
    local foo
    foo = {
        func = function(s)
            return s
        end,
        method = function(self, s)
            return s
        end
    }
    return foo:method("foo") .. foo.func("bar")
end
return ____exports`, false, false},
		{"Function expression type inference in object literal ({\"assignTo\":\"let foo: Foo; foo\",\"funcExp\":\"(function(s) { return s; })\"})", `interface Foo {
            func(this: void, s: string): string;
            method(this: this, s: string): string;
        }
        let foo: Foo; foo = {func: (function(s) { return s; }), method: (function(s) { return s; })};
        return foo.method("foo") + foo.func("bar");`, `"foobar"`, `local ____exports = {}
function ____exports.__main(self)
    local foo
    foo = {
        func = function(s)
            return s
        end,
        method = function(self, s)
            return s
        end
    }
    return foo:method("foo") .. foo.func("bar")
end
return ____exports`, false, false},
		{"Function expression type inference in object literal assigned to narrower type", `let foo: {} = {bar: (s: string) => s};
        return (foo as {bar: (a: any) => any}).bar("foobar");`, `"foobar"`, `local ____exports = {}
function ____exports.__main(self)
    local foo = {bar = function(____, s) return s end}
    return foo:bar("foobar")
end
return ____exports`, false, false},
		{"Function expression type inference in object literal (generic key) ({\"assignTo\":\"const foo: Foo\",\"funcExp\":\"s => s\"})", `interface Foo {
            [f: string]: (this: void, s: string) => string;
        }
        const foo: Foo = {func: s => s};
        return foo.func("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local foo = {func = function(s) return s end}
    return foo.func("foo")
end
return ____exports`, false, false},
		{"Function expression type inference in object literal (generic key) ({\"assignTo\":\"const foo: Foo\",\"funcExp\":\"(s => s)\"})", `interface Foo {
            [f: string]: (this: void, s: string) => string;
        }
        const foo: Foo = {func: (s => s)};
        return foo.func("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local foo = {func = function(s) return s end}
    return foo.func("foo")
end
return ____exports`, false, false},
		{"Function expression type inference in object literal (generic key) ({\"assignTo\":\"const foo: Foo\",\"funcExp\":\"function(s) { return s; }\"})", `interface Foo {
            [f: string]: (this: void, s: string) => string;
        }
        const foo: Foo = {func: function(s) { return s; }};
        return foo.func("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local foo = {func = function(s)
        return s
    end}
    return foo.func("foo")
end
return ____exports`, false, false},
		{"Function expression type inference in object literal (generic key) ({\"assignTo\":\"const foo: Foo\",\"funcExp\":\"(function(s) { return s; })\"})", `interface Foo {
            [f: string]: (this: void, s: string) => string;
        }
        const foo: Foo = {func: (function(s) { return s; })};
        return foo.func("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local foo = {func = function(s)
        return s
    end}
    return foo.func("foo")
end
return ____exports`, false, false},
		{"Function expression type inference in object literal (generic key) ({\"assignTo\":\"let foo: Foo; foo\",\"funcExp\":\"s => s\"})", `interface Foo {
            [f: string]: (this: void, s: string) => string;
        }
        let foo: Foo; foo = {func: s => s};
        return foo.func("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local foo
    foo = {func = function(s) return s end}
    return foo.func("foo")
end
return ____exports`, false, false},
		{"Function expression type inference in object literal (generic key) ({\"assignTo\":\"let foo: Foo; foo\",\"funcExp\":\"(s => s)\"})", `interface Foo {
            [f: string]: (this: void, s: string) => string;
        }
        let foo: Foo; foo = {func: (s => s)};
        return foo.func("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local foo
    foo = {func = function(s) return s end}
    return foo.func("foo")
end
return ____exports`, false, false},
		{"Function expression type inference in object literal (generic key) ({\"assignTo\":\"let foo: Foo; foo\",\"funcExp\":\"function(s) { return s; }\"})", `interface Foo {
            [f: string]: (this: void, s: string) => string;
        }
        let foo: Foo; foo = {func: function(s) { return s; }};
        return foo.func("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local foo
    foo = {func = function(s)
        return s
    end}
    return foo.func("foo")
end
return ____exports`, false, false},
		{"Function expression type inference in object literal (generic key) ({\"assignTo\":\"let foo: Foo; foo\",\"funcExp\":\"(function(s) { return s; })\"})", `interface Foo {
            [f: string]: (this: void, s: string) => string;
        }
        let foo: Foo; foo = {func: (function(s) { return s; })};
        return foo.func("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local foo
    foo = {func = function(s)
        return s
    end}
    return foo.func("foo")
end
return ____exports`, false, false},
		{"Function expression type inference in tuple ({\"assignTo\":\"const funcs: [Func, Method]\",\"func\":\"funcs[0]\",\"method\":\"funcs[1]\",\"funcExp\":\"s => s\"})", `interface Foo {
            method(s: string): string;
        }
        interface Func {
            (this: void, s: string): string;
        }
        interface Method {
            (this: Foo, s: string): string;
        }
        const funcs: [Func, Method] = [s => s, s => s];
        const foo: Foo = {method: funcs[1]};
        return foo.method("foo") + funcs[0]("bar");`, `"foobar"`, `local ____exports = {}
function ____exports.__main(self)
    local funcs = {
        function(s) return s end,
        function(____, s) return s end
    }
    local foo = {method = funcs[2]}
    return foo:method("foo") .. funcs[1]("bar")
end
return ____exports`, false, false},
		{"Function expression type inference in tuple ({\"assignTo\":\"const funcs: [Func, Method]\",\"func\":\"funcs[0]\",\"method\":\"funcs[1]\",\"funcExp\":\"(s => s)\"})", `interface Foo {
            method(s: string): string;
        }
        interface Func {
            (this: void, s: string): string;
        }
        interface Method {
            (this: Foo, s: string): string;
        }
        const funcs: [Func, Method] = [(s => s), (s => s)];
        const foo: Foo = {method: funcs[1]};
        return foo.method("foo") + funcs[0]("bar");`, `"foobar"`, `local ____exports = {}
function ____exports.__main(self)
    local funcs = {
        function(s) return s end,
        function(____, s) return s end
    }
    local foo = {method = funcs[2]}
    return foo:method("foo") .. funcs[1]("bar")
end
return ____exports`, false, false},
		{"Function expression type inference in tuple ({\"assignTo\":\"const funcs: [Func, Method]\",\"func\":\"funcs[0]\",\"method\":\"funcs[1]\",\"funcExp\":\"function(s) { return s; }\"})", `interface Foo {
            method(s: string): string;
        }
        interface Func {
            (this: void, s: string): string;
        }
        interface Method {
            (this: Foo, s: string): string;
        }
        const funcs: [Func, Method] = [function(s) { return s; }, function(s) { return s; }];
        const foo: Foo = {method: funcs[1]};
        return foo.method("foo") + funcs[0]("bar");`, `"foobar"`, `local ____exports = {}
function ____exports.__main(self)
    local funcs = {
        function(s)
            return s
        end,
        function(self, s)
            return s
        end
    }
    local foo = {method = funcs[2]}
    return foo:method("foo") .. funcs[1]("bar")
end
return ____exports`, false, false},
		{"Function expression type inference in tuple ({\"assignTo\":\"const funcs: [Func, Method]\",\"func\":\"funcs[0]\",\"method\":\"funcs[1]\",\"funcExp\":\"(function(s) { return s; })\"})", `interface Foo {
            method(s: string): string;
        }
        interface Func {
            (this: void, s: string): string;
        }
        interface Method {
            (this: Foo, s: string): string;
        }
        const funcs: [Func, Method] = [(function(s) { return s; }), (function(s) { return s; })];
        const foo: Foo = {method: funcs[1]};
        return foo.method("foo") + funcs[0]("bar");`, `"foobar"`, `local ____exports = {}
function ____exports.__main(self)
    local funcs = {
        function(s)
            return s
        end,
        function(self, s)
            return s
        end
    }
    local foo = {method = funcs[2]}
    return foo:method("foo") .. funcs[1]("bar")
end
return ____exports`, false, false},
		{"Function expression type inference in tuple ({\"assignTo\":\"let funcs: [Func, Method]; funcs\",\"func\":\"funcs[0]\",\"method\":\"funcs[1]\",\"funcExp\":\"s => s\"})", `interface Foo {
            method(s: string): string;
        }
        interface Func {
            (this: void, s: string): string;
        }
        interface Method {
            (this: Foo, s: string): string;
        }
        let funcs: [Func, Method]; funcs = [s => s, s => s];
        const foo: Foo = {method: funcs[1]};
        return foo.method("foo") + funcs[0]("bar");`, `"foobar"`, `local ____exports = {}
function ____exports.__main(self)
    local funcs
    funcs = {
        function(s) return s end,
        function(____, s) return s end
    }
    local foo = {method = funcs[2]}
    return foo:method("foo") .. funcs[1]("bar")
end
return ____exports`, false, false},
		{"Function expression type inference in tuple ({\"assignTo\":\"let funcs: [Func, Method]; funcs\",\"func\":\"funcs[0]\",\"method\":\"funcs[1]\",\"funcExp\":\"(s => s)\"})", `interface Foo {
            method(s: string): string;
        }
        interface Func {
            (this: void, s: string): string;
        }
        interface Method {
            (this: Foo, s: string): string;
        }
        let funcs: [Func, Method]; funcs = [(s => s), (s => s)];
        const foo: Foo = {method: funcs[1]};
        return foo.method("foo") + funcs[0]("bar");`, `"foobar"`, `local ____exports = {}
function ____exports.__main(self)
    local funcs
    funcs = {
        function(s) return s end,
        function(____, s) return s end
    }
    local foo = {method = funcs[2]}
    return foo:method("foo") .. funcs[1]("bar")
end
return ____exports`, false, false},
		{"Function expression type inference in tuple ({\"assignTo\":\"let funcs: [Func, Method]; funcs\",\"func\":\"funcs[0]\",\"method\":\"funcs[1]\",\"funcExp\":\"function(s) { return s; }\"})", `interface Foo {
            method(s: string): string;
        }
        interface Func {
            (this: void, s: string): string;
        }
        interface Method {
            (this: Foo, s: string): string;
        }
        let funcs: [Func, Method]; funcs = [function(s) { return s; }, function(s) { return s; }];
        const foo: Foo = {method: funcs[1]};
        return foo.method("foo") + funcs[0]("bar");`, `"foobar"`, `local ____exports = {}
function ____exports.__main(self)
    local funcs
    funcs = {
        function(s)
            return s
        end,
        function(self, s)
            return s
        end
    }
    local foo = {method = funcs[2]}
    return foo:method("foo") .. funcs[1]("bar")
end
return ____exports`, false, false},
		{"Function expression type inference in tuple ({\"assignTo\":\"let funcs: [Func, Method]; funcs\",\"func\":\"funcs[0]\",\"method\":\"funcs[1]\",\"funcExp\":\"(function(s) { return s; })\"})", `interface Foo {
            method(s: string): string;
        }
        interface Func {
            (this: void, s: string): string;
        }
        interface Method {
            (this: Foo, s: string): string;
        }
        let funcs: [Func, Method]; funcs = [(function(s) { return s; }), (function(s) { return s; })];
        const foo: Foo = {method: funcs[1]};
        return foo.method("foo") + funcs[0]("bar");`, `"foobar"`, `local ____exports = {}
function ____exports.__main(self)
    local funcs
    funcs = {
        function(s)
            return s
        end,
        function(self, s)
            return s
        end
    }
    local foo = {method = funcs[2]}
    return foo:method("foo") .. funcs[1]("bar")
end
return ____exports`, false, false},
		{"Function expression type inference in tuple ({\"assignTo\":\"const [func, meth]: [Func, Method]\",\"func\":\"func\",\"method\":\"meth\",\"funcExp\":\"s => s\"})", `interface Foo {
            method(s: string): string;
        }
        interface Func {
            (this: void, s: string): string;
        }
        interface Method {
            (this: Foo, s: string): string;
        }
        const [func, meth]: [Func, Method] = [s => s, s => s];
        const foo: Foo = {method: meth};
        return foo.method("foo") + func("bar");`, `"foobar"`, `local ____exports = {}
function ____exports.__main(self)
    local func, meth = function(s) return s end, function(____, s) return s end
    local foo = {method = meth}
    return foo:method("foo") .. func("bar")
end
return ____exports`, false, false},
		{"Function expression type inference in tuple ({\"assignTo\":\"const [func, meth]: [Func, Method]\",\"func\":\"func\",\"method\":\"meth\",\"funcExp\":\"(s => s)\"})", `interface Foo {
            method(s: string): string;
        }
        interface Func {
            (this: void, s: string): string;
        }
        interface Method {
            (this: Foo, s: string): string;
        }
        const [func, meth]: [Func, Method] = [(s => s), (s => s)];
        const foo: Foo = {method: meth};
        return foo.method("foo") + func("bar");`, `"foobar"`, `local ____exports = {}
function ____exports.__main(self)
    local func, meth = function(s) return s end, function(____, s) return s end
    local foo = {method = meth}
    return foo:method("foo") .. func("bar")
end
return ____exports`, false, false},
		{"Function expression type inference in tuple ({\"assignTo\":\"const [func, meth]: [Func, Method]\",\"func\":\"func\",\"method\":\"meth\",\"funcExp\":\"function(s) { return s; }\"})", `interface Foo {
            method(s: string): string;
        }
        interface Func {
            (this: void, s: string): string;
        }
        interface Method {
            (this: Foo, s: string): string;
        }
        const [func, meth]: [Func, Method] = [function(s) { return s; }, function(s) { return s; }];
        const foo: Foo = {method: meth};
        return foo.method("foo") + func("bar");`, `"foobar"`, `local ____exports = {}
function ____exports.__main(self)
    local func, meth = function(s)
        return s
    end, function(self, s)
        return s
    end
    local foo = {method = meth}
    return foo:method("foo") .. func("bar")
end
return ____exports`, false, false},
		{"Function expression type inference in tuple ({\"assignTo\":\"const [func, meth]: [Func, Method]\",\"func\":\"func\",\"method\":\"meth\",\"funcExp\":\"(function(s) { return s; })\"})", `interface Foo {
            method(s: string): string;
        }
        interface Func {
            (this: void, s: string): string;
        }
        interface Method {
            (this: Foo, s: string): string;
        }
        const [func, meth]: [Func, Method] = [(function(s) { return s; }), (function(s) { return s; })];
        const foo: Foo = {method: meth};
        return foo.method("foo") + func("bar");`, `"foobar"`, `local ____exports = {}
function ____exports.__main(self)
    local func, meth = function(s)
        return s
    end, function(self, s)
        return s
    end
    local foo = {method = meth}
    return foo:method("foo") .. func("bar")
end
return ____exports`, false, false},
		{"Function expression type inference in tuple ({\"assignTo\":\"let func: Func; let meth: Method; [func, meth]\",\"func\":\"func\",\"method\":\"meth\",\"funcExp\":\"s => s\"})", `interface Foo {
            method(s: string): string;
        }
        interface Func {
            (this: void, s: string): string;
        }
        interface Method {
            (this: Foo, s: string): string;
        }
        let func: Func; let meth: Method; [func, meth] = [s => s, s => s];
        const foo: Foo = {method: meth};
        return foo.method("foo") + func("bar");`, `"foobar"`, `local ____exports = {}
function ____exports.__main(self)
    local func
    local meth
    func, meth = function(s) return s end, function(____, s) return s end
    local foo = {method = meth}
    return foo:method("foo") .. func("bar")
end
return ____exports`, false, false},
		{"Function expression type inference in tuple ({\"assignTo\":\"let func: Func; let meth: Method; [func, meth]\",\"func\":\"func\",\"method\":\"meth\",\"funcExp\":\"(s => s)\"})", `interface Foo {
            method(s: string): string;
        }
        interface Func {
            (this: void, s: string): string;
        }
        interface Method {
            (this: Foo, s: string): string;
        }
        let func: Func; let meth: Method; [func, meth] = [(s => s), (s => s)];
        const foo: Foo = {method: meth};
        return foo.method("foo") + func("bar");`, `"foobar"`, `local ____exports = {}
function ____exports.__main(self)
    local func
    local meth
    func, meth = function(s) return s end, function(____, s) return s end
    local foo = {method = meth}
    return foo:method("foo") .. func("bar")
end
return ____exports`, false, false},
		{"Function expression type inference in tuple ({\"assignTo\":\"let func: Func; let meth: Method; [func, meth]\",\"func\":\"func\",\"method\":\"meth\",\"funcExp\":\"function(s) { return s; }\"})", `interface Foo {
            method(s: string): string;
        }
        interface Func {
            (this: void, s: string): string;
        }
        interface Method {
            (this: Foo, s: string): string;
        }
        let func: Func; let meth: Method; [func, meth] = [function(s) { return s; }, function(s) { return s; }];
        const foo: Foo = {method: meth};
        return foo.method("foo") + func("bar");`, `"foobar"`, `local ____exports = {}
function ____exports.__main(self)
    local func
    local meth
    func, meth = function(s)
        return s
    end, function(self, s)
        return s
    end
    local foo = {method = meth}
    return foo:method("foo") .. func("bar")
end
return ____exports`, false, false},
		{"Function expression type inference in tuple ({\"assignTo\":\"let func: Func; let meth: Method; [func, meth]\",\"func\":\"func\",\"method\":\"meth\",\"funcExp\":\"(function(s) { return s; })\"})", `interface Foo {
            method(s: string): string;
        }
        interface Func {
            (this: void, s: string): string;
        }
        interface Method {
            (this: Foo, s: string): string;
        }
        let func: Func; let meth: Method; [func, meth] = [(function(s) { return s; }), (function(s) { return s; })];
        const foo: Foo = {method: meth};
        return foo.method("foo") + func("bar");`, `"foobar"`, `local ____exports = {}
function ____exports.__main(self)
    local func
    local meth
    func, meth = function(s)
        return s
    end, function(self, s)
        return s
    end
    local foo = {method = meth}
    return foo:method("foo") .. func("bar")
end
return ____exports`, false, false},
		{"Function expression type inference in array ({\"assignTo\":\"const meths: Method[]\",\"method\":\"meths[0]\",\"funcExp\":\"s => s\"})", `interface Foo {
            method(s: string): string;
        }
        interface Method {
            (this: Foo, s: string): string;
        }
        const meths: Method[] = [s => s];
        const foo: Foo = {method: meths[0]};
        return foo.method("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local meths = {function(____, s) return s end}
    local foo = {method = meths[1]}
    return foo:method("foo")
end
return ____exports`, false, false},
		{"Function expression type inference in array ({\"assignTo\":\"const meths: Method[]\",\"method\":\"meths[0]\",\"funcExp\":\"(s => s)\"})", `interface Foo {
            method(s: string): string;
        }
        interface Method {
            (this: Foo, s: string): string;
        }
        const meths: Method[] = [(s => s)];
        const foo: Foo = {method: meths[0]};
        return foo.method("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local meths = {function(____, s) return s end}
    local foo = {method = meths[1]}
    return foo:method("foo")
end
return ____exports`, false, false},
		{"Function expression type inference in array ({\"assignTo\":\"const meths: Method[]\",\"method\":\"meths[0]\",\"funcExp\":\"function(s) { return s; }\"})", `interface Foo {
            method(s: string): string;
        }
        interface Method {
            (this: Foo, s: string): string;
        }
        const meths: Method[] = [function(s) { return s; }];
        const foo: Foo = {method: meths[0]};
        return foo.method("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local meths = {function(self, s)
        return s
    end}
    local foo = {method = meths[1]}
    return foo:method("foo")
end
return ____exports`, false, false},
		{"Function expression type inference in array ({\"assignTo\":\"const meths: Method[]\",\"method\":\"meths[0]\",\"funcExp\":\"(function(s) { return s; })\"})", `interface Foo {
            method(s: string): string;
        }
        interface Method {
            (this: Foo, s: string): string;
        }
        const meths: Method[] = [(function(s) { return s; })];
        const foo: Foo = {method: meths[0]};
        return foo.method("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local meths = {function(self, s)
        return s
    end}
    local foo = {method = meths[1]}
    return foo:method("foo")
end
return ____exports`, false, false},
		{"Function expression type inference in array ({\"assignTo\":\"let meths: Method[]; meths\",\"method\":\"meths[0]\",\"funcExp\":\"s => s\"})", `interface Foo {
            method(s: string): string;
        }
        interface Method {
            (this: Foo, s: string): string;
        }
        let meths: Method[]; meths = [s => s];
        const foo: Foo = {method: meths[0]};
        return foo.method("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local meths
    meths = {function(____, s) return s end}
    local foo = {method = meths[1]}
    return foo:method("foo")
end
return ____exports`, false, false},
		{"Function expression type inference in array ({\"assignTo\":\"let meths: Method[]; meths\",\"method\":\"meths[0]\",\"funcExp\":\"(s => s)\"})", `interface Foo {
            method(s: string): string;
        }
        interface Method {
            (this: Foo, s: string): string;
        }
        let meths: Method[]; meths = [(s => s)];
        const foo: Foo = {method: meths[0]};
        return foo.method("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local meths
    meths = {function(____, s) return s end}
    local foo = {method = meths[1]}
    return foo:method("foo")
end
return ____exports`, false, false},
		{"Function expression type inference in array ({\"assignTo\":\"let meths: Method[]; meths\",\"method\":\"meths[0]\",\"funcExp\":\"function(s) { return s; }\"})", `interface Foo {
            method(s: string): string;
        }
        interface Method {
            (this: Foo, s: string): string;
        }
        let meths: Method[]; meths = [function(s) { return s; }];
        const foo: Foo = {method: meths[0]};
        return foo.method("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local meths
    meths = {function(self, s)
        return s
    end}
    local foo = {method = meths[1]}
    return foo:method("foo")
end
return ____exports`, false, false},
		{"Function expression type inference in array ({\"assignTo\":\"let meths: Method[]; meths\",\"method\":\"meths[0]\",\"funcExp\":\"(function(s) { return s; })\"})", `interface Foo {
            method(s: string): string;
        }
        interface Method {
            (this: Foo, s: string): string;
        }
        let meths: Method[]; meths = [(function(s) { return s; })];
        const foo: Foo = {method: meths[0]};
        return foo.method("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local meths
    meths = {function(self, s)
        return s
    end}
    local foo = {method = meths[1]}
    return foo:method("foo")
end
return ____exports`, false, false},
		{"Function expression type inference in array ({\"assignTo\":\"const [meth]: Method[]\",\"method\":\"meth\",\"funcExp\":\"s => s\"})", `interface Foo {
            method(s: string): string;
        }
        interface Method {
            (this: Foo, s: string): string;
        }
        const [meth]: Method[] = [s => s];
        const foo: Foo = {method: meth};
        return foo.method("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local function meth(____, s)
        return s
    end
    local foo = {method = meth}
    return foo:method("foo")
end
return ____exports`, false, false},
		{"Function expression type inference in array ({\"assignTo\":\"const [meth]: Method[]\",\"method\":\"meth\",\"funcExp\":\"(s => s)\"})", `interface Foo {
            method(s: string): string;
        }
        interface Method {
            (this: Foo, s: string): string;
        }
        const [meth]: Method[] = [(s => s)];
        const foo: Foo = {method: meth};
        return foo.method("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local function meth(____, s)
        return s
    end
    local foo = {method = meth}
    return foo:method("foo")
end
return ____exports`, false, false},
		{"Function expression type inference in array ({\"assignTo\":\"const [meth]: Method[]\",\"method\":\"meth\",\"funcExp\":\"function(s) { return s; }\"})", `interface Foo {
            method(s: string): string;
        }
        interface Method {
            (this: Foo, s: string): string;
        }
        const [meth]: Method[] = [function(s) { return s; }];
        const foo: Foo = {method: meth};
        return foo.method("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local function meth(self, s)
        return s
    end
    local foo = {method = meth}
    return foo:method("foo")
end
return ____exports`, false, false},
		{"Function expression type inference in array ({\"assignTo\":\"const [meth]: Method[]\",\"method\":\"meth\",\"funcExp\":\"(function(s) { return s; })\"})", `interface Foo {
            method(s: string): string;
        }
        interface Method {
            (this: Foo, s: string): string;
        }
        const [meth]: Method[] = [(function(s) { return s; })];
        const foo: Foo = {method: meth};
        return foo.method("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local function meth(self, s)
        return s
    end
    local foo = {method = meth}
    return foo:method("foo")
end
return ____exports`, false, false},
		{"Function expression type inference in array ({\"assignTo\":\"let meth: Method; [meth]\",\"method\":\"meth\",\"funcExp\":\"s => s\"})", `interface Foo {
            method(s: string): string;
        }
        interface Method {
            (this: Foo, s: string): string;
        }
        let meth: Method; [meth] = [s => s];
        const foo: Foo = {method: meth};
        return foo.method("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local meth
    meth = function(____, s) return s end
    local foo = {method = meth}
    return foo:method("foo")
end
return ____exports`, false, false},
		{"Function expression type inference in array ({\"assignTo\":\"let meth: Method; [meth]\",\"method\":\"meth\",\"funcExp\":\"(s => s)\"})", `interface Foo {
            method(s: string): string;
        }
        interface Method {
            (this: Foo, s: string): string;
        }
        let meth: Method; [meth] = [(s => s)];
        const foo: Foo = {method: meth};
        return foo.method("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local meth
    meth = function(____, s) return s end
    local foo = {method = meth}
    return foo:method("foo")
end
return ____exports`, false, false},
		{"Function expression type inference in array ({\"assignTo\":\"let meth: Method; [meth]\",\"method\":\"meth\",\"funcExp\":\"function(s) { return s; }\"})", `interface Foo {
            method(s: string): string;
        }
        interface Method {
            (this: Foo, s: string): string;
        }
        let meth: Method; [meth] = [function(s) { return s; }];
        const foo: Foo = {method: meth};
        return foo.method("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local meth
    meth = function(self, s)
        return s
    end
    local foo = {method = meth}
    return foo:method("foo")
end
return ____exports`, false, false},
		{"Function expression type inference in array ({\"assignTo\":\"let meth: Method; [meth]\",\"method\":\"meth\",\"funcExp\":\"(function(s) { return s; })\"})", `interface Foo {
            method(s: string): string;
        }
        interface Method {
            (this: Foo, s: string): string;
        }
        let meth: Method; [meth] = [(function(s) { return s; })];
        const foo: Foo = {method: meth};
        return foo.method("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local meth
    meth = function(self, s)
        return s
    end
    local foo = {method = meth}
    return foo:method("foo")
end
return ____exports`, false, false},
		{"Function expression type inference in union ({\"funcType\":\"(this: void, s: string) => string\",\"funcExp\":\"s => s\"})", `type U = string | number | ((this: void, s: string) => string);
        const u: U = s => s;
        return (u as (this: void, s: string) => string)("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local function u(s)
        return s
    end
    return u("foo")
end
return ____exports`, false, false},
		{"Function expression type inference in union ({\"funcType\":\"(this: any, s: string) => string\",\"funcExp\":\"s => s\"})", `type U = string | number | ((this: any, s: string) => string);
        const u: U = s => s;
        return (u as (this: any, s: string) => string)("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local function u(____, s)
        return s
    end
    return u(nil, "foo")
end
return ____exports`, false, false},
		{"Function expression type inference in union ({\"funcType\":\"(s: string) => string\",\"funcExp\":\"s => s\"})", `type U = string | number | ((s: string) => string);
        const u: U = s => s;
        return (u as (s: string) => string)("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local function u(____, s)
        return s
    end
    return u(nil, "foo")
end
return ____exports`, false, false},
		{"Function expression type inference in union ({\"funcType\":\"(this: void, s: string) => string\",\"funcExp\":\"function(s) { return s; }\"})", `type U = string | number | ((this: void, s: string) => string);
        const u: U = function(s) { return s; };
        return (u as (this: void, s: string) => string)("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local function u(s)
        return s
    end
    return u("foo")
end
return ____exports`, false, false},
		{"Function expression type inference in union ({\"funcType\":\"(this: any, s: string) => string\",\"funcExp\":\"function(s) { return s; }\"})", `type U = string | number | ((this: any, s: string) => string);
        const u: U = function(s) { return s; };
        return (u as (this: any, s: string) => string)("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local function u(self, s)
        return s
    end
    return u(nil, "foo")
end
return ____exports`, false, false},
		{"Function expression type inference in union ({\"funcType\":\"(s: string) => string\",\"funcExp\":\"function(s) { return s; }\"})", `type U = string | number | ((s: string) => string);
        const u: U = function(s) { return s; };
        return (u as (s: string) => string)("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local function u(self, s)
        return s
    end
    return u(nil, "foo")
end
return ____exports`, false, false},
		{"Function expression type inference in union tuple ({\"funcType\":\"(this: void, s: string) => string\",\"funcExp\":\"s => s\"})", `interface I { callback: (this: void, s: string) => string; }
        let a: I[] | number = [{ callback: s => s }];
        return a[0].callback("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local a = {{callback = function(s) return s end}}
    return a[1].callback("foo")
end
return ____exports`, false, false},
		{"Function expression type inference in union tuple ({\"funcType\":\"(this: any, s: string) => string\",\"funcExp\":\"s => s\"})", `interface I { callback: (this: any, s: string) => string; }
        let a: I[] | number = [{ callback: s => s }];
        return a[0].callback("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local a = {{callback = function(____, s) return s end}}
    return a[1]:callback("foo")
end
return ____exports`, false, false},
		{"Function expression type inference in union tuple ({\"funcType\":\"(s: string) => string\",\"funcExp\":\"s => s\"})", `interface I { callback: (s: string) => string; }
        let a: I[] | number = [{ callback: s => s }];
        return a[0].callback("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local a = {{callback = function(____, s) return s end}}
    return a[1]:callback("foo")
end
return ____exports`, false, false},
		{"Function expression type inference in union tuple ({\"funcType\":\"(this: void, s: string) => string\",\"funcExp\":\"function(s) { return s; }\"})", `interface I { callback: (this: void, s: string) => string; }
        let a: I[] | number = [{ callback: function(s) { return s; } }];
        return a[0].callback("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local a = {{callback = function(s)
        return s
    end}}
    return a[1].callback("foo")
end
return ____exports`, false, false},
		{"Function expression type inference in union tuple ({\"funcType\":\"(this: any, s: string) => string\",\"funcExp\":\"function(s) { return s; }\"})", `interface I { callback: (this: any, s: string) => string; }
        let a: I[] | number = [{ callback: function(s) { return s; } }];
        return a[0].callback("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local a = {{callback = function(self, s)
        return s
    end}}
    return a[1]:callback("foo")
end
return ____exports`, false, false},
		{"Function expression type inference in union tuple ({\"funcType\":\"(s: string) => string\",\"funcExp\":\"function(s) { return s; }\"})", `interface I { callback: (s: string) => string; }
        let a: I[] | number = [{ callback: function(s) { return s; } }];
        return a[0].callback("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local a = {{callback = function(self, s)
        return s
    end}}
    return a[1]:callback("foo")
end
return ____exports`, false, false},
		{"Function expression type inference in as cast ({\"funcType\":\"(this: void, s: string) => string\",\"funcExp\":\"s => s\"})", `const fn: (this: void, s: string) => string = (s => s) as ((this: void, s: string) => string);
        return fn("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local function fn(s)
        return s
    end
    return fn("foo")
end
return ____exports`, false, false},
		{"Function expression type inference in as cast ({\"funcType\":\"(this: any, s: string) => string\",\"funcExp\":\"s => s\"})", `const fn: (this: any, s: string) => string = (s => s) as ((this: any, s: string) => string);
        return fn("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local function fn(____, s)
        return s
    end
    return fn(nil, "foo")
end
return ____exports`, false, false},
		{"Function expression type inference in as cast ({\"funcType\":\"(s: string) => string\",\"funcExp\":\"s => s\"})", `const fn: (s: string) => string = (s => s) as ((s: string) => string);
        return fn("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local function fn(____, s)
        return s
    end
    return fn(nil, "foo")
end
return ____exports`, false, false},
		{"Function expression type inference in as cast ({\"funcType\":\"(this: void, s: string) => string\",\"funcExp\":\"function(s) { return s; }\"})", `const fn: (this: void, s: string) => string = (function(s) { return s; }) as ((this: void, s: string) => string);
        return fn("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local function fn(s)
        return s
    end
    return fn("foo")
end
return ____exports`, false, false},
		{"Function expression type inference in as cast ({\"funcType\":\"(this: any, s: string) => string\",\"funcExp\":\"function(s) { return s; }\"})", `const fn: (this: any, s: string) => string = (function(s) { return s; }) as ((this: any, s: string) => string);
        return fn("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local function fn(self, s)
        return s
    end
    return fn(nil, "foo")
end
return ____exports`, false, false},
		{"Function expression type inference in as cast ({\"funcType\":\"(s: string) => string\",\"funcExp\":\"function(s) { return s; }\"})", `const fn: (s: string) => string = (function(s) { return s; }) as ((s: string) => string);
        return fn("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local function fn(self, s)
        return s
    end
    return fn(nil, "foo")
end
return ____exports`, false, false},
		{"Function expression type inference in type assertion ({\"funcType\":\"(this: void, s: string) => string\",\"funcExp\":\"s => s\"})", `const fn: (this: void, s: string) => string = <(this: void, s: string) => string>(s => s);
        return fn("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local function fn(s)
        return s
    end
    return fn("foo")
end
return ____exports`, false, false},
		{"Function expression type inference in type assertion ({\"funcType\":\"(this: any, s: string) => string\",\"funcExp\":\"s => s\"})", `const fn: (this: any, s: string) => string = <(this: any, s: string) => string>(s => s);
        return fn("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local function fn(____, s)
        return s
    end
    return fn(nil, "foo")
end
return ____exports`, false, false},
		{"Function expression type inference in type assertion ({\"funcType\":\"(s: string) => string\",\"funcExp\":\"s => s\"})", `const fn: (s: string) => string = <(s: string) => string>(s => s);
        return fn("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local function fn(____, s)
        return s
    end
    return fn(nil, "foo")
end
return ____exports`, false, false},
		{"Function expression type inference in type assertion ({\"funcType\":\"(this: void, s: string) => string\",\"funcExp\":\"function(s) { return s; }\"})", `const fn: (this: void, s: string) => string = <(this: void, s: string) => string>(function(s) { return s; });
        return fn("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local function fn(s)
        return s
    end
    return fn("foo")
end
return ____exports`, false, false},
		{"Function expression type inference in type assertion ({\"funcType\":\"(this: any, s: string) => string\",\"funcExp\":\"function(s) { return s; }\"})", `const fn: (this: any, s: string) => string = <(this: any, s: string) => string>(function(s) { return s; });
        return fn("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local function fn(self, s)
        return s
    end
    return fn(nil, "foo")
end
return ____exports`, false, false},
		{"Function expression type inference in type assertion ({\"funcType\":\"(s: string) => string\",\"funcExp\":\"function(s) { return s; }\"})", `const fn: (s: string) => string = <(s: string) => string>(function(s) { return s; });
        return fn("foo");`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local function fn(self, s)
        return s
    end
    return fn(nil, "foo")
end
return ____exports`, false, false},
		{"Function expression type inference in constructor ({\"funcType\":\"(this: void, s: string) => string\",\"funcExp\":\"s => s\"})", `class C {
            result: string;
            constructor(fn: (this: void, s: string) => string) { this.result = fn("foo"); }
        }
        const c = new C(s => s);
        return c.result;`, `"foo"`, `local ____lualib = require("lualib_bundle")
local __TS__Class = ____lualib.__TS__Class
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local C = __TS__Class()
    C.name = "C"
    function C.prototype.____constructor(self, fn)
        self.result = fn("foo")
    end
    local c = __TS__New(
        C,
        function(s) return s end
    )
    return c.result
end
return ____exports`, false, false},
		{"Function expression type inference in constructor ({\"funcType\":\"(this: any, s: string) => string\",\"funcExp\":\"s => s\"})", `class C {
            result: string;
            constructor(fn: (this: any, s: string) => string) { this.result = fn("foo"); }
        }
        const c = new C(s => s);
        return c.result;`, `"foo"`, `local ____lualib = require("lualib_bundle")
local __TS__Class = ____lualib.__TS__Class
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local C = __TS__Class()
    C.name = "C"
    function C.prototype.____constructor(self, fn)
        self.result = fn(nil, "foo")
    end
    local c = __TS__New(
        C,
        function(____, s) return s end
    )
    return c.result
end
return ____exports`, false, false},
		{"Function expression type inference in constructor ({\"funcType\":\"(s: string) => string\",\"funcExp\":\"s => s\"})", `class C {
            result: string;
            constructor(fn: (s: string) => string) { this.result = fn("foo"); }
        }
        const c = new C(s => s);
        return c.result;`, `"foo"`, `local ____lualib = require("lualib_bundle")
local __TS__Class = ____lualib.__TS__Class
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local C = __TS__Class()
    C.name = "C"
    function C.prototype.____constructor(self, fn)
        self.result = fn(nil, "foo")
    end
    local c = __TS__New(
        C,
        function(____, s) return s end
    )
    return c.result
end
return ____exports`, false, false},
		{"Function expression type inference in constructor ({\"funcType\":\"(this: void, s: string) => string\",\"funcExp\":\"function(s) { return s; }\"})", `class C {
            result: string;
            constructor(fn: (this: void, s: string) => string) { this.result = fn("foo"); }
        }
        const c = new C(function(s) { return s; });
        return c.result;`, `"foo"`, `local ____lualib = require("lualib_bundle")
local __TS__Class = ____lualib.__TS__Class
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local C = __TS__Class()
    C.name = "C"
    function C.prototype.____constructor(self, fn)
        self.result = fn("foo")
    end
    local c = __TS__New(
        C,
        function(s)
            return s
        end
    )
    return c.result
end
return ____exports`, false, false},
		{"Function expression type inference in constructor ({\"funcType\":\"(this: any, s: string) => string\",\"funcExp\":\"function(s) { return s; }\"})", `class C {
            result: string;
            constructor(fn: (this: any, s: string) => string) { this.result = fn("foo"); }
        }
        const c = new C(function(s) { return s; });
        return c.result;`, `"foo"`, `local ____lualib = require("lualib_bundle")
local __TS__Class = ____lualib.__TS__Class
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local C = __TS__Class()
    C.name = "C"
    function C.prototype.____constructor(self, fn)
        self.result = fn(nil, "foo")
    end
    local c = __TS__New(
        C,
        function(self, s)
            return s
        end
    )
    return c.result
end
return ____exports`, false, false},
		{"Function expression type inference in constructor ({\"funcType\":\"(s: string) => string\",\"funcExp\":\"function(s) { return s; }\"})", `class C {
            result: string;
            constructor(fn: (s: string) => string) { this.result = fn("foo"); }
        }
        const c = new C(function(s) { return s; });
        return c.result;`, `"foo"`, `local ____lualib = require("lualib_bundle")
local __TS__Class = ____lualib.__TS__Class
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local C = __TS__Class()
    C.name = "C"
    function C.prototype.____constructor(self, fn)
        self.result = fn(nil, "foo")
    end
    local c = __TS__New(
        C,
        function(self, s)
            return s
        end
    )
    return c.result
end
return ____exports`, false, false},
	})

	batchRunTests(t, []batchTestCase{
		{name: "noSelf function method argument (\"noSelf\")", tsCode: `
        /** @noSelf */ namespace NS {
            export class C {
                method(fn: (s: string) => string) { return fn("foo"); }
            }
        }
        function foo(this: void, s: string) { return s; }
    
export function __main() {const c = new NS.C();
        return c.method(foo);}`, accessor: `mod.__main()`, want: `"foo"`, refLua: `local ____lualib = require("lualib_bundle")
local __TS__Class = ____lualib.__TS__Class
local __TS__New = ____lualib.__TS__New
local ____exports = {}
local NS = {}
do
    NS.C = __TS__Class()
    local C = NS.C
    C.name = "C"
    function C.prototype.____constructor(self)
    end
    function C.prototype.method(self, fn)
        return fn("foo")
    end
end
local function foo(s)
    return s
end
function ____exports.__main(self)
    local c = __TS__New(NS.C)
    return c:method(foo)
end
return ____exports`},
		{name: "noSelf function method argument (\"noSelfInFile\")", tsCode: `
        /** @noSelfInFile */ namespace NS {
            export class C {
                method(fn: (s: string) => string) { return fn("foo"); }
            }
        }
        function foo(this: void, s: string) { return s; }
    
export function __main() {const c = new NS.C();
        return c.method(foo);}`, accessor: `mod.__main()`, want: `"foo"`, refLua: `local ____lualib = require("lualib_bundle")
local __TS__Class = ____lualib.__TS__Class
local __TS__New = ____lualib.__TS__New
local ____exports = {}
local NS = {}
do
    NS.C = __TS__Class()
    local C = NS.C
    C.name = "C"
    function C.prototype.____constructor(self)
    end
    function C.prototype.method(self, fn)
        return fn("foo")
    end
end
local function foo(s)
    return s
end
function ____exports.__main()
    local c = __TS__New(NS.C)
    return c:method(foo)
end
return ____exports`},
		{name: "Function expression type inference in binary operator (\"(this: void, s: string) => string\")", tsCode: `let undefinedFunc: ((this: void, s: string) => string) | undefined;
export function __main() {let func: (this: void, s: string) => string = s => s;
            func = undefinedFunc || (s => s);
            return func("foo");}`, accessor: `mod.__main()`, want: `"foo"`, refLua: `local ____exports = {}
local undefinedFunc
function ____exports.__main(self)
    local function func(s)
        return s
    end
    func = undefinedFunc or (function(s) return s end)
    return func("foo")
end
return ____exports`},
		{name: "Function expression type inference in binary operator (\"(this: any, s: string) => string\")", tsCode: `let undefinedFunc: ((this: any, s: string) => string) | undefined;
export function __main() {let func: (this: any, s: string) => string = s => s;
            func = undefinedFunc || (s => s);
            return func("foo");}`, accessor: `mod.__main()`, want: `"foo"`, refLua: `local ____exports = {}
local undefinedFunc
function ____exports.__main(self)
    local function func(____, s)
        return s
    end
    func = undefinedFunc or (function(____, s) return s end)
    return func(nil, "foo")
end
return ____exports`},
		{name: "Function expression type inference in binary operator (\"(s: string) => string\")", tsCode: `let undefinedFunc: ((s: string) => string) | undefined;
export function __main() {let func: (s: string) => string = s => s;
            func = undefinedFunc || (s => s);
            return func("foo");}`, accessor: `mod.__main()`, want: `"foo"`, refLua: `local ____exports = {}
local undefinedFunc
function ____exports.__main(self)
    local function func(____, s)
        return s
    end
    func = undefinedFunc or (function(____, s) return s end)
    return func(nil, "foo")
end
return ____exports`},
	})
}
