// Code generated by scripts/migrate from extern/tstl/test/unit/functions/functionProperties.spec.ts. DO NOT EDIT.
package tstltest

import "testing"

func TestEval_FunctionProperties(t *testing.T) {
	t.Parallel()

	batchExpectFunctions(t, []funcTestCase{
		{"property on function", `function foo(s: string) { return s; }
        foo.bar = "bar";
        return foo("foo") + foo.bar;`, `"foobar"`, `local ____exports = {}
function ____exports.__main(self)
    local foo = setmetatable(
        {},
        {__call = function(____, self, s)
            return s
        end}
    )
    foo.bar = "bar"
    return foo(nil, "foo") .. foo.bar
end
return ____exports`, false, false},
		{"property on void function", `function foo(this: void, s: string) { return s; }
        foo.bar = "bar";
        return foo("foo") + foo.bar;`, `"foobar"`, `local ____exports = {}
function ____exports.__main(self)
    local foo = setmetatable(
        {},
        {__call = function(____, s)
            return s
        end}
    )
    foo.bar = "bar"
    return foo("foo") .. foo.bar
end
return ____exports`, false, false},
		{"property on recursively referenced function", `function foo(s: string) { return s + foo.bar; }
        foo.bar = "bar";
        return foo("foo") + foo.bar;`, `"foobarbar"`, `local ____exports = {}
function ____exports.__main(self)
    local foo
    foo = setmetatable(
        {},
        {__call = function(____, self, s)
            return s .. foo.bar
        end}
    )
    foo.bar = "bar"
    return foo(nil, "foo") .. foo.bar
end
return ____exports`, false, false},
		{"property on hoisted function", `foo.bar = "bar";
        function foo(s: string) { return s; }
        return foo("foo") + foo.bar;`, `"foobar"`, `local ____exports = {}
function ____exports.__main(self)
    local foo
    foo = setmetatable(
        {},
        {__call = function(____, self, s)
            return s
        end}
    )
    foo.bar = "bar"
    return foo(nil, "foo") .. foo.bar
end
return ____exports`, false, false},
		{"function with property assigned to variable", `const foo = function(s: string) { return s; };
        foo.bar = "bar";
        return foo("foo") + foo.bar;`, `"foobar"`, `local ____exports = {}
function ____exports.__main(self)
    local foo = setmetatable(
        {},
        {__call = function(____, self, s)
            return s
        end}
    )
    foo.bar = "bar"
    return foo(nil, "foo") .. foo.bar
end
return ____exports`, false, false},
		{"void function with property assigned to variable", `const foo = function(this: void, s: string) { return s; };
        foo.bar = "bar";
        return foo("foo") + foo.bar;`, `"foobar"`, `local ____exports = {}
function ____exports.__main(self)
    local foo = setmetatable(
        {},
        {__call = function(____, s)
            return s
        end}
    )
    foo.bar = "bar"
    return foo("foo") .. foo.bar
end
return ____exports`, false, false},
		{"named function with property assigned to variable", `const foo = function baz(s: string) { return s; }
        foo.bar = "bar";
        return foo("foo") + foo.bar;`, `"foobar"`, `local ____exports = {}
function ____exports.__main(self)
    local foo = setmetatable(
        {},
        {__call = function(____, self, s)
            return s
        end}
    )
    foo.bar = "bar"
    return foo(nil, "foo") .. foo.bar
end
return ____exports`, false, false},
		{"recursively referenced function with property assigned to variable", `const foo = function(s: string) { return s + foo.bar; };
        foo.bar = "bar";
        return foo("foo") + foo.bar;`, `"foobarbar"`, `local ____exports = {}
function ____exports.__main(self)
    local foo
    foo = setmetatable(
        {},
        {__call = function(____, self, s)
            return s .. foo.bar
        end}
    )
    foo.bar = "bar"
    return foo(nil, "foo") .. foo.bar
end
return ____exports`, false, false},
		{"named recursively referenced function with property assigned to variable", `const foo = function baz(s: string) { return s + foo.bar + baz.bar; };
        foo.bar = "bar";
        return foo("foo") + foo.bar;`, `"foobarbarbar"`, `local ____exports = {}
function ____exports.__main(self)
    local foo
    local baz
    baz = setmetatable(
        {},
        {__call = function(____, self, s)
            return (s .. foo.bar) .. baz.bar
        end}
    )
    foo = baz
    foo.bar = "bar"
    return foo(nil, "foo") .. foo.bar
end
return ____exports`, false, false},
		{"arrow function with property assigned to variable", `const foo: { (s: string): string; bar: string; } = s => s;
        foo.bar = "bar";
        return foo("foo") + foo.bar;`, `"foobar"`, `local ____exports = {}
function ____exports.__main(self)
    local foo = setmetatable(
        {},
        {__call = function(____, ____, s) return s end}
    )
    foo.bar = "bar"
    return foo(nil, "foo") .. foo.bar
end
return ____exports`, false, false},
		{"void arrow function with property assigned to variable", `const foo: { (this: void, s: string): string; bar: string; } = s => s;
        foo.bar = "bar";
        return foo("foo") + foo.bar;`, `"foobar"`, `local ____exports = {}
function ____exports.__main(self)
    local foo = setmetatable(
        {},
        {__call = function(____, s) return s end}
    )
    foo.bar = "bar"
    return foo("foo") .. foo.bar
end
return ____exports`, false, false},
		{"recursively referenced arrow function with property assigned to variable", `const foo: { (s: string): string; bar: string; } = s => s + foo.bar;
        foo.bar = "bar";
        return foo("foo") + foo.bar;`, `"foobarbar"`, `local ____exports = {}
function ____exports.__main(self)
    local foo
    foo = setmetatable(
        {},
        {__call = function(____, ____, s) return s .. foo.bar end}
    )
    foo.bar = "bar"
    return foo(nil, "foo") .. foo.bar
end
return ____exports`, false, false},
		{"property on generator function", `function *foo(s: string) { yield s; }
        foo.bar = "bar";
        for (const s of foo("foo")) {
            return s + foo.bar;
        }`, `"foobar"`, `local ____lualib = require("lualib_bundle")
local __TS__Generator = ____lualib.__TS__Generator
local __TS__Iterator = ____lualib.__TS__Iterator
local ____exports = {}
function ____exports.__main(self)
    local foo = setmetatable(
        {},
        {__call = function(____, ...) return __TS__Generator(function(self, s)
            coroutine.yield(s)
        end)(...) end}
    )
    foo.bar = "bar"
    for ____, s in __TS__Iterator(foo(nil, "foo")) do
        return s .. foo.bar
    end
end
return ____exports`, false, false},
		{"generator function assigned to variable", `const foo = function *(s: string) { yield s; }
        foo.bar = "bar";
        for (const s of foo("foo")) {
            return s + foo.bar;
        }`, `"foobar"`, `local ____lualib = require("lualib_bundle")
local __TS__Generator = ____lualib.__TS__Generator
local __TS__Iterator = ____lualib.__TS__Iterator
local ____exports = {}
function ____exports.__main(self)
    local foo = setmetatable(
        {},
        {__call = function(____, ...) return __TS__Generator(function(self, s)
            coroutine.yield(s)
        end)(...) end}
    )
    foo.bar = "bar"
    for ____, s in __TS__Iterator(foo(nil, "foo")) do
        return s .. foo.bar
    end
end
return ____exports`, false, false},
		{"property on async function", `let result = "";
        async function foo(s: string) { result = s + foo.bar; }
        foo.bar = "bar";
        void foo("foo");
        return result;`, `"foobar"`, `local ____lualib = require("lualib_bundle")
local __TS__AsyncAwaiter = ____lualib.__TS__AsyncAwaiter
local __TS__Await = ____lualib.__TS__Await
local ____exports = {}
function ____exports.__main(self)
    local result = ""
    local foo
    foo = setmetatable(
        {},
        {__call = function(____, self, s)
            return __TS__AsyncAwaiter(function(____awaiter_resolve)
                result = s .. foo.bar
            end)
        end}
    )
    foo.bar = "bar"
    foo(nil, "foo")
    return result
end
return ____exports`, false, false},
		{"async function with property assigned to variable", `let result = "";
        const foo = async function(s: string) { result = s + foo.bar; }
        foo.bar = "bar";
        void foo("foo");
        return result;`, `"foobar"`, `local ____lualib = require("lualib_bundle")
local __TS__AsyncAwaiter = ____lualib.__TS__AsyncAwaiter
local __TS__Await = ____lualib.__TS__Await
local ____exports = {}
function ____exports.__main(self)
    local result = ""
    local foo
    foo = setmetatable(
        {},
        {__call = function(____, self, s)
            return __TS__AsyncAwaiter(function(____awaiter_resolve)
                result = s .. foo.bar
            end)
        end}
    )
    foo.bar = "bar"
    foo(nil, "foo")
    return result
end
return ____exports`, false, false},
		{"async arrow function with property assigned to variable", `let result = "";
        const foo: { (s: string): Promise<void>; bar: string; } = async s => { result = s + foo.bar; };
        foo.bar = "bar";
        void foo("foo");
        return result;`, `"foobar"`, `local ____lualib = require("lualib_bundle")
local __TS__AsyncAwaiter = ____lualib.__TS__AsyncAwaiter
local __TS__Await = ____lualib.__TS__Await
local ____exports = {}
function ____exports.__main(self)
    local result = ""
    local foo
    foo = setmetatable(
        {},
        {__call = function(____, ____, s)
            return __TS__AsyncAwaiter(function(____awaiter_resolve)
                result = s .. foo.bar
            end)
        end}
    )
    foo.bar = "bar"
    foo(nil, "foo")
    return result
end
return ____exports`, false, false},
		{"call function with property using call method", `function foo(this: string, s: string) { return this + s; }
        foo.baz = "baz";
        return foo.call("foo", "bar") + foo.baz;`, `"foobarbaz"`, `local ____exports = {}
function ____exports.__main(self)
    local foo = setmetatable(
        {},
        {__call = function(____, self, s)
            return self .. s
        end}
    )
    foo.baz = "baz"
    return foo("foo", "bar") .. foo.baz
end
return ____exports`, false, false},
		{"call function with property using apply method", `function foo(this: string, s: string) { return this + s; }
        foo.baz = "baz";
        return foo.apply("foo", ["bar"]) + foo.baz;`, `"foobarbaz"`, `local ____exports = {}
function ____exports.__main(self)
    local foo = setmetatable(
        {},
        {__call = function(____, self, s)
            return self .. s
        end}
    )
    foo.baz = "baz"
    return foo(
        "foo",
        table.unpack({"bar"})
    ) .. foo.baz
end
return ____exports`, false, false},
		{"call function with property using bind method", `function foo(this: string, s: string) { return this + s; }
        foo.baz = "baz";
        return foo.bind("foo", "bar")() + foo.baz;`, `"foobarbaz"`, `local ____lualib = require("lualib_bundle")
local __TS__FunctionBind = ____lualib.__TS__FunctionBind
local ____exports = {}
function ____exports.__main(self)
    local foo = setmetatable(
        {},
        {__call = function(____, self, s)
            return self .. s
        end}
    )
    foo.baz = "baz"
    return __TS__FunctionBind(foo, "foo", "bar")(nil) .. foo.baz
end
return ____exports`, false, false},
		{"Does not wrap simple variable declaration", `function foo(s: string) { return s; }
        foo.bar = "bar";
        const foo2 = foo;
        return foo2("foo") + foo2.bar;`, `"foobar"`, `local ____exports = {}
function ____exports.__main(self)
    local foo = setmetatable(
        {},
        {__call = function(____, self, s)
            return s
        end}
    )
    foo.bar = "bar"
    local foo2 = foo
    return foo2(nil, "foo") .. foo2.bar
end
return ____exports`, false, false},
		{"Wraps function in inner expression", `type Foo = { (s: string): string; bar: string; }
        const foo = (s => s)! as Foo
        foo.bar = "bar";
        return foo("foo") + foo.bar;`, `"foobar"`, `local ____exports = {}
function ____exports.__main(self)
    local foo = setmetatable(
        {},
        {__call = function(____, ____, s) return s end}
    )
    foo.bar = "bar"
    return foo(nil, "foo") .. foo.bar
end
return ____exports`, false, false},
	})

	batchRunTests(t, []batchTestCase{
		{name: "function merged with namespace", tsCode: `function foo(s: string) { return s; }
        namespace foo {
            export let bar = "bar";
        }
        export const result = foo("foo") + foo.bar;`, accessor: `mod["result"]`, want: `"foobar"`, refLua: `local ____exports = {}
local foo = setmetatable(
    {},
    {__call = function(____, self, s)
        return s
    end}
)
do
    foo.bar = "bar"
end
____exports.result = foo(nil, "foo") .. foo.bar
return ____exports`},
	})
}
