// Code generated by scripts/migrate from extern/tstl/test/unit/functions/generators.spec.ts. DO NOT EDIT.
package tstltest

import (
	"testing"

	"github.com/realcoldfry/tslua/internal/transpiler"
)

func TestEval_Generators(t *testing.T) {
	t.Parallel()

	batchExpectFunctions(t, []funcTestCase{
		{"generator parameters", `function* generator(value: number) {
            yield value;
        }

        return generator(5).next();`, `{done = false, value = 5}`, `local ____lualib = require("lualib_bundle")
local __TS__Generator = ____lualib.__TS__Generator
local ____exports = {}
function ____exports.__main(self)
    local generator = __TS__Generator(function(self, value)
        coroutine.yield(value)
    end)
    return generator(nil, 5):next()
end
return ____exports`, false, false},
		{".next()", `function* generator() {
            yield 1;
            yield 2;
            return 3;
        }

        const it = generator();
        return [it.next(), it.next(), it.next(), it.next()];`, `{{done = false, value = 1}, {done = false, value = 2}, {done = true, value = 3}, {done = true}}`, `local ____lualib = require("lualib_bundle")
local __TS__Generator = ____lualib.__TS__Generator
local ____exports = {}
function ____exports.__main(self)
    local generator = __TS__Generator(function(self)
        coroutine.yield(1)
        coroutine.yield(2)
        return 3
    end)
    local it = generator(nil)
    return {
        it:next(),
        it:next(),
        it:next(),
        it:next()
    }
end
return ____exports`, false, false},
		{".next() with parameters", `function* generator(): Generator<number, number, number> {
            return yield 0;
        }

        const it = generator();
        return [it.next(1), it.next(2), it.next(3)];`, `{{done = false, value = 0}, {done = true, value = 2}, {done = true}}`, `local ____lualib = require("lualib_bundle")
local __TS__Generator = ____lualib.__TS__Generator
local ____exports = {}
function ____exports.__main(self)
    local generator = __TS__Generator(function(self)
        return coroutine.yield(0)
    end)
    local it = generator(nil)
    return {
        it:next(1),
        it:next(2),
        it:next(3)
    }
end
return ____exports`, false, false},
		{"for..of", `function* generator() {
            yield 1;
            yield 2;
            yield undefined;
            return 3;
        }

        const results = [];
        for (const value of generator()) {
            results.push({ value });
        }
        return results;`, `{{value = 1}, {value = 2}, {}}`, `local ____lualib = require("lualib_bundle")
local __TS__Generator = ____lualib.__TS__Generator
local __TS__Iterator = ____lualib.__TS__Iterator
local ____exports = {}
function ____exports.__main(self)
    local generator = __TS__Generator(function(self)
        coroutine.yield(1)
        coroutine.yield(2)
        coroutine.yield(nil)
        return 3
    end)
    local results = {}
    for ____, value in __TS__Iterator(generator(nil)) do
        results[#results + 1] = {value = value}
    end
    return results
end
return ____exports`, false, false},
		{"yield* generator", `function* subGenerator() {
                yield 1;
                yield 2;
                yield 3;
            }

            function* generator() {
                yield 0;
                return yield* subGenerator();
            }

            const it = generator();
            return [it.next(), it.next(), it.next(), it.next(), it.next()];`, `{{done = false, value = 0}, {done = false, value = 1}, {done = false, value = 2}, {done = false, value = 3}, {done = true}}`, `local ____lualib = require("lualib_bundle")
local __TS__Generator = ____lualib.__TS__Generator
local __TS__DelegatedYield = ____lualib.__TS__DelegatedYield
local ____exports = {}
function ____exports.__main(self)
    local subGenerator = __TS__Generator(function(self)
        coroutine.yield(1)
        coroutine.yield(2)
        coroutine.yield(3)
    end)
    local generator = __TS__Generator(function(self)
        coroutine.yield(0)
        return __TS__DelegatedYield(subGenerator(nil))
    end)
    local it = generator(nil)
    return {
        it:next(),
        it:next(),
        it:next(),
        it:next(),
        it:next()
    }
end
return ____exports`, false, false},
		{"yield* array", `function* generator() {
                return yield* [1, 2, 3];
            }

            const it = generator();
            return [it.next(), it.next(), it.next(), it.next()];`, `{{done = false, value = 1}, {done = false, value = 2}, {done = false, value = 3}, {done = true}}`, `local ____lualib = require("lualib_bundle")
local __TS__DelegatedYield = ____lualib.__TS__DelegatedYield
local __TS__Generator = ____lualib.__TS__Generator
local ____exports = {}
function ____exports.__main(self)
    local generator = __TS__Generator(function(self)
        return __TS__DelegatedYield({1, 2, 3})
    end)
    local it = generator(nil)
    return {
        it:next(),
        it:next(),
        it:next(),
        it:next()
    }
end
return ____exports`, false, false},
		{"yield* string", `function* generator() {
                return yield* "abc";
            }

            const it = generator();
            return [it.next(), it.next(), it.next(), it.next()];`, `{{done = false, value = "a"}, {done = false, value = "b"}, {done = false, value = "c"}, {done = true}}`, `local ____lualib = require("lualib_bundle")
local __TS__DelegatedYield = ____lualib.__TS__DelegatedYield
local __TS__Generator = ____lualib.__TS__Generator
local ____exports = {}
function ____exports.__main(self)
    local generator = __TS__Generator(function(self)
        return __TS__DelegatedYield("abc")
    end)
    local it = generator(nil)
    return {
        it:next(),
        it:next(),
        it:next(),
        it:next()
    }
end
return ____exports`, false, false},
		{"yield* iterable", `function* generator() {
                return yield* new Set([1, 2, 3]);
            }

            const it = generator();
            return [it.next(), it.next(), it.next(), it.next()];`, `{{done = false, value = 1}, {done = false, value = 2}, {done = false, value = 3}, {done = true}}`, `local ____lualib = require("lualib_bundle")
local Set = ____lualib.Set
local __TS__New = ____lualib.__TS__New
local __TS__DelegatedYield = ____lualib.__TS__DelegatedYield
local __TS__Generator = ____lualib.__TS__Generator
local ____exports = {}
function ____exports.__main(self)
    local generator = __TS__Generator(function(self)
        return __TS__DelegatedYield(__TS__New(Set, {1, 2, 3}))
    end)
    local it = generator(nil)
    return {
        it:next(),
        it:next(),
        it:next(),
        it:next()
    }
end
return ____exports`, false, false},
		{"function expression", `const generator = function*() {
            return true;
        }

        return generator().next();`, `{done = true, value = true}`, `local ____lualib = require("lualib_bundle")
local __TS__Generator = ____lualib.__TS__Generator
local ____exports = {}
function ____exports.__main(self)
    local generator = __TS__Generator(function(self)
        return true
    end)
    return generator(nil):next()
end
return ____exports`, false, false},
		{"class method", `class A {
            *generator() {
                return true;
            }
        }

        return new A().generator().next();`, `{done = true, value = true}`, `local ____lualib = require("lualib_bundle")
local __TS__Class = ____lualib.__TS__Class
local __TS__Generator = ____lualib.__TS__Generator
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local A = __TS__Class()
    A.name = "A"
    function A.prototype.____constructor(self)
    end
    A.prototype.generator = __TS__Generator(function(self)
        return true
    end)
    return __TS__New(A):generator():next()
end
return ____exports`, false, false},
		{"object member", `const a = {
            *generator() {
                return true;
            }
        }

        return a.generator().next();`, `{done = true, value = true}`, `local ____lualib = require("lualib_bundle")
local __TS__Generator = ____lualib.__TS__Generator
local ____exports = {}
function ____exports.__main(self)
    local a = {generator = __TS__Generator(function(self)
        return true
    end)}
    return a:generator():next()
end
return ____exports`, false, false},
		{"hoisting", `return generator().next();

        function* generator() {
            return true;
        }`, `{done = true, value = true}`, `local ____lualib = require("lualib_bundle")
local __TS__Generator = ____lualib.__TS__Generator
local ____exports = {}
function ____exports.__main(self)
    local generator
    generator = __TS__Generator(function(self)
        return true
    end)
    return generator(nil):next()
end
return ____exports`, false, false},
	})

	batchExpectDiagnostics(t, []diagTestCase{
		{"generator yield inside try/catch [5.0]", "function", `function* generator() {
            try {
                yield 4;
            } catch {
                throw "something went wrong";
            }
        }
        return generator().next();`, []int32{100027}, nil},
	}, WithLuaTarget(transpiler.LuaTargetLua50))

	batchExpectDiagnostics(t, []diagTestCase{
		{"generator yield inside try/catch [5.1]", "function", `function* generator() {
            try {
                yield 4;
            } catch {
                throw "something went wrong";
            }
        }
        return generator().next();`, []int32{100027}, nil},
	}, WithLuaTarget(transpiler.LuaTargetLua51))

	batchExpectDiagnostics(t, []diagTestCase{
		{"generator yield inside try/catch [universal]", "function", `function* generator() {
            try {
                yield 4;
            } catch {
                throw "something went wrong";
            }
        }
        return generator().next();`, []int32{100027}, nil},
	}, WithLuaTarget(transpiler.LuaTargetUniversal))

	t.Run("generator yield inside try/catch [JIT]", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function* generator() {
            try {
                yield 4;
            } catch {
                throw "something went wrong";
            }
        }
        return generator().next();`, `{done = false, value = 4}`, WithLuaTarget(transpiler.LuaTargetLuaJIT))
	})

	t.Run("generator yield inside try/catch [5.2]", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function* generator() {
            try {
                yield 4;
            } catch {
                throw "something went wrong";
            }
        }
        return generator().next();`, `{done = false, value = 4}`, WithLuaTarget(transpiler.LuaTargetLua52))
	})

	t.Run("generator yield inside try/catch [5.3]", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function* generator() {
            try {
                yield 4;
            } catch {
                throw "something went wrong";
            }
        }
        return generator().next();`, `{done = false, value = 4}`, WithLuaTarget(transpiler.LuaTargetLua53))
	})

	t.Run("generator yield inside try/catch [5.4]", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function* generator() {
            try {
                yield 4;
            } catch {
                throw "something went wrong";
            }
        }
        return generator().next();`, `{done = false, value = 4}`, WithLuaTarget(transpiler.LuaTargetLua54))
	})

	t.Run("generator yield inside try/catch [5.5]", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function* generator() {
            try {
                yield 4;
            } catch {
                throw "something went wrong";
            }
        }
        return generator().next();`, `{done = false, value = 4}`, WithLuaTarget(transpiler.LuaTargetLua55))
	})
}
