// Code generated by scripts/migrate from extern/tstl/test/unit/builtins/globalThis.spec.ts. DO NOT EDIT.
package tstltest

import "testing"

func TestEval_GlobalThis(t *testing.T) {
	t.Parallel()

	batchRunTests(t, []batchTestCase{
		{name: "equals _G", tsCode: `declare const _G: typeof globalThis;
export const __result = globalThis === _G;`, accessor: `mod["__result"]`, want: `true`, refLua: `local ____exports = {}
____exports.__result = _G == _G
return ____exports`},
		{name: "registers global symbol", tsCode: `declare global { var foo: string }
export function __main() {globalThis.foo = "bar";
        return foo;}`, accessor: `mod.__main()`, want: `"bar"`, refLua: `local ____exports = {}
function ____exports.__main(self)
    _G.foo = "bar"
    return foo
end
return ____exports`},
		{name: "uses global symbol", tsCode: `declare global { var foo: string }
export function __main() {foo = "bar";
        return globalThis.foo;}`, accessor: `mod.__main()`, want: `"bar"`, refLua: `local ____exports = {}
function ____exports.__main(self)
    foo = "bar"
    return _G.foo
end
return ____exports`},
		{name: "function call", tsCode: `declare global { var foo: () => string }
export function __main() {foo = () => "bar";
        return globalThis.foo();}`, accessor: `mod.__main()`, want: `"bar"`, refLua: `local ____exports = {}
function ____exports.__main(self)
    foo = function() return "bar" end
    return _G:foo()
end
return ____exports`, allowDiagnostics: true},
	})
}
