// Code generated by scripts/migrate from extern/tstl/test/unit/hoisting.spec.ts. DO NOT EDIT.
package tstltest

import "testing"

func TestEval_Hoisting(t *testing.T) {
	t.Parallel()

	batchExpectFunctions(t, []funcTestCase{
		{"Let/Const Hoisting (\"let\")", `let bar: string;
        function setBar() { bar = foo; }
        let foo = "foo";
        setBar();
        return foo;`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local foo
    local bar
    local function setBar(self)
        bar = foo
    end
    foo = "foo"
    setBar(nil)
    return foo
end
return ____exports`, false, false},
		{"Let/Const Hoisting (\"const\")", `let bar: string;
        function setBar() { bar = foo; }
        const foo = "foo";
        setBar();
        return foo;`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local foo
    local bar
    local function setBar(self)
        bar = foo
    end
    foo = "foo"
    setBar(nil)
    return foo
end
return ____exports`, false, false},
		{"Global Function Hoisting", `const foo = bar();
        function bar() { return "bar"; }
        return foo;`, `"bar"`, `local ____exports = {}
function ____exports.__main(self)
    local bar
    function bar(self)
        return "bar"
    end
    local foo = bar(nil)
    return foo
end
return ____exports`, false, false},
		{"Hoisting in Non-Function Scope (\"let\")", `function foo() {
            let bar = "bar";
            for (let i = 0; i < 1; ++i) {
                let bar = "foo";
            }
            return bar;
        }
        return foo();`, `"bar"`, `local ____exports = {}
function ____exports.__main(self)
    local function foo(self)
        local bar = "bar"
        do
            local i = 0
            while i < 1 do
                local bar = "foo"
                i = i + 1
            end
        end
        return bar
    end
    return foo(nil)
end
return ____exports`, false, false},
		{"Hoisting in Non-Function Scope (\"const\")", `function foo() {
            const bar = "bar";
            for (let i = 0; i < 1; ++i) {
                const bar = "foo";
            }
            return bar;
        }
        return foo();`, `"bar"`, `local ____exports = {}
function ____exports.__main(self)
    local function foo(self)
        local bar = "bar"
        do
            local i = 0
            while i < 1 do
                local bar = "foo"
                i = i + 1
            end
        end
        return bar
    end
    return foo(nil)
end
return ____exports`, false, false},
		{"Hoisting due to reference from hoisted function", `const foo = "foo";
        const result = bar();
        function bar() {
            return foo;
        }
        return result;`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local bar, foo
    function bar(self)
        return foo
    end
    foo = "foo"
    local result = bar(nil)
    return result
end
return ____exports`, false, false},
		{"Hoisting Shorthand Property", `function foo() {
            return { bar }.bar;
        }
        let bar = "foobar";
        return foo();`, `"foobar"`, `local ____exports = {}
function ____exports.__main(self)
    local bar
    local function foo(self)
        return ({bar = bar}).bar
    end
    bar = "foobar"
    return foo(nil)
end
return ____exports`, false, false},
		{"Hoisting variable without initializer", `function foo() {
            return x;
        }
        let x: number | undefined;
        return foo();`, `nil`, `local ____exports = {}
function ____exports.__main(self)
    local x
    local function foo(self)
        return x
    end
    return foo(nil)
end
return ____exports`, false, false},
	})

	batchExpectModules(t, []moduleTestCase{
		{"Exported Let/Const Hoisting (\"let\")", `let bar: string;
        function setBar() { bar = foo; }
        export let foo = "foo";
        setBar();`, `{foo = "foo"}`, `local ____exports = {}
local bar
local function setBar(self)
    bar = ____exports.foo
end
____exports.foo = "foo"
setBar(nil)
return ____exports`, false, false},
		{"Exported Let/Const Hoisting (\"const\")", `let bar: string;
        function setBar() { bar = foo; }
        export const foo = "foo";
        setBar();`, `{foo = "foo"}`, `local ____exports = {}
local bar
local function setBar(self)
    bar = ____exports.foo
end
____exports.foo = "foo"
setBar(nil)
return ____exports`, false, false},
		{"Local Function Hoisting", `export const foo = bar();
        function bar() { return "bar"; }`, `{foo = "bar"}`, `local ____exports = {}
local bar
function bar(self)
    return "bar"
end
____exports.foo = bar(nil)
return ____exports`, false, false},
		{"Hoisting with synthetic source file node", `export const foo = bar();
        function bar() { return "bar"; }`, `{foo = "bar"}`, `local ____exports = {}
local bar
function bar(self)
    return "bar"
end
____exports.foo = bar(nil)
return ____exports`, false, false},
		{"Namespace Hoisting", `function bar() {
            return NS.foo;
        }
        namespace NS {
            export let foo = "foo";
        }
        export const foo = bar();`, `{foo = "foo"}`, `local ____exports = {}
local NS
local function bar(self)
    return NS.foo
end
NS = {}
do
    NS.foo = "foo"
end
____exports.foo = bar(nil)
return ____exports`, false, false},
		{"Exported Namespace Hoisting", `function bar() {
            return NS.foo;
        }
        export namespace NS {
            export let foo = "foo";
        }
        export const foo = bar();`, `{NS = {foo = "foo"}, foo = "foo"}`, `local ____exports = {}
local NS
local function bar(self)
    return ____exports.NS.foo
end
____exports.NS = {}
NS = ____exports.NS
do
    NS.foo = "foo"
end
____exports.foo = bar(nil)
return ____exports`, false, false},
		{"Nested Namespace Hoisting", `const Inner = 0;
        namespace Outer {
            export function bar() {
                return Inner.foo;
            }
            namespace Inner {
                export const foo = "foo";
            }
        }

        export const foo = Outer.bar();
        export { Inner };`, `{Inner = 0, foo = "foo"}`, `local ____exports = {}
local Inner = 0
local Outer = {}
do
    local Inner
    function Outer.bar(self)
        return Inner.foo
    end
    Inner = {}
    do
        Inner.foo = "foo"
    end
end
____exports.foo = Outer:bar()
____exports.Inner = Inner
return ____exports`, false, false},
		{"Class Hoisting", `function makeFoo() {
            return new Foo();
        }
        class Foo {
            public bar = "foo";
        }
        export const foo = makeFoo().bar;`, `{foo = "foo"}`, `local ____lualib = require("lualib_bundle")
local __TS__New = ____lualib.__TS__New
local __TS__Class = ____lualib.__TS__Class
local ____exports = {}
local Foo
local function makeFoo(self)
    return __TS__New(Foo)
end
Foo = __TS__Class()
Foo.name = "Foo"
function Foo.prototype.____constructor(self)
    self.bar = "foo"
end
____exports.foo = makeFoo(nil).bar
return ____exports`, false, false},
	})

	batchRunTests(t, []batchTestCase{
		{name: "Exported Function Hoisting", tsCode: `const foo = bar();
        export function bar() { return "bar"; }
        export const baz = foo;`, accessor: `mod["baz"]`, want: `"bar"`, refLua: `local ____exports = {}
function ____exports.bar(self)
    return "bar"
end
local foo = ____exports.bar(nil)
____exports.baz = foo
return ____exports`},
		{name: "Namespace Function Hoisting", tsCode: `
            let foo: string;
            namespace NS {
                foo = bar();
                function bar() { return "bar"; }
            }
        
export function __main() {return foo;}`, accessor: `mod.__main()`, want: `"bar"`, refLua: `local ____exports = {}
local foo
local NS = {}
do
    local bar
    function bar(self)
        return "bar"
    end
    foo = bar(nil)
end
function ____exports.__main(self)
    return foo
end
return ____exports`},
		{name: "Exported Namespace Function Hoisting", tsCode: `
            let foo: string;
            namespace NS {
                foo = bar();
                export function bar() { return "bar"; }
            }
        
export function __main() {return foo;}`, accessor: `mod.__main()`, want: `"bar"`, refLua: `local ____exports = {}
local foo
local NS = {}
do
    function NS.bar(self)
        return "bar"
    end
    foo = NS.bar(nil)
end
function ____exports.__main(self)
    return foo
end
return ____exports`},
		{name: "Import hoisting (named)", tsCode: `export const result = foo;
        import { foo } from "./module";`, accessor: `mod`, want: `{result = true}`, refLua: `local ____exports = {}
local ____module = require("module")
local foo = ____module.foo
____exports.result = foo
return ____exports`, extraFiles: map[string]string{"module.ts": `export const foo = true;`}},
		{name: "Import hoisting (namespace)", tsCode: `export const result = m.foo;
        import * as m from "./module";`, accessor: `mod`, want: `{result = true}`, refLua: `local ____exports = {}
local m = require("module")
____exports.result = m.foo
return ____exports`, extraFiles: map[string]string{"module.ts": `export const foo = true;`}},
		{name: "Import hoisting (side-effect)", tsCode: `export const result = (globalThis as any).result;
        import "./module";`, accessor: `mod`, want: `{result = true}`, refLua: `local ____exports = {}
require("module")
____exports.result = _G.result
return ____exports`, extraFiles: map[string]string{"module.ts": `(globalThis as any).result = true; export {};`}},
		{name: "Import hoisted before function", tsCode: `export let result: any;

        baz();
        function baz() {
            result = foo;
        }

        import { foo } from "./module";`, accessor: `mod`, want: `{result = true}`, refLua: `local ____exports = {}
local baz
local ____module = require("module")
local foo = ____module.foo
function baz(self)
    ____exports.result = foo
end
baz(nil)
return ____exports`, extraFiles: map[string]string{"module.ts": `export const foo = true;`}},
	})
}
