// Code generated by scripts/migrate from extern/tstl/test/unit/language-extensions/iterable.spec.ts. DO NOT EDIT.
package tstltest

import "testing"

func TestEval_Iterable(t *testing.T) {
	t.Parallel()

	batchExpectDiagnostics(t, []diagTestCase{
		{"LuaIterable with LuaMultiReturn value type invalid LuaIterable<LuaMultiReturn> without destructuring (\"for (const s of testIterable()) {}\")", "function", `function testIterable(this: void): LuaIterable<LuaMultiReturn<[string, {a: string}]>> {
        const strsArray = [["a1", {a: "a"}], ["b1", {a: "b"}], ["c1", {a: "c"}]];
        let i = 0;
        return (() => {
            const strs = strsArray[i++];
            if (strs) {
                return $multi(...strs);
            }
        }) as any;
    }
    
            for (const s of testIterable()) {}`, []int32{100024}, []string{`local ____exports = {}
function ____exports.__main(self)
    local function testIterable()
        local strsArray = {{"a1", {a = "a"}}, {"b1", {a = "b"}}, {"c1", {a = "c"}}}
        local i = 0
        return function()
            local ____i_0 = i
            i = ____i_0 + 1
            local strs = strsArray[____i_0 + 1]
            if strs then
                return table.unpack(strs)
            end
        end
    end
    for ____ in testIterable() do
    end
end
return ____exports`}},
		{"LuaIterable with LuaMultiReturn value type invalid LuaIterable<LuaMultiReturn> without destructuring (\"let s; for (s of testIterable()) {}\")", "function", `function testIterable(this: void): LuaIterable<LuaMultiReturn<[string, {a: string}]>> {
        const strsArray = [["a1", {a: "a"}], ["b1", {a: "b"}], ["c1", {a: "c"}]];
        let i = 0;
        return (() => {
            const strs = strsArray[i++];
            if (strs) {
                return $multi(...strs);
            }
        }) as any;
    }
    
            let s; for (s of testIterable()) {}`, []int32{100024}, []string{`local ____exports = {}
function ____exports.__main(self)
    local function testIterable()
        local strsArray = {{"a1", {a = "a"}}, {"b1", {a = "b"}}, {"c1", {a = "c"}}}
        local i = 0
        return function()
            local ____i_0 = i
            i = ____i_0 + 1
            local strs = strsArray[____i_0 + 1]
            if strs then
                return table.unpack(strs)
            end
        end
    end
    local s
    for ____ in testIterable() do
    end
end
return ____exports`}},
	}, WithLanguageExtensions())

	batchExpectCodegen(t, []codegenTestCase{
		{"LuaIterable with LuaMultiReturn value type invalid LuaIterable<LuaMultiReturn> without destructuring (\"for (const s of testIterable()) {}\")", "function", `function testIterable(this: void): LuaIterable<LuaMultiReturn<[string, {a: string}]>> {
        const strsArray = [["a1", {a: "a"}], ["b1", {a: "b"}], ["c1", {a: "c"}]];
        let i = 0;
        return (() => {
            const strs = strsArray[i++];
            if (strs) {
                return $multi(...strs);
            }
        }) as any;
    }
    
            for (const s of testIterable()) {}`, nil, nil, nil, nil},
		{"LuaIterable with LuaMultiReturn value type invalid LuaIterable<LuaMultiReturn> without destructuring (\"let s; for (s of testIterable()) {}\")", "function", `function testIterable(this: void): LuaIterable<LuaMultiReturn<[string, {a: string}]>> {
        const strsArray = [["a1", {a: "a"}], ["b1", {a: "b"}], ["c1", {a: "c"}]];
        let i = 0;
        return (() => {
            const strs = strsArray[i++];
            if (strs) {
                return $multi(...strs);
            }
        }) as any;
    }
    
            let s; for (s of testIterable()) {}`, nil, nil, nil, nil},
	}, WithLanguageExtensions())

	t.Run("simple LuaIterable const control variable", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function testIterable(this: void): LuaIterable<string> {
        const strs = ["a", "b", "c"];
        let i = 0;
        return (() => strs[i++]) as any;
    }
    
            const results: string[] = [];
            for (const s of testIterable()) {
                results.push(s);
            }
            return results;`, `{"a", "b", "c"}`, WithLanguageExtensions())
	})

	t.Run("simple LuaIterable let control variable", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function testIterable(this: void): LuaIterable<string> {
        const strs = ["a", "b", "c"];
        let i = 0;
        return (() => strs[i++]) as any;
    }
    
            const results: string[] = [];
            for (let s of testIterable()) {
                results.push(s);
            }
            return results;`, `{"a", "b", "c"}`, WithLanguageExtensions())
	})

	t.Run("simple LuaIterable external control variable", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function testIterable(this: void): LuaIterable<string> {
        const strs = ["a", "b", "c"];
        let i = 0;
        return (() => strs[i++]) as any;
    }
    
            const results: string[] = [];
            let s: string;
            for (s of testIterable()) {
                results.push(s);
            }
            return results;`, `{"a", "b", "c"}`, WithLanguageExtensions())
	})

	t.Run("simple LuaIterable function forward", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function testIterable(this: void): LuaIterable<string> {
        const strs = ["a", "b", "c"];
        let i = 0;
        return (() => strs[i++]) as any;
    }
    
            function forward() { return testIterable(); }
            const results: string[] = [];
            for (const s of forward()) {
                results.push(s);
            }
            return results;`, `{"a", "b", "c"}`, WithLanguageExtensions())
	})

	t.Run("simple LuaIterable function indirect forward", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function testIterable(this: void): LuaIterable<string> {
        const strs = ["a", "b", "c"];
        let i = 0;
        return (() => strs[i++]) as any;
    }
    
            function forward() { const iter = testIterable(); return iter; }
            const results: string[] = [];
            for (const s of forward()) {
                results.push(s);
            }
            return results;`, `{"a", "b", "c"}`, WithLanguageExtensions())
	})

	t.Run("simple LuaIterable arrow function forward", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function testIterable(this: void): LuaIterable<string> {
        const strs = ["a", "b", "c"];
        let i = 0;
        return (() => strs[i++]) as any;
    }
    
            const forward = () => testIterable();
            const results: string[] = [];
            for (const s of forward()) {
                results.push(s);
            }
            return results;`, `{"a", "b", "c"}`, WithLanguageExtensions())
	})

	t.Run("simple LuaIterable manual use", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function testIterable(this: void): LuaIterable<string> {
        const strs = ["a", "b", "c"];
        let i = 0;
        return (() => strs[i++]) as any;
    }
    
            const results: string[] = [];
            const iter = testIterable();
            while (true) {
                const val = iter();
                if (!val) {
                    break;
                }
                results.push(val);
            }
            return results;`, `{"a", "b", "c"}`, WithLanguageExtensions())
	})

	t.Run("LuaIterable using state const control variable", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function iterator(this: void, strs: string[], lastStr: string) {
        return strs[strs.indexOf(lastStr) + 1];
    }
    const testIterable = (() => $multi(iterator, ["a", "b", "c"], "")) as (() => LuaIterable<string, string[]>);
    
            const results: string[] = [];
            for (const s of testIterable()) {
                results.push(s);
            }
            return results;`, `{"a", "b", "c"}`, WithLanguageExtensions())
	})

	t.Run("LuaIterable using state let control variable", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function iterator(this: void, strs: string[], lastStr: string) {
        return strs[strs.indexOf(lastStr) + 1];
    }
    const testIterable = (() => $multi(iterator, ["a", "b", "c"], "")) as (() => LuaIterable<string, string[]>);
    
            const results: string[] = [];
            for (let s of testIterable()) {
                results.push(s);
            }
            return results;`, `{"a", "b", "c"}`, WithLanguageExtensions())
	})

	t.Run("LuaIterable using state external control variable", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function iterator(this: void, strs: string[], lastStr: string) {
        return strs[strs.indexOf(lastStr) + 1];
    }
    const testIterable = (() => $multi(iterator, ["a", "b", "c"], "")) as (() => LuaIterable<string, string[]>);
    
            const results: string[] = [];
            let s: string;
            for (s of testIterable()) {
                results.push(s);
            }
            return results;`, `{"a", "b", "c"}`, WithLanguageExtensions())
	})

	t.Run("LuaIterable using state function forward", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function iterator(this: void, strs: string[], lastStr: string) {
        return strs[strs.indexOf(lastStr) + 1];
    }
    const testIterable = (() => $multi(iterator, ["a", "b", "c"], "")) as (() => LuaIterable<string, string[]>);
    
            function forward() { return testIterable(); }
            const results: string[] = [];
            for (const s of forward()) {
                results.push(s);
            }
            return results;`, `{"a", "b", "c"}`, WithLanguageExtensions())
	})

	t.Run("LuaIterable using state function indirect forward", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function iterator(this: void, strs: string[], lastStr: string) {
        return strs[strs.indexOf(lastStr) + 1];
    }
    const testIterable = (() => $multi(iterator, ["a", "b", "c"], "")) as (() => LuaIterable<string, string[]>);
    
            function forward() { const iter = testIterable(); return iter; }
            const results: string[] = [];
            for (const s of forward()) {
                results.push(s);
            }
            return results;`, `{"a", "b", "c"}`, WithLanguageExtensions())
	})

	t.Run("LuaIterable using state arrow function forward", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function iterator(this: void, strs: string[], lastStr: string) {
        return strs[strs.indexOf(lastStr) + 1];
    }
    const testIterable = (() => $multi(iterator, ["a", "b", "c"], "")) as (() => LuaIterable<string, string[]>);
    
            const forward = () => testIterable();
            const results: string[] = [];
            for (const s of forward()) {
                results.push(s);
            }
            return results;`, `{"a", "b", "c"}`, WithLanguageExtensions())
	})

	t.Run("LuaIterable using state manual use", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function iterator(this: void, strs: string[], lastStr: string) {
        return strs[strs.indexOf(lastStr) + 1];
    }
    const testIterable = (() => $multi(iterator, ["a", "b", "c"], "")) as (() => LuaIterable<string, string[]>);
    
            const results: string[] = [];
            let [iter, state, val] = testIterable();
            while (true) {
                val = iter(state, val);
                if (!val) {
                    break;
                }
                results.push(val);
            }
            return results;`, `{"a", "b", "c"}`, WithLanguageExtensions())
	})

	t.Run("LuaIterable with array value type basic destructuring", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function testIterable(this: void): LuaIterable<string[]> {
        const strsArray = [["a1", "a2"], ["b1", "b2"], ["c1", "c2"]];
        let i = 0;
        return (() => strsArray[i++]) as any;
    }
    
            const results = [];
            for (const [x, y] of testIterable()) {
                results.push([x, y]);
            }
            return results;`, `{{"a1", "a2"}, {"b1", "b2"}, {"c1", "c2"}}`, WithLanguageExtensions())
	})

	t.Run("LuaIterable with array value type destructure with external control variable", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function testIterable(this: void): LuaIterable<string[]> {
        const strsArray = [["a1", "a2"], ["b1", "b2"], ["c1", "c2"]];
        let i = 0;
        return (() => strsArray[i++]) as any;
    }
    
            const results = []
            let x: string, y: string;
            for ([x, y] of testIterable()) {
                results.push([x, y]);
            }
            return results;`, `{{"a1", "a2"}, {"b1", "b2"}, {"c1", "c2"}}`, WithLanguageExtensions())
	})

	t.Run("LuaIterable with array value type destructure with function forward", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function testIterable(this: void): LuaIterable<string[]> {
        const strsArray = [["a1", "a2"], ["b1", "b2"], ["c1", "c2"]];
        let i = 0;
        return (() => strsArray[i++]) as any;
    }
    
            function forward() { return testIterable(); }
            const results: Array<string[]> = [];
            for (const [x, y] of forward()) {
                results.push([x, y]);
            }
            return results;`, `{{"a1", "a2"}, {"b1", "b2"}, {"c1", "c2"}}`, WithLanguageExtensions())
	})

	t.Run("LuaIterable with array value type destructure with function indirect forward", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function testIterable(this: void): LuaIterable<string[]> {
        const strsArray = [["a1", "a2"], ["b1", "b2"], ["c1", "c2"]];
        let i = 0;
        return (() => strsArray[i++]) as any;
    }
    
            function forward() { const iter = testIterable(); return iter; }
            const results: Array<string[]> = [];
            for (const [x, y] of forward()) {
                results.push([x, y]);
            }
            return results;`, `{{"a1", "a2"}, {"b1", "b2"}, {"c1", "c2"}}`, WithLanguageExtensions())
	})

	t.Run("LuaIterable with array value type destructure arrow function forward", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function testIterable(this: void): LuaIterable<string[]> {
        const strsArray = [["a1", "a2"], ["b1", "b2"], ["c1", "c2"]];
        let i = 0;
        return (() => strsArray[i++]) as any;
    }
    
            const forward = () => testIterable();
            const results: Array<string[]> = [];
            for (const [x, y] of forward()) {
                results.push([x, y]);
            }
            return results;`, `{{"a1", "a2"}, {"b1", "b2"}, {"c1", "c2"}}`, WithLanguageExtensions())
	})

	t.Run("LuaIterable with array value type manual use", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function testIterable(this: void): LuaIterable<string[]> {
        const strsArray = [["a1", "a2"], ["b1", "b2"], ["c1", "c2"]];
        let i = 0;
        return (() => strsArray[i++]) as any;
    }
    
            const results: Array<string[]> = [];
            const iter = testIterable();
            while (true) {
                const val = iter();
                if (!val) {
                    break;
                }
                results.push(val);
            }
            return results;`, `{{"a1", "a2"}, {"b1", "b2"}, {"c1", "c2"}}`, WithLanguageExtensions())
	})

	t.Run("LuaIterable with LuaMultiReturn value type basic destructuring", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function testIterable(this: void): LuaIterable<LuaMultiReturn<[string, {a: string}]>> {
        const strsArray = [["a1", {a: "a"}], ["b1", {a: "b"}], ["c1", {a: "c"}]];
        let i = 0;
        return (() => {
            const strs = strsArray[i++];
            if (strs) {
                return $multi(...strs);
            }
        }) as any;
    }
    
            const results = [];
            for (const [x, y] of testIterable()) {
                results.push([x, y]);
            }
            return results;`, `{{"a1", {a = "a"}}, {"b1", {a = "b"}}, {"c1", {a = "c"}}}`, WithLanguageExtensions())
	})

	t.Run("LuaIterable with LuaMultiReturn value type destructure with external control variable", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function testIterable(this: void): LuaIterable<LuaMultiReturn<[string, {a: string}]>> {
        const strsArray = [["a1", {a: "a"}], ["b1", {a: "b"}], ["c1", {a: "c"}]];
        let i = 0;
        return (() => {
            const strs = strsArray[i++];
            if (strs) {
                return $multi(...strs);
            }
        }) as any;
    }
    
            const results = [];
            let x: string, y: any;
            for ([x, y] of testIterable()) {
                results.push([x, y]);
            }
            return results;`, `{{"a1", {a = "a"}}, {"b1", {a = "b"}}, {"c1", {a = "c"}}}`, WithLanguageExtensions())
	})

	t.Run("LuaIterable with LuaMultiReturn value type destructure with function forward", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function testIterable(this: void): LuaIterable<LuaMultiReturn<[string, {a: string}]>> {
        const strsArray = [["a1", {a: "a"}], ["b1", {a: "b"}], ["c1", {a: "c"}]];
        let i = 0;
        return (() => {
            const strs = strsArray[i++];
            if (strs) {
                return $multi(...strs);
            }
        }) as any;
    }
    
            function forward() { return testIterable(); }
            const results = [];
            for (const [x, y] of forward()) {
                results.push([x, y]);
            }
            return results;`, `{{"a1", {a = "a"}}, {"b1", {a = "b"}}, {"c1", {a = "c"}}}`, WithLanguageExtensions())
	})

	t.Run("LuaIterable with LuaMultiReturn value type destructure with function indirect forward", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function testIterable(this: void): LuaIterable<LuaMultiReturn<[string, {a: string}]>> {
        const strsArray = [["a1", {a: "a"}], ["b1", {a: "b"}], ["c1", {a: "c"}]];
        let i = 0;
        return (() => {
            const strs = strsArray[i++];
            if (strs) {
                return $multi(...strs);
            }
        }) as any;
    }
    
            function forward() { const iter = testIterable(); return iter; }
            const results = [];
            for (const [x, y] of forward()) {
                results.push([x, y]);
            }
            return results;`, `{{"a1", {a = "a"}}, {"b1", {a = "b"}}, {"c1", {a = "c"}}}`, WithLanguageExtensions())
	})

	t.Run("LuaIterable with LuaMultiReturn value type destructure arrow function forward", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function testIterable(this: void): LuaIterable<LuaMultiReturn<[string, {a: string}]>> {
        const strsArray = [["a1", {a: "a"}], ["b1", {a: "b"}], ["c1", {a: "c"}]];
        let i = 0;
        return (() => {
            const strs = strsArray[i++];
            if (strs) {
                return $multi(...strs);
            }
        }) as any;
    }
    
            const forward = () => testIterable();
            const results = [];
            for (const [x, y] of forward()) {
                results.push([x, y]);
            }
            return results;`, `{{"a1", {a = "a"}}, {"b1", {a = "b"}}, {"c1", {a = "c"}}}`, WithLanguageExtensions())
	})

	t.Run("LuaIterable with LuaMultiReturn value type destructure manual use", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function testIterable(this: void): LuaIterable<LuaMultiReturn<[string, {a: string}]>> {
        const strsArray = [["a1", {a: "a"}], ["b1", {a: "b"}], ["c1", {a: "c"}]];
        let i = 0;
        return (() => {
            const strs = strsArray[i++];
            if (strs) {
                return $multi(...strs);
            }
        }) as any;
    }
    
            const results = [];
            const iter = testIterable();
            while (true) {
                const [x, y] = iter();
                if (!x) {
                    break;
                }
                results.push([x, y]);
            }
            return results;`, `{{"a1", {a = "a"}}, {"b1", {a = "b"}}, {"c1", {a = "c"}}}`, WithLanguageExtensions())
	})

	t.Run("LuaIterable with LuaMultiReturn value type nested destructuring", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function testIterable(this: void): LuaIterable<LuaMultiReturn<[string, {a: string}]>> {
        const strsArray = [["a1", {a: "a"}], ["b1", {a: "b"}], ["c1", {a: "c"}]];
        let i = 0;
        return (() => {
            const strs = strsArray[i++];
            if (strs) {
                return $multi(...strs);
            }
        }) as any;
    }
    
            const results = [];
            for (const [x, {a}] of testIterable()) {
                results.push([x, a]);
            }
            return results;`, `{{"a1", "a"}, {"b1", "b"}, {"c1", "c"}}`, WithLanguageExtensions())
	})

	t.Run("LuaIterable property basic usage", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `class IterableTester {
        public strs = ["a", "b", "c"];

        public get values(): LuaIterable<string> {
            let i = 0;
            return (() => this.strs[i++]) as any;
        }
    }
    const tester = new IterableTester();
    
            const results: string[] = [];
            for (const s of tester.values) {
                results.push(s);
            }
            return results;`, `{"a", "b", "c"}`, WithLanguageExtensions())
	})

	t.Run("LuaIterable property external control variable", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `class IterableTester {
        public strs = ["a", "b", "c"];

        public get values(): LuaIterable<string> {
            let i = 0;
            return (() => this.strs[i++]) as any;
        }
    }
    const tester = new IterableTester();
    
            const results: string[] = [];
            let s: string;
            for (s of tester.values) {
                results.push(s);
            }
            return results;`, `{"a", "b", "c"}`, WithLanguageExtensions())
	})

	t.Run("LuaIterable property function forward", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `class IterableTester {
        public strs = ["a", "b", "c"];

        public get values(): LuaIterable<string> {
            let i = 0;
            return (() => this.strs[i++]) as any;
        }
    }
    const tester = new IterableTester();
    
            function forward() { return tester.values; }
            const results: string[] = [];
            for (const s of forward()) {
                results.push(s);
            }
            return results;`, `{"a", "b", "c"}`, WithLanguageExtensions())
	})

	t.Run("LuaIterable property function indirect forward", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `class IterableTester {
        public strs = ["a", "b", "c"];

        public get values(): LuaIterable<string> {
            let i = 0;
            return (() => this.strs[i++]) as any;
        }
    }
    const tester = new IterableTester();
    
            function forward() { const iter = tester.values; return iter; }
            const results: string[] = [];
            for (const s of forward()) {
                results.push(s);
            }
            return results;`, `{"a", "b", "c"}`, WithLanguageExtensions())
	})

	t.Run("LuaIterable property arrow function forward", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `class IterableTester {
        public strs = ["a", "b", "c"];

        public get values(): LuaIterable<string> {
            let i = 0;
            return (() => this.strs[i++]) as any;
        }
    }
    const tester = new IterableTester();
    
            const forward = () => tester.values;
            const results: string[] = [];
            for (const s of forward()) {
                results.push(s);
            }
            return results;`, `{"a", "b", "c"}`, WithLanguageExtensions())
	})

	t.Run("LuaIterable property manual use", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `class IterableTester {
        public strs = ["a", "b", "c"];

        public get values(): LuaIterable<string> {
            let i = 0;
            return (() => this.strs[i++]) as any;
        }
    }
    const tester = new IterableTester();
    
            const results: string[] = [];
            const iter = tester.values;
            while (true) {
                const val = iter();
                if (!val) {
                    break;
                }
                results.push(val);
            }
            return results;`, `{"a", "b", "c"}`, WithLanguageExtensions())
	})
}
