// Code generated by scripts/migrate from extern/tstl/test/unit/builtins/map.spec.ts. DO NOT EDIT.
package tstltest

import "testing"

func TestEval_Map(t *testing.T) {
	t.Parallel()

	batchExpectFunctions(t, []funcTestCase{
		{"map constructor", `let mymap = new Map();
        return mymap.size;`, `0`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local mymap = __TS__New(Map)
    return mymap.size
end
return ____exports`, false, false},
		{"map iterable constructor", `let mymap = new Map([["a", "c"],["b", "d"]]);
         return mymap.has("a") && mymap.has("b");`, `true`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local mymap = __TS__New(Map, {{"a", "c"}, {"b", "d"}})
    return mymap:has("a") and mymap:has("b")
end
return ____exports`, false, false},
		{"map iterable constructor map", `let mymap = new Map(new Map([["a", "c"],["b", "d"]]));
        return mymap.has("a") && mymap.has("b");`, `true`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local mymap = __TS__New(
        Map,
        __TS__New(Map, {{"a", "c"}, {"b", "d"}})
    )
    return mymap:has("a") and mymap:has("b")
end
return ____exports`, false, false},
		{"map delete", `let mymap = new Map([["a", "c"],["b", "d"]]);
        mymap.delete("a");
        return mymap.has("b") && !mymap.has("a");`, `true`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local mymap = __TS__New(Map, {{"a", "c"}, {"b", "d"}})
    mymap:delete("a")
    return mymap:has("b") and not mymap:has("a")
end
return ____exports`, false, false},
		{"map entries", `let mymap = new Map([[5, 2],[6, 3],[7, 4]]);
        let count = 0;
        for (const [key, value] of mymap.entries()) { count += key + value; }
        return count;`, `27`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local __TS__Iterator = ____lualib.__TS__Iterator
local ____exports = {}
function ____exports.__main(self)
    local mymap = __TS__New(Map, {{5, 2}, {6, 3}, {7, 4}})
    local count = 0
    for ____, ____value in __TS__Iterator(mymap:entries()) do
        local key = ____value[1]
        local value = ____value[2]
        count = count + (key + value)
    end
    return count
end
return ____exports`, false, false},
		{"map foreach", `let mymap = new Map([["a", 2],["b", 3],["c", 4]]);
        let count = 0;
        mymap.forEach(i => count += i);
        return count;`, `9`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local mymap = __TS__New(Map, {{"a", 2}, {"b", 3}, {"c", 4}})
    local count = 0
    mymap:forEach(function(____, i)
        count = count + i
        return count
    end)
    return count
end
return ____exports`, false, false},
		{"map foreach keys", `let mymap = new Map([[5, 2],[6, 3],[7, 4]]);
        let count = 0;
        mymap.forEach((value, key) => { count += key; });
        return count;`, `18`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local mymap = __TS__New(Map, {{5, 2}, {6, 3}, {7, 4}})
    local count = 0
    mymap:forEach(function(____, value, key)
        count = count + key
    end)
    return count
end
return ____exports`, false, false},
		{"map get", `let mymap = new Map([["a", "c"],["b", "d"]]);
        return mymap.get("a");`, `"c"`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local mymap = __TS__New(Map, {{"a", "c"}, {"b", "d"}})
    return mymap:get("a")
end
return ____exports`, false, false},
		{"map get missing", `let mymap = new Map([["a", "c"],["b", "d"]]);
        return mymap.get("c");`, `nil`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local mymap = __TS__New(Map, {{"a", "c"}, {"b", "d"}})
    return mymap:get("c")
end
return ____exports`, false, false},
		{"map has", `let mymap = new Map([["a", "c"]]);
        return mymap.has("a");`, `true`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local mymap = __TS__New(Map, {{"a", "c"}})
    return mymap:has("a")
end
return ____exports`, false, false},
		{"map has false", `let mymap = new Map();
        return mymap.has("a");`, `false`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local mymap = __TS__New(Map)
    return mymap:has("a")
end
return ____exports`, false, false},
		{"map (\"[[\\\"a\\\", null]]\") has null", `let mymap = new Map([["a", null]]);
        return mymap.has("a");`, `true`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local mymap = __TS__New(Map, {{"a", nil}})
    return mymap:has("a")
end
return ____exports`, false, false},
		{"map (\"[[\\\"b\\\", \\\"c\\\"], [\\\"a\\\", null]]\") has null", `let mymap = new Map([["b", "c"], ["a", null]]);
        return mymap.has("a");`, `true`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local mymap = __TS__New(Map, {{"b", "c"}, {"a", nil}})
    return mymap:has("a")
end
return ____exports`, false, false},
		{"map (\"[[\\\"a\\\", null], [\\\"b\\\", \\\"c\\\"]]\") has null", `let mymap = new Map([["a", null], ["b", "c"]]);
        return mymap.has("a");`, `true`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local mymap = __TS__New(Map, {{"a", nil}, {"b", "c"}})
    return mymap:has("a")
end
return ____exports`, false, false},
		{"map (\"[[\\\"b\\\", \\\"c\\\"], [\\\"a\\\", null], [\\\"x\\\", \\\"y\\\"]]\") has null", `let mymap = new Map([["b", "c"], ["a", null], ["x", "y"]]);
        return mymap.has("a");`, `true`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local mymap = __TS__New(Map, {{"b", "c"}, {"a", nil}, {"x", "y"}})
    return mymap:has("a")
end
return ____exports`, false, false},
		{"map (\"[[\\\"a\\\", undefined]]\") has undefined", `let mymap = new Map([["a", undefined]]);
        return mymap.has("a");`, `true`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local mymap = __TS__New(Map, {{"a", nil}})
    return mymap:has("a")
end
return ____exports`, false, false},
		{"map (\"[[\\\"b\\\", \\\"c\\\"], [\\\"a\\\", undefined]]\") has undefined", `let mymap = new Map([["b", "c"], ["a", undefined]]);
        return mymap.has("a");`, `true`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local mymap = __TS__New(Map, {{"b", "c"}, {"a", nil}})
    return mymap:has("a")
end
return ____exports`, false, false},
		{"map (\"[[\\\"a\\\", undefined], [\\\"b\\\", \\\"c\\\"]]\") has undefined", `let mymap = new Map([["a", undefined], ["b", "c"]]);
        return mymap.has("a");`, `true`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local mymap = __TS__New(Map, {{"a", nil}, {"b", "c"}})
    return mymap:has("a")
end
return ____exports`, false, false},
		{"map (\"[[\\\"b\\\", \\\"c\\\"], [\\\"a\\\", undefined], [\\\"x\\\", \\\"y\\\"]]\") has undefined", `let mymap = new Map([["b", "c"], ["a", undefined], ["x", "y"]]);
        return mymap.has("a");`, `true`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local mymap = __TS__New(Map, {{"b", "c"}, {"a", nil}, {"x", "y"}})
    return mymap:has("a")
end
return ____exports`, false, false},
		{"map keys", `let mymap = new Map([[5, 2],[6, 3],[7, 4]]);
        let count = 0;
        for (const key of mymap.keys()) { count += key; }
        return count;`, `18`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local __TS__Iterator = ____lualib.__TS__Iterator
local ____exports = {}
function ____exports.__main(self)
    local mymap = __TS__New(Map, {{5, 2}, {6, 3}, {7, 4}})
    local count = 0
    for ____, key in __TS__Iterator(mymap:keys()) do
        count = count + key
    end
    return count
end
return ____exports`, false, false},
		{"map set", `let mymap = new Map(); mymap.set("a", 5);return mymap.has("a");`, `true`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local mymap = __TS__New(Map)
    mymap:set("a", 5)
    return mymap:has("a")
end
return ____exports`, false, false},
		{"map set", `let mymap = new Map(); mymap.set("a", 5);return mymap.get("a")`, `5`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local mymap = __TS__New(Map)
    mymap:set("a", 5)
    return mymap:get("a")
end
return ____exports`, false, false},
		{"map values", `let mymap = new Map([[5, 2],[6, 3],[7, 4]]);
        let count = 0;
        for (const value of mymap.values()) { count += value; }
        return count;`, `9`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local __TS__Iterator = ____lualib.__TS__Iterator
local ____exports = {}
function ____exports.__main(self)
    local mymap = __TS__New(Map, {{5, 2}, {6, 3}, {7, 4}})
    local count = 0
    for ____, value in __TS__Iterator(mymap:values()) do
        count = count + value
    end
    return count
end
return ____exports`, false, false},
		{"map size", `let m = new Map(); return m.size;`, `0`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local m = __TS__New(Map)
    return m.size
end
return ____exports`, false, false},
		{"map size", `let m = new Map(); m.set(1,3); return m.size;`, `1`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local m = __TS__New(Map)
    m:set(1, 3)
    return m.size
end
return ____exports`, false, false},
		{"map size", `let m = new Map([[1,2],[3,4]]); return m.size;`, `2`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local m = __TS__New(Map, {{1, 2}, {3, 4}})
    return m.size
end
return ____exports`, false, false},
		{"map size", `let m = new Map([[1,2],[3,4]]); m.clear(); return m.size;`, `0`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local m = __TS__New(Map, {{1, 2}, {3, 4}})
    m:clear()
    return m.size
end
return ____exports`, false, false},
		{"map size", `let m = new Map([[1,2],[3,4]]); m.delete(3); return m.size;`, `1`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local m = __TS__New(Map, {{1, 2}, {3, 4}})
    m:delete(3)
    return m.size
end
return ____exports`, false, false},
		{"map.entries() preserves insertion order", `const mymap = new Map();

            mymap.set("x", 1);
            mymap.set("a", 2);
            mymap.set(4, 3);
            mymap.set("b", 6);
            mymap.set(1, 4);
            mymap.set("a", 5);

            mymap.delete("b");

            return [...mymap.entries()];`, `{{"x", 1}, {"a", 5}, {4, 3}, {1, 4}}`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local __TS__Spread = ____lualib.__TS__Spread
local ____exports = {}
function ____exports.__main(self)
    local mymap = __TS__New(Map)
    mymap:set("x", 1)
    mymap:set("a", 2)
    mymap:set(4, 3)
    mymap:set("b", 6)
    mymap:set(1, 4)
    mymap:set("a", 5)
    mymap:delete("b")
    return {__TS__Spread(mymap:entries())}
end
return ____exports`, false, false},
		{"map.entries() preserves insertion order", `const mymap = new Map();

            mymap.set("x", 1);
            mymap.set("a", 2);
            mymap.set(4, 3);

            mymap.delete(4);

            return [...mymap.entries()];`, `{{"x", 1}, {"a", 2}}`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local __TS__Spread = ____lualib.__TS__Spread
local ____exports = {}
function ____exports.__main(self)
    local mymap = __TS__New(Map)
    mymap:set("x", 1)
    mymap:set("a", 2)
    mymap:set(4, 3)
    mymap:delete(4)
    return {__TS__Spread(mymap:entries())}
end
return ____exports`, false, false},
		{"map.entries() preserves insertion order", `const mymap = new Map();

            mymap.set("x", 1);
            mymap.set("a", 2);
            mymap.set(4, 3);

            mymap.delete("x");

            return [...mymap.entries()];`, `{{"a", 2}, {4, 3}}`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local __TS__Spread = ____lualib.__TS__Spread
local ____exports = {}
function ____exports.__main(self)
    local mymap = __TS__New(Map)
    mymap:set("x", 1)
    mymap:set("a", 2)
    mymap:set(4, 3)
    mymap:delete("x")
    return {__TS__Spread(mymap:entries())}
end
return ____exports`, false, false},
		{"map.entries() preserves insertion order", `const mymap = new Map();

            mymap.set("x", 1);
            mymap.set("a", 2);

            mymap.delete("a");
            mymap.delete("x");

            return [...mymap.entries()];`, `{}`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local __TS__Spread = ____lualib.__TS__Spread
local ____exports = {}
function ____exports.__main(self)
    local mymap = __TS__New(Map)
    mymap:set("x", 1)
    mymap:set("a", 2)
    mymap:delete("a")
    mymap:delete("x")
    return {__TS__Spread(mymap:entries())}
end
return ____exports`, false, false},
		{"map.keys() preserves insertion order", `const mymap = new Map();

            mymap.set("x", 1);
            mymap.set("a", 2);
            mymap.set(4, 3);
            mymap.set("b", 6);
            mymap.set(1, 4);
            mymap.set("a", 5);

            mymap.delete("b");

            return [...mymap.keys()];`, `{"x", "a", 4, 1}`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local __TS__Spread = ____lualib.__TS__Spread
local ____exports = {}
function ____exports.__main(self)
    local mymap = __TS__New(Map)
    mymap:set("x", 1)
    mymap:set("a", 2)
    mymap:set(4, 3)
    mymap:set("b", 6)
    mymap:set(1, 4)
    mymap:set("a", 5)
    mymap:delete("b")
    return {__TS__Spread(mymap:keys())}
end
return ____exports`, false, false},
		{"map.keys() preserves insertion order", `const mymap = new Map();

            mymap.set("x", 1);
            mymap.set("a", 2);
            mymap.set(4, 3);

            mymap.delete(4);

            return [...mymap.keys()];`, `{"x", "a"}`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local __TS__Spread = ____lualib.__TS__Spread
local ____exports = {}
function ____exports.__main(self)
    local mymap = __TS__New(Map)
    mymap:set("x", 1)
    mymap:set("a", 2)
    mymap:set(4, 3)
    mymap:delete(4)
    return {__TS__Spread(mymap:keys())}
end
return ____exports`, false, false},
		{"map.keys() preserves insertion order", `const mymap = new Map();

            mymap.set("x", 1);
            mymap.set("a", 2);
            mymap.set(4, 3);

            mymap.delete("x");

            return [...mymap.keys()];`, `{"a", 4}`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local __TS__Spread = ____lualib.__TS__Spread
local ____exports = {}
function ____exports.__main(self)
    local mymap = __TS__New(Map)
    mymap:set("x", 1)
    mymap:set("a", 2)
    mymap:set(4, 3)
    mymap:delete("x")
    return {__TS__Spread(mymap:keys())}
end
return ____exports`, false, false},
		{"map.keys() preserves insertion order", `const mymap = new Map();

            mymap.set("x", 1);
            mymap.set("a", 2);

            mymap.delete("a");
            mymap.delete("x");

            return [...mymap.keys()];`, `{}`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local __TS__Spread = ____lualib.__TS__Spread
local ____exports = {}
function ____exports.__main(self)
    local mymap = __TS__New(Map)
    mymap:set("x", 1)
    mymap:set("a", 2)
    mymap:delete("a")
    mymap:delete("x")
    return {__TS__Spread(mymap:keys())}
end
return ____exports`, false, false},
		{"map.values() preserves insertion order", `const mymap = new Map();

            mymap.set("x", 1);
            mymap.set("a", 2);
            mymap.set(4, 3);
            mymap.set("b", 6);
            mymap.set(1, 4);
            mymap.set("a", 5);

            mymap.delete("b");

            return [...mymap.values()];`, `{1, 5, 3, 4}`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local __TS__Spread = ____lualib.__TS__Spread
local ____exports = {}
function ____exports.__main(self)
    local mymap = __TS__New(Map)
    mymap:set("x", 1)
    mymap:set("a", 2)
    mymap:set(4, 3)
    mymap:set("b", 6)
    mymap:set(1, 4)
    mymap:set("a", 5)
    mymap:delete("b")
    return {__TS__Spread(mymap:values())}
end
return ____exports`, false, false},
		{"map.values() preserves insertion order", `const mymap = new Map();

            mymap.set("x", 1);
            mymap.set("a", 2);
            mymap.set(4, 3);

            mymap.delete(4);

            return [...mymap.values()];`, `{1, 2}`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local __TS__Spread = ____lualib.__TS__Spread
local ____exports = {}
function ____exports.__main(self)
    local mymap = __TS__New(Map)
    mymap:set("x", 1)
    mymap:set("a", 2)
    mymap:set(4, 3)
    mymap:delete(4)
    return {__TS__Spread(mymap:values())}
end
return ____exports`, false, false},
		{"map.values() preserves insertion order", `const mymap = new Map();

            mymap.set("x", 1);
            mymap.set("a", 2);
            mymap.set(4, 3);

            mymap.delete("x");

            return [...mymap.values()];`, `{2, 3}`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local __TS__Spread = ____lualib.__TS__Spread
local ____exports = {}
function ____exports.__main(self)
    local mymap = __TS__New(Map)
    mymap:set("x", 1)
    mymap:set("a", 2)
    mymap:set(4, 3)
    mymap:delete("x")
    return {__TS__Spread(mymap:values())}
end
return ____exports`, false, false},
		{"map.values() preserves insertion order", `const mymap = new Map();

            mymap.set("x", 1);
            mymap.set("a", 2);

            mymap.delete("a");
            mymap.delete("x");

            return [...mymap.values()];`, `{}`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local __TS__Spread = ____lualib.__TS__Spread
local ____exports = {}
function ____exports.__main(self)
    local mymap = __TS__New(Map)
    mymap:set("x", 1)
    mymap:set("a", 2)
    mymap:delete("a")
    mymap:delete("x")
    return {__TS__Spread(mymap:values())}
end
return ____exports`, false, false},
		{"map.entries() handles mutation", `const map = new Map<number, string>([[1, "a"], [2, "b"]]);
            const iter = map.entries();
            map.delete(1);
            return iter.next().value;`, `{2, "b"}`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local map = __TS__New(Map, {{1, "a"}, {2, "b"}})
    local iter = map:entries()
    map:delete(1)
    return iter:next().value
end
return ____exports`, false, false},
		{"map.entries() handles mutation", `const map = new Map<number, string>([[1, "a"], [2, "b"], [3, "c"]]);
            const iter = map.entries();
            iter.next(); // 1
            map.delete(2);
            map.set(4, "d");
            const results: IteratorResult<any>[] = [];
            let r = iter.next();
            while (!r.done) { results.push({ done: r.done, value: r.value }); r = iter.next(); }
            return results;`, `{{done = false, value = {3, "c"}}, {done = false, value = {4, "d"}}}`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local map = __TS__New(Map, {{1, "a"}, {2, "b"}, {3, "c"}})
    local iter = map:entries()
    iter:next()
    map:delete(2)
    map:set(4, "d")
    local results = {}
    local r = iter:next()
    while not r.done do
        results[#results + 1] = {done = r.done, value = r.value}
        r = iter:next()
    end
    return results
end
return ____exports`, false, false},
		{"map.entries() handles mutation", `const map = new Map<number, string>([[1, "a"], [2, "b"]]);
            const iter = map.entries();
            const results: boolean[] = [];
            results.push(iter.next().done!);
            results.push(iter.next().done!);
            results.push(iter.next().done!); // should be done
            results.push(iter.next().done!); // should still be done, not restart
            return results;`, `{false, false, true, true}`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local map = __TS__New(Map, {{1, "a"}, {2, "b"}})
    local iter = map:entries()
    local results = {}
    results[#results + 1] = iter:next().done
    results[#results + 1] = iter:next().done
    results[#results + 1] = iter:next().done
    results[#results + 1] = iter:next().done
    return results
end
return ____exports`, false, false},
		{"map.keys() handles mutation", `const map = new Map<number, string>([[1, "a"], [2, "b"]]);
            const iter = map.keys();
            map.delete(1);
            return iter.next().value;`, `2`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local map = __TS__New(Map, {{1, "a"}, {2, "b"}})
    local iter = map:keys()
    map:delete(1)
    return iter:next().value
end
return ____exports`, false, false},
		{"map.keys() handles mutation", `const map = new Map<number, string>([[1, "a"], [2, "b"], [3, "c"]]);
            const iter = map.keys();
            iter.next(); // 1
            map.delete(2);
            map.set(4, "d");
            const results: IteratorResult<any>[] = [];
            let r = iter.next();
            while (!r.done) { results.push({ done: r.done, value: r.value }); r = iter.next(); }
            return results;`, `{{done = false, value = 3}, {done = false, value = 4}}`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local map = __TS__New(Map, {{1, "a"}, {2, "b"}, {3, "c"}})
    local iter = map:keys()
    iter:next()
    map:delete(2)
    map:set(4, "d")
    local results = {}
    local r = iter:next()
    while not r.done do
        results[#results + 1] = {done = r.done, value = r.value}
        r = iter:next()
    end
    return results
end
return ____exports`, false, false},
		{"map.keys() handles mutation", `const map = new Map<number, string>([[1, "a"], [2, "b"]]);
            const iter = map.keys();
            const results: boolean[] = [];
            results.push(iter.next().done!);
            results.push(iter.next().done!);
            results.push(iter.next().done!); // should be done
            results.push(iter.next().done!); // should still be done, not restart
            return results;`, `{false, false, true, true}`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local map = __TS__New(Map, {{1, "a"}, {2, "b"}})
    local iter = map:keys()
    local results = {}
    results[#results + 1] = iter:next().done
    results[#results + 1] = iter:next().done
    results[#results + 1] = iter:next().done
    results[#results + 1] = iter:next().done
    return results
end
return ____exports`, false, false},
		{"map.values() handles mutation", `const map = new Map<number, string>([[1, "a"], [2, "b"]]);
            const iter = map.values();
            map.delete(1);
            return iter.next().value;`, `"b"`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local map = __TS__New(Map, {{1, "a"}, {2, "b"}})
    local iter = map:values()
    map:delete(1)
    return iter:next().value
end
return ____exports`, false, false},
		{"map.values() handles mutation", `const map = new Map<number, string>([[1, "a"], [2, "b"], [3, "c"]]);
            const iter = map.values();
            iter.next(); // 1
            map.delete(2);
            map.set(4, "d");
            const results: IteratorResult<any>[] = [];
            let r = iter.next();
            while (!r.done) { results.push({ done: r.done, value: r.value }); r = iter.next(); }
            return results;`, `{{done = false, value = "c"}, {done = false, value = "d"}}`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local map = __TS__New(Map, {{1, "a"}, {2, "b"}, {3, "c"}})
    local iter = map:values()
    iter:next()
    map:delete(2)
    map:set(4, "d")
    local results = {}
    local r = iter:next()
    while not r.done do
        results[#results + 1] = {done = r.done, value = r.value}
        r = iter:next()
    end
    return results
end
return ____exports`, false, false},
		{"map.values() handles mutation", `const map = new Map<number, string>([[1, "a"], [2, "b"]]);
            const iter = map.values();
            const results: boolean[] = [];
            results.push(iter.next().done!);
            results.push(iter.next().done!);
            results.push(iter.next().done!); // should be done
            results.push(iter.next().done!); // should still be done, not restart
            return results;`, `{false, false, true, true}`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local map = __TS__New(Map, {{1, "a"}, {2, "b"}})
    local iter = map:values()
    local results = {}
    results[#results + 1] = iter:next().done
    results[#results + 1] = iter:next().done
    results[#results + 1] = iter:next().done
    results[#results + 1] = iter:next().done
    return results
end
return ____exports`, false, false},
		{"Map.groupBy empty", `const array: number[] = [];

            const map = Map.groupBy(array, (num, index) => {
                return num % 2 === 0 ? "even": "odd";
            });

            return Object.fromEntries(map.entries());`, `{}`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__MapGroupBy = ____lualib.__TS__MapGroupBy
local __TS__ObjectFromEntries = ____lualib.__TS__ObjectFromEntries
local ____exports = {}
function ____exports.__main(self)
    local array = {}
    local map = __TS__MapGroupBy(
        array,
        function(____, num, index)
            return num % 2 == 0 and "even" or "odd"
        end
    )
    return __TS__ObjectFromEntries(map:entries())
end
return ____exports`, false, false},
		{"Map.groupBy groupBy", `const array = [0, 1, 2, 3, 4, 5];

            const map = Map.groupBy(array, (num, index) => {
                return num % 2 === 0 ? "even": "odd";
            });

            return Object.fromEntries(map.entries());`, `{even = {0, 2, 4}, odd = {1, 3, 5}}`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__MapGroupBy = ____lualib.__TS__MapGroupBy
local __TS__ObjectFromEntries = ____lualib.__TS__ObjectFromEntries
local ____exports = {}
function ____exports.__main(self)
    local array = {
        0,
        1,
        2,
        3,
        4,
        5
    }
    local map = __TS__MapGroupBy(
        array,
        function(____, num, index)
            return num % 2 == 0 and "even" or "odd"
        end
    )
    return __TS__ObjectFromEntries(map:entries())
end
return ____exports`, false, false},
		{"Map.groupBy groupBy index", `const array = [0, 1, 2, 3, 4, 5];

            const map = Map.groupBy(array, (num, index) => {
                return index < 3 ? "low": "high";
            });

            return Object.fromEntries(map.entries());`, `{high = {3, 4, 5}, low = {0, 1, 2}}`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__MapGroupBy = ____lualib.__TS__MapGroupBy
local __TS__ObjectFromEntries = ____lualib.__TS__ObjectFromEntries
local ____exports = {}
function ____exports.__main(self)
    local array = {
        0,
        1,
        2,
        3,
        4,
        5
    }
    local map = __TS__MapGroupBy(
        array,
        function(____, num, index)
            return index < 3 and "low" or "high"
        end
    )
    return __TS__ObjectFromEntries(map:entries())
end
return ____exports`, false, false},
	})

	batchRunTests(t, []batchTestCase{
		{name: "map clear", tsCode: `let mymap = new Map([["a", "c"],["b", "d"]]); mymap.clear();
export const __result = mymap.size;`, accessor: `mod["__result"]`, want: `0`, refLua: `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local ____exports = {}
local mymap = __TS__New(Map, {{"a", "c"}, {"b", "d"}})
mymap:clear()
____exports.__result = mymap.size
return ____exports`},
		{name: "map clear", tsCode: `let mymap = new Map([["a", "c"],["b", "d"]]); mymap.clear();
export const __result = !mymap.has("a") && !mymap.has("b");`, accessor: `mod["__result"]`, want: `true`, refLua: `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local ____exports = {}
local mymap = __TS__New(Map, {{"a", "c"}, {"b", "d"}})
mymap:clear()
____exports.__result = not mymap:has("a") and not mymap:has("b")
return ____exports`},
	})
}
