// Code generated by scripts/migrate from extern/tstl/test/unit/modules/modules.spec.ts. DO NOT EDIT.
package tstltest

import "testing"

func TestEval_Modules(t *testing.T) {
	t.Parallel()

	batchExpectModules(t, []moduleTestCase{
		{"module import/export elision should elide type exports", `(globalThis as any).foo = true;
            type foo = boolean;
            export { foo };`, `{}`, `local ____exports = {}
_G.foo = true
return ____exports`, false, false},
		{"export specifier with reassignment afterwards (\"x = 1\")", `let x = 0;
        export { x };
        x = 1;`, `{x = 1}`, `local ____exports = {}
local x = 0
____exports.x = x
x = 1
____exports.x = x
return ____exports`, false, false},
		{"export specifier with reassignment afterwards (\"x++\")", `let x = 0;
        export { x };
        x++;`, `{x = 1}`, `local ____exports = {}
local x = 0
____exports.x = x
x = x + 1
____exports.x = x
return ____exports`, false, false},
		{"export specifier with reassignment afterwards (\"(x = 1)\")", `let x = 0;
        export { x };
        (x = 1);`, `{x = 1}`, `local ____exports = {}
local x = 0
____exports.x = x
x = 1
____exports.x = x
local ____ = x
return ____exports`, false, false},
		{"export specifier with reassignment afterwards (\"[x] = [1]\")", `let x = 0;
        export { x };
        [x] = [1];`, `{x = 1}`, `local ____exports = {}
local x = 0
____exports.x = x
local ____temp_0 = {1}
x = ____temp_0[1]
____exports.x = x
return ____exports`, false, false},
		{"export specifier with reassignment afterwards (\"[[x]] = [[1]]\")", `let x = 0;
        export { x };
        [[x]] = [[1]];`, `{x = 1}`, `local ____exports = {}
local x = 0
____exports.x = x
local ____temp_0 = {{1}}
x = ____temp_0[1][1]
____exports.x = x
return ____exports`, false, false},
		{"export specifier with reassignment afterwards (\"({ x } = { x: 1 })\")", `let x = 0;
        export { x };
        ({ x } = { x: 1 });`, `{x = 1}`, `local ____exports = {}
local x = 0
____exports.x = x
local ____temp_0 = {x = 1}
x = ____temp_0.x
____exports.x = x
return ____exports`, false, false},
		{"export specifier with reassignment afterwards (\"({ y: x } = { y: 1 })\")", `let x = 0;
        export { x };
        ({ y: x } = { y: 1 });`, `{x = 1}`, `local ____exports = {}
local x = 0
____exports.x = x
local ____temp_0 = {y = 1}
x = ____temp_0.y
____exports.x = x
return ____exports`, false, false},
		{"export specifier with reassignment afterwards (\"({ x = 1 } = { x: undefined })\")", `let x = 0;
        export { x };
        ({ x = 1 } = { x: undefined });`, `{x = 1}`, `local ____exports = {}
local x = 0
____exports.x = x
local ____temp_0 = {x = nil}
x = ____temp_0.x
____exports.x = x
if x == nil then
    x = 1
    ____exports.x = x
end
return ____exports`, false, false},
		{"export specifier fork (\"x = 1\")", `let x = 0;
        export { x as a };
        export { x as b };
        x = 1;`, `{a = 1, b = 1}`, `local ____exports = {}
local x = 0
____exports.a = x
____exports.b = x
x = 1
____exports.a = x
____exports.b = x
return ____exports`, false, false},
		{"export specifier fork (\"x++\")", `let x = 0;
        export { x as a };
        export { x as b };
        x++;`, `{a = 1, b = 1}`, `local ____exports = {}
local x = 0
____exports.a = x
____exports.b = x
x = x + 1
____exports.a = x
____exports.b = x
return ____exports`, false, false},
		{"export specifier fork (\"(x = 1)\")", `let x = 0;
        export { x as a };
        export { x as b };
        (x = 1);`, `{a = 1, b = 1}`, `local ____exports = {}
local x = 0
____exports.a = x
____exports.b = x
x = 1
____exports.a = x
____exports.b = x
local ____ = x
return ____exports`, false, false},
		{"export specifier fork (\"[x] = [1]\")", `let x = 0;
        export { x as a };
        export { x as b };
        [x] = [1];`, `{a = 1, b = 1}`, `local ____exports = {}
local x = 0
____exports.a = x
____exports.b = x
local ____temp_0 = {1}
x = ____temp_0[1]
____exports.a = x
____exports.b = x
return ____exports`, false, false},
		{"export specifier fork (\"[[x]] = [[1]]\")", `let x = 0;
        export { x as a };
        export { x as b };
        [[x]] = [[1]];`, `{a = 1, b = 1}`, `local ____exports = {}
local x = 0
____exports.a = x
____exports.b = x
local ____temp_0 = {{1}}
x = ____temp_0[1][1]
____exports.a = x
____exports.b = x
return ____exports`, false, false},
		{"export specifier fork (\"({ x } = { x: 1 })\")", `let x = 0;
        export { x as a };
        export { x as b };
        ({ x } = { x: 1 });`, `{a = 1, b = 1}`, `local ____exports = {}
local x = 0
____exports.a = x
____exports.b = x
local ____temp_0 = {x = 1}
x = ____temp_0.x
____exports.a = x
____exports.b = x
return ____exports`, false, false},
		{"export specifier fork (\"({ y: x } = { y: 1 })\")", `let x = 0;
        export { x as a };
        export { x as b };
        ({ y: x } = { y: 1 });`, `{a = 1, b = 1}`, `local ____exports = {}
local x = 0
____exports.a = x
____exports.b = x
local ____temp_0 = {y = 1}
x = ____temp_0.y
____exports.a = x
____exports.b = x
return ____exports`, false, false},
		{"export specifier fork (\"({ x = 1 } = { x: undefined })\")", `let x = 0;
        export { x as a };
        export { x as b };
        ({ x = 1 } = { x: undefined });`, `{a = 1, b = 1}`, `local ____exports = {}
local x = 0
____exports.a = x
____exports.b = x
local ____temp_0 = {x = nil}
x = ____temp_0.x
____exports.a = x
____exports.b = x
if x == nil then
    x = 1
    ____exports.a = x
    ____exports.b = x
end
return ____exports`, false, false},
		{"does not export shadowed identifiers", `export let a = 1;
        { let a = 2; a = 3 };`, `{a = 1}`, `local ____exports = {}
____exports.a = 1
do
    local a = 2
    a = 3
end
return ____exports`, false, false},
		{"export as specifier shouldn't effect local vars", `let x = false;
        export { x as a };
        let a = 5;
        a = 6;`, `{a = false}`, `local ____exports = {}
local x = false
____exports.a = x
local a = 5
a = 6
return ____exports`, false, false},
	})

	batchRunTests(t, []batchTestCase{
		{name: "Import module names with invalid lua identifier characters (\"ke-bab\")", tsCode: `import { foo } from "./ke-bab";
            export { foo };`, accessor: `mod["foo"]`, want: `"bar"`, refLua: `local ____exports = {}
local ____ke_2Dbab = require("ke-bab")
local foo = ____ke_2Dbab.foo
____exports.foo = foo
return ____exports`, extraFiles: map[string]string{"ke-bab.ts": `export const foo = "bar";`}},
		{name: "Import module names with invalid lua identifier characters (\"dollar$\")", tsCode: `import { foo } from "./dollar$";
            export { foo };`, accessor: `mod["foo"]`, want: `"bar"`, refLua: `local ____exports = {}
local ____dollar_24 = require("dollar$")
local foo = ____dollar_24.foo
____exports.foo = foo
return ____exports`, extraFiles: map[string]string{"dollar$.ts": `export const foo = "bar";`}},
		{name: "Import module names with invalid lua identifier characters (\"singlequote'\")", tsCode: `import { foo } from "./singlequote'";
            export { foo };`, accessor: `mod["foo"]`, want: `"bar"`, refLua: `local ____exports = {}
local ____singlequote_27 = require("singlequote'")
local foo = ____singlequote_27.foo
____exports.foo = foo
return ____exports`, extraFiles: map[string]string{"singlequote'.ts": `export const foo = "bar";`}},
		{name: "Import module names with invalid lua identifier characters (\"hash#\")", tsCode: `import { foo } from "./hash#";
            export { foo };`, accessor: `mod["foo"]`, want: `"bar"`, refLua: `local ____exports = {}
local ____hash_23 = require("hash#")
local foo = ____hash_23.foo
____exports.foo = foo
return ____exports`, extraFiles: map[string]string{"hash#.ts": `export const foo = "bar";`}},
		{name: "Import module names with invalid lua identifier characters (\"s p a c e\")", tsCode: `import { foo } from "./s p a c e";
            export { foo };`, accessor: `mod["foo"]`, want: `"bar"`, refLua: `local ____exports = {}
local ____s_20p_20a_20c_20e = require("s p a c e")
local foo = ____s_20p_20a_20c_20e.foo
____exports.foo = foo
return ____exports`, extraFiles: map[string]string{"s p a c e.ts": `export const foo = "bar";`}},
		{name: "Import module names with invalid lua identifier characters (\"ɥɣɎɌͼƛಠ\")", tsCode: `import { foo } from "./ɥɣɎɌͼƛಠ";
            export { foo };`, accessor: `mod["foo"]`, want: `"bar"`, refLua: `local ____exports = {}
local _____265_263_24E_24C_37C_19B_CA0 = require("ɥɣɎɌͼƛಠ")
local foo = _____265_263_24E_24C_37C_19B_CA0.foo
____exports.foo = foo
return ____exports`, extraFiles: map[string]string{"ɥɣɎɌͼƛಠ.ts": `export const foo = "bar";`}},
		{name: "Import module names with invalid lua identifier characters (\"_̀ः٠‿\")", tsCode: `import { foo } from "./_̀ः٠‿";
            export { foo };`, accessor: `mod["foo"]`, want: `"bar"`, refLua: `local ____exports = {}
local ______300_903_660_203F = require("_̀ः٠‿")
local foo = ______300_903_660_203F.foo
____exports.foo = foo
return ____exports`, extraFiles: map[string]string{"_̀ः٠‿.ts": `export const foo = "bar";`}},
		{name: "Export Default From (\"export default value;\")", tsCode: `export { default } from "./module";`, accessor: `mod`, want: `{default = true}`, refLua: `local ____exports = {}
do
    local ____module = require("module")
    ____exports.default = ____module.default
end
return ____exports`, extraFiles: map[string]string{"module.ts": `
                export const value = true;
                export default value;;
            `}},
		{name: "Export Default From (\"export { value as default };\")", tsCode: `export { default } from "./module";`, accessor: `mod`, want: `{default = true}`, refLua: `local ____exports = {}
do
    local ____module = require("module")
    ____exports.default = ____module.default
end
return ____exports`, extraFiles: map[string]string{"module.ts": `
                export const value = true;
                export { value as default };;
            `}},
		{name: "Default Import and Export Expression", tsCode: `import defaultExport from "./module";
        export const value = defaultExport;`, accessor: `mod`, want: `{value = 6}`, refLua: `local ____exports = {}
local ____module = require("module")
local defaultExport = ____module.default
____exports.value = defaultExport
return ____exports`, extraFiles: map[string]string{"module.ts": `
                export default 1 + 2 + 3;
            `}},
		{name: "Mixed Exports, Default and Named Imports", tsCode: `import defaultExport, { a, b, c } from "./module";
        export const value = defaultExport + b + c;`, accessor: `mod`, want: `{value = 6}`, refLua: `local ____exports = {}
local ____module = require("module")
local defaultExport = ____module.default
local b = ____module.b
local c = ____module.c
____exports.value = defaultExport + b + c
return ____exports`, extraFiles: map[string]string{"module.ts": `
                export const a = 1;
                export const b = 2;
                export const c = 3;
                export default a;
            `}},
		{name: "Mixed Exports, Default and Namespace Import", tsCode: `import defaultExport, * as ns from "./module";
        export const value = defaultExport + ns.b + ns.c;`, accessor: `mod`, want: `{value = 6}`, refLua: `local ____exports = {}
local ____module = require("module")
local defaultExport = ____module.default
local ns = require("module")
____exports.value = defaultExport + ns.b + ns.c
return ____exports`, extraFiles: map[string]string{"module.ts": `
                export const a = 1;
                export const b = 2;
                export const c = 3;
                export default a;
            `}},
		{name: "Export Default Function", tsCode: `import defaultExport from "./module";
        export const value = defaultExport();`, accessor: `mod`, want: `{value = true}`, refLua: `local ____exports = {}
local ____module = require("module")
local defaultExport = ____module.default
____exports.value = defaultExport(nil)
return ____exports`, extraFiles: map[string]string{"module.ts": `
                export default function() {
                    return true;
                }
            `}},
		{name: "export modified in for in loop", tsCode: `export let foo = '';
        for (foo in { x: true }) {}`, accessor: `mod["foo"]`, want: `"x"`, refLua: `local ____exports = {}
____exports.foo = ""
for ____value in pairs({x = true}) do
    ____exports.foo = ____value
end
return ____exports`},
		{name: "export dependency modified in for in loop", tsCode: `let foo = '';
        export { foo as bar };
        for (foo in { x: true }) {}`, accessor: `mod["bar"]`, want: `"x"`, refLua: `local ____exports = {}
local foo = ""
____exports.bar = foo
for ____value in pairs({x = true}) do
    foo = ____value
    ____exports.bar = foo
end
return ____exports`},
		{name: "export default class with future reference", tsCode: `export default class Default {}
        const d = new Default();
        export const result = d.constructor.name;`, accessor: `mod["result"]`, want: `"Default"`, refLua: `local ____lualib = require("lualib_bundle")
local __TS__Class = ____lualib.__TS__Class
local __TS__New = ____lualib.__TS__New
local ____exports = {}
____exports.default = __TS__Class()
local Default = ____exports.default
Default.name = "Default"
function Default.prototype.____constructor(self)
end
local d = __TS__New(____exports.default)
____exports.result = d.constructor.name
return ____exports`},
		{name: "export default function with future reference", tsCode: `export default function defaultFunction() {
            return true;
        }
        export const result = defaultFunction();`, accessor: `mod["result"]`, want: `true`, refLua: `local ____exports = {}
function ____exports.default(self)
    return true
end
____exports.result = ____exports.default(nil)
return ____exports`},
		{name: "namespace export does not include default", tsCode: `export * as result from "./module";`, accessor: `mod`, want: `{result = {default = true, foo = "bar"}}`, refLua: `local ____exports = {}
____exports.result = require("module")
return ____exports`, extraFiles: map[string]string{"module.ts": `
export default true;
export const foo = "bar";
`}},
		{name: "namespace export with unsafe Lua name", tsCode: `export * as $$$ from "./module";`, accessor: `mod`, want: `{$$$ = {default = true, foo = "bar"}}`, refLua: `local ____exports = {}
____exports["$$$"] = require("module")
return ____exports`, extraFiles: map[string]string{"module.ts": `
export default true;
export const foo = "bar";
`}},
		{name: "correctly exports @compileMembersOnly enums (#1572)", tsCode: `export { val } from "./otherfile";`, accessor: `mod`, want: `{val = 3}`, refLua: `local ____exports = {}
do
    local ____otherfile = require("otherfile")
    ____exports.val = ____otherfile.val
end
return ____exports`, extraFiles: map[string]string{"otherfile.ts": `
        // Would put this in the main file, but we cannot transfer enum types over lua/js boundary
        // but we still need to have an exported enum, hence it is in another file
        /** @compileMembersOnly */
        export enum MyEnum {
            A = 0,
            B = 1,
            C = 2
        }
        export const val = MyEnum.B | MyEnum.C;
    `}},
	})

	t.Run("Import and Export Assignment", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `import m = require("./module");
        export const value = m;`, `{value = true}`, WithExtraFile("module.ts", `
                export = true;
            `), WithOptions(map[string]any{"module": 1}))
	})

	t.Run("Export Equals", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `export = true;`, `true`, WithOptions(map[string]any{"module": 1}))
	})

	t.Run("export all does not include default", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `export * from "./module";`, `{foo = "bar"}`, WithExtraFile("module.ts", `
export default true;
export const foo = "bar";
`), WithOptions(map[string]any{"module": 1}))
	})

	t.Run("import expression", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `let result;
        import("./module").then(m => { result = m.foo(); });
        export { result };`, `{result = "foo"}`, WithExtraFile("module.ts", `export function foo() { return "foo"; }`), WithOptions(map[string]any{"module": 99}))
	})
}
