// Code generated by scripts/migrate from extern/tstl/test/unit/functions/noImplicitSelfOption.spec.ts. DO NOT EDIT.
package tstltest

import "testing"

func TestEval_NoImplicitSelfOption(t *testing.T) {
	t.Parallel()

	t.Run("noImplicitSelf does not affect functions in default libraries", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `const array = [1, 2, 3];
        const items = array.filter(x => x > 1); // array.filter is in external library
        return items;`, `{2, 3}`, WithOptions(map[string]any{"noImplicitSelf": true}))
	})

	t.Run("explicit this parameter respected over noImplicitSelf", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `function foo(this: unknown, arg: any) {
            return {self: this, arg};
        }
        export const result = foo(1);`, `{result = {arg = 1}}`, WithOptions(map[string]any{"noImplicitSelf": true}))
	})
}
