// Code generated by scripts/migrate from extern/tstl/test/unit/functions/noImplicitGlobalVariables.spec.ts. DO NOT EDIT.
package tstltest

import "testing"

func TestEval_NoImplicitGlobalVariables(t *testing.T) {
	t.Parallel()
}
