// Code generated by scripts/migrate from extern/tstl/test/unit/nullishCoalescing.spec.ts. DO NOT EDIT.
package tstltest

import "testing"

func TestEval_NullishCoalescing(t *testing.T) {
	t.Parallel()

	batchExpectExpressions(t, []exprTestCase{
		{"nullish-coalesing operator returns rhs", `null ?? "Hello, World!"`, `"Hello, World!"`, `local ____exports = {}
____exports.__result = nil or "Hello, World!"
return ____exports`, false, true},
		{"nullish-coalesing operator returns rhs", `undefined ?? "Hello, World!"`, `"Hello, World!"`, `local ____exports = {}
____exports.__result = nil or "Hello, World!"
return ____exports`, false, true},
		{"nullish-coalesing operator returns lhs", `3 ?? "Hello, World!"`, `3`, `local ____exports = {}
____exports.__result = 3 or "Hello, World!"
return ____exports`, false, true},
		{"nullish-coalesing operator returns lhs", `"foo" ?? "Hello, World!"`, `"foo"`, `local ____exports = {}
____exports.__result = "foo" or "Hello, World!"
return ____exports`, false, true},
		{"nullish-coalesing operator returns lhs", `{} ?? "Hello, World!"`, `{}`, `local ____exports = {}
____exports.__result = ({}) or "Hello, World!"
return ____exports`, false, true},
		{"nullish-coalesing operator returns lhs", `[] ?? "Hello, World!"`, `{}`, `local ____exports = {}
____exports.__result = ({}) or "Hello, World!"
return ____exports`, false, true},
		{"nullish-coalesing operator returns lhs", `true ?? "Hello, World!"`, `true`, `local ____exports = {}
local ____temp_0 = true
if ____temp_0 == nil then
    ____temp_0 = "Hello, World!"
end
____exports.__result = ____temp_0
return ____exports`, false, true},
		{"nullish-coalesing operator returns lhs", `false ?? "Hello, World!"`, `false`, `local ____exports = {}
local ____temp_0 = false
if ____temp_0 == nil then
    ____temp_0 = "Hello, World!"
end
____exports.__result = ____temp_0
return ____exports`, false, true},
	})

	batchExpectFunctions(t, []funcTestCase{
		{"nullish-coalesing operator with any/unknown type", `const unknownType = false as any;
        return unknownType ?? "This should not be returned!";`, `false`, `local ____exports = {}
function ____exports.__main(self)
    local unknownType = false
    local ____unknownType_0 = unknownType
    if ____unknownType_0 == nil then
        ____unknownType_0 = "This should not be returned!"
    end
    return ____unknownType_0
end
return ____exports`, false, true},
		{"nullish-coalesing operator with any/unknown type", `const unknownType = false as unknown;
        return unknownType ?? "This should not be returned!";`, `false`, `local ____exports = {}
function ____exports.__main(self)
    local unknownType = false
    local ____unknownType_0 = unknownType
    if ____unknownType_0 == nil then
        ____unknownType_0 = "This should not be returned!"
    end
    return ____unknownType_0
end
return ____exports`, false, true},
		{"nullish-coalesing operator with union type", `const unknownType = false as boolean | string;
            return unknownType ?? "This should not be returned!";`, `false`, `local ____exports = {}
function ____exports.__main(self)
    local unknownType = false
    local ____unknownType_0 = unknownType
    if ____unknownType_0 == nil then
        ____unknownType_0 = "This should not be returned!"
    end
    return ____unknownType_0
end
return ____exports`, false, false},
		{"nullish-coalesing operator with union type", `const unknownType = false as number | false;
            return unknownType ?? "This should not be returned!";`, `false`, `local ____exports = {}
function ____exports.__main(self)
    local unknownType = false
    local ____unknownType_0 = unknownType
    if ____unknownType_0 == nil then
        ____unknownType_0 = "This should not be returned!"
    end
    return ____unknownType_0
end
return ____exports`, false, false},
		{"nullish-coalesing operator with union type", `const unknownType = false as undefined | true;
            return unknownType ?? "This should not be returned!";`, `false`, `local ____exports = {}
function ____exports.__main(self)
    local unknownType = false
    local ____unknownType_0 = unknownType
    if ____unknownType_0 == nil then
        ____unknownType_0 = "This should not be returned!"
    end
    return ____unknownType_0
end
return ____exports`, false, false},
		{"nullish-coalescing operator with side effect lhs", `let i = 0;
        const incI = () => ++i;
        return [i, incI() ?? 3, i];`, `{0, 1, 1}`, `local ____exports = {}
function ____exports.__main(self)
    local i = 0
    local function incI()
        i = i + 1
        return i
    end
    return {
        i,
        incI(nil) or 3,
        i
    }
end
return ____exports`, false, false},
		{"nullish-coalescing operator with side effect rhs", `let i = 0;
        const incI = () => ++i;
        return [i, undefined ?? incI(), i];`, `{0, 1, 1}`, `local ____exports = {}
function ____exports.__main(self)
    local i = 0
    local function incI()
        i = i + 1
        return i
    end
    return {
        i,
        nil or incI(nil),
        i
    }
end
return ____exports`, false, true},
		{"nullish-coalescing operator with vararg", `function foo(...args: any[]){
            return args
        }
        function bar(...args: any[]) {
            let x: boolean | undefined = false
            const y = x ?? foo(...args)
        }
        return bar(1, 2)`, `nil`, `local ____exports = {}
function ____exports.__main(self)
    local function foo(self, ...)
        local args = {...}
        return args
    end
    local function bar(self, ...)
        local x = false
        local ____x_0 = x
        if ____x_0 == nil then
            ____x_0 = foo(nil, ...)
        end
        local y = ____x_0
    end
    return bar(nil, 1, 2)
end
return ____exports`, false, false},
		{"nullish-coalescing with generic lhs (true)", `function coalesce<A, B>(a: A, b: B) {
            return a ?? b
        }
        return coalesce(true, "wasNull")`, `true`, `local ____exports = {}
function ____exports.__main(self)
    local function coalesce(self, a, b)
        local ____a_0 = a
        if ____a_0 == nil then
            ____a_0 = b
        end
        return ____a_0
    end
    return coalesce(nil, true, "wasNull")
end
return ____exports`, false, false},
		{"nullish-coalescing with generic lhs (false)", `function coalesce<A, B>(a: A, b: B) {
            return a ?? b
        }
        return coalesce(false, "wasNull")`, `false`, `local ____exports = {}
function ____exports.__main(self)
    local function coalesce(self, a, b)
        local ____a_0 = a
        if ____a_0 == nil then
            ____a_0 = b
        end
        return ____a_0
    end
    return coalesce(nil, false, "wasNull")
end
return ____exports`, false, false},
		{"nullish-coalescing with generic lhs (null)", `function coalesce<A, B>(a: A, b: B) {
            return a ?? b
        }
        return coalesce(null, "wasNull")`, `"wasNull"`, `local ____exports = {}
function ____exports.__main(self)
    local function coalesce(self, a, b)
        local ____a_0 = a
        if ____a_0 == nil then
            ____a_0 = b
        end
        return ____a_0
    end
    return coalesce(nil, nil, "wasNull")
end
return ____exports`, false, false},
	})
}
