// Code generated by scripts/migrate from extern/tstl/test/unit/builtins/object.spec.ts. DO NOT EDIT.
package tstltest

import "testing"

func TestEval_Object(t *testing.T) {
	t.Parallel()

	batchExpectExpressions(t, []exprTestCase{
		{"Object.assign ({\"initial\":{\"a\":3},\"args\":[{}]})", `Object.assign({"a":3}, {})`, `{a = 3}`, `local ____lualib = require("lualib_bundle")
local __TS__ObjectAssign = ____lualib.__TS__ObjectAssign
local ____exports = {}
____exports.__result = __TS__ObjectAssign({a = 3}, {})
return ____exports`, false, false},
		{"Object.assign ({\"initial\":{},\"args\":[{\"a\":3}]})", `Object.assign({}, {"a":3})`, `{a = 3}`, `local ____lualib = require("lualib_bundle")
local __TS__ObjectAssign = ____lualib.__TS__ObjectAssign
local ____exports = {}
____exports.__result = __TS__ObjectAssign({}, {a = 3})
return ____exports`, false, false},
		{"Object.assign ({\"initial\":{\"a\":3},\"args\":[{\"a\":5}]})", `Object.assign({"a":3}, {"a":5})`, `{a = 5}`, `local ____lualib = require("lualib_bundle")
local __TS__ObjectAssign = ____lualib.__TS__ObjectAssign
local ____exports = {}
____exports.__result = __TS__ObjectAssign({a = 3}, {a = 5})
return ____exports`, false, false},
		{"Object.assign ({\"initial\":{\"a\":3},\"args\":[{\"b\":5},{\"c\":7}]})", `Object.assign({"a":3}, {"b":5}, {"c":7})`, `{a = 3, b = 5, c = 7}`, `local ____lualib = require("lualib_bundle")
local __TS__ObjectAssign = ____lualib.__TS__ObjectAssign
local ____exports = {}
____exports.__result = __TS__ObjectAssign({a = 3}, {b = 5}, {c = 7})
return ____exports`, false, false},
		{"Object.assign skips non-object sources (\"Object.assign({}, false)\")", `Object.assign({}, false)`, `{}`, `local ____lualib = require("lualib_bundle")
local __TS__ObjectAssign = ____lualib.__TS__ObjectAssign
local ____exports = {}
____exports.__result = __TS__ObjectAssign({}, false)
return ____exports`, false, false},
		{"Object.assign skips non-object sources (\"Object.assign({}, null)\")", `Object.assign({}, null)`, `{}`, `local ____lualib = require("lualib_bundle")
local __TS__ObjectAssign = ____lualib.__TS__ObjectAssign
local ____exports = {}
____exports.__result = __TS__ObjectAssign({}, nil)
return ____exports`, false, false},
		{"Object.assign skips non-object sources (\"Object.assign({}, undefined)\")", `Object.assign({}, undefined)`, `{}`, `local ____lualib = require("lualib_bundle")
local __TS__ObjectAssign = ____lualib.__TS__ObjectAssign
local ____exports = {}
____exports.__result = __TS__ObjectAssign({}, nil)
return ____exports`, false, false},
		{"Object.assign skips non-object sources (\"Object.assign({}, null, undefined)\")", `Object.assign({}, null, undefined)`, `{}`, `local ____lualib = require("lualib_bundle")
local __TS__ObjectAssign = ____lualib.__TS__ObjectAssign
local ____exports = {}
____exports.__result = __TS__ObjectAssign({}, nil, nil)
return ____exports`, false, false},
		{"Object.assign skips non-object sources (\"Object.assign({ a: 1 }, false, { b: 2 })\")", `Object.assign({ a: 1 }, false, { b: 2 })`, `{a = 1, b = 2}`, `local ____lualib = require("lualib_bundle")
local __TS__ObjectAssign = ____lualib.__TS__ObjectAssign
local ____exports = {}
____exports.__result = __TS__ObjectAssign({a = 1}, false, {b = 2})
return ____exports`, false, false},
		{"Object.fromEntries([])", `Object.fromEntries([])`, `{}`, `local ____lualib = require("lualib_bundle")
local __TS__ObjectFromEntries = ____lualib.__TS__ObjectFromEntries
local ____exports = {}
____exports.__result = __TS__ObjectFromEntries({})
return ____exports`, false, false},
		{"Object.fromEntries([[\"a\", 1], [\"b\", 2]])", `Object.fromEntries([["a", 1], ["b", 2]])`, `{a = 1, b = 2}`, `local ____lualib = require("lualib_bundle")
local __TS__ObjectFromEntries = ____lualib.__TS__ObjectFromEntries
local ____exports = {}
____exports.__result = __TS__ObjectFromEntries({{"a", 1}, {"b", 2}})
return ____exports`, false, false},
		{"Object.fromEntries([[\"a\", 1], [\"a\", 2]])", `Object.fromEntries([["a", 1], ["a", 2]])`, `{a = 2}`, `local ____lualib = require("lualib_bundle")
local __TS__ObjectFromEntries = ____lualib.__TS__ObjectFromEntries
local ____exports = {}
____exports.__result = __TS__ObjectFromEntries({{"a", 1}, {"a", 2}})
return ____exports`, false, false},
		{"Object.fromEntries(new Map([[\"foo\", \"bar\"]]))", `Object.fromEntries(new Map([["foo", "bar"]]))`, `{foo = "bar"}`, `local ____lualib = require("lualib_bundle")
local Map = ____lualib.Map
local __TS__New = ____lualib.__TS__New
local __TS__ObjectFromEntries = ____lualib.__TS__ObjectFromEntries
local ____exports = {}
____exports.__result = __TS__ObjectFromEntries(__TS__New(Map, {{"foo", "bar"}}))
return ____exports`, false, false},
	})

	batchExpectFunctions(t, []funcTestCase{
		{".toString() class override", `function toString(value: object) {
            const result = value.toString();
            return result === "[object Object]" || result.startsWith("table: ") ? "table" : result;
        }
    
            class A {
                public toString() {
                    return "A";
                }
            }

            return toString(new A());`, `"A"`, `local ____lualib = require("lualib_bundle")
local __TS__StringStartsWith = ____lualib.__TS__StringStartsWith
local __TS__Class = ____lualib.__TS__Class
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local function toString(self, value)
        local result = tostring(value)
        return (result == "[object Object]" or __TS__StringStartsWith(result, "table: ")) and "table" or result
    end
    local A = __TS__Class()
    A.name = "A"
    function A.prototype.____constructor(self)
    end
    function A.prototype.__tostring(self)
        return "A"
    end
    return toString(
        nil,
        __TS__New(A)
    )
end
return ____exports`, false, false},
		{".toString() inherited class override", `function toString(value: object) {
            const result = value.toString();
            return result === "[object Object]" || result.startsWith("table: ") ? "table" : result;
        }
    
            class A {
                public toString() {
                    return "A";
                }
            }

            class B extends A {}

            return { A: toString(new A()), B: toString(new B()) };`, `{A = "A", B = "A"}`, `local ____lualib = require("lualib_bundle")
local __TS__StringStartsWith = ____lualib.__TS__StringStartsWith
local __TS__Class = ____lualib.__TS__Class
local __TS__ClassExtends = ____lualib.__TS__ClassExtends
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local function toString(self, value)
        local result = tostring(value)
        return (result == "[object Object]" or __TS__StringStartsWith(result, "table: ")) and "table" or result
    end
    local A = __TS__Class()
    A.name = "A"
    function A.prototype.____constructor(self)
    end
    function A.prototype.__tostring(self)
        return "A"
    end
    local B = __TS__Class()
    B.name = "B"
    __TS__ClassExtends(B, A)
    return {
        A = toString(
            nil,
            __TS__New(A)
        ),
        B = toString(
            nil,
            __TS__New(B)
        )
    }
end
return ____exports`, false, false},
		{".toString() don't affect inherited class", `function toString(value: object) {
            const result = value.toString();
            return result === "[object Object]" || result.startsWith("table: ") ? "table" : result;
        }
    
            class A {}

            class B extends A {
                public toString() {
                    return "B";
                }
            }

            return { A: toString(new A()), B: toString(new B()) };`, `{A = "table", B = "B"}`, `local ____lualib = require("lualib_bundle")
local __TS__StringStartsWith = ____lualib.__TS__StringStartsWith
local __TS__Class = ____lualib.__TS__Class
local __TS__ClassExtends = ____lualib.__TS__ClassExtends
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local function toString(self, value)
        local result = tostring(value)
        return (result == "[object Object]" or __TS__StringStartsWith(result, "table: ")) and "table" or result
    end
    local A = __TS__Class()
    A.name = "A"
    function A.prototype.____constructor(self)
    end
    local B = __TS__Class()
    B.name = "B"
    __TS__ClassExtends(B, A)
    function B.prototype.__tostring(self)
        return "B"
    end
    return {
        A = toString(
            nil,
            __TS__New(A)
        ),
        B = toString(
            nil,
            __TS__New(B)
        )
    }
end
return ____exports`, false, false},
		{".toString() override inherited class override", `function toString(value: object) {
            const result = value.toString();
            return result === "[object Object]" || result.startsWith("table: ") ? "table" : result;
        }
    
            class A {
                public toString() {
                    return "A";
                }
            }

            class B extends A {
                public toString() {
                    return "B";
                }
            }

            return { A: toString(new A()), B: toString(new B()) };`, `{A = "A", B = "B"}`, `local ____lualib = require("lualib_bundle")
local __TS__StringStartsWith = ____lualib.__TS__StringStartsWith
local __TS__Class = ____lualib.__TS__Class
local __TS__ClassExtends = ____lualib.__TS__ClassExtends
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local function toString(self, value)
        local result = tostring(value)
        return (result == "[object Object]" or __TS__StringStartsWith(result, "table: ")) and "table" or result
    end
    local A = __TS__Class()
    A.name = "A"
    function A.prototype.____constructor(self)
    end
    function A.prototype.__tostring(self)
        return "A"
    end
    local B = __TS__Class()
    B.name = "B"
    __TS__ClassExtends(B, A)
    function B.prototype.__tostring(self)
        return "B"
    end
    return {
        A = toString(
            nil,
            __TS__New(A)
        ),
        B = toString(
            nil,
            __TS__New(B)
        )
    }
end
return ____exports`, false, false},
		{".hasOwnProperty() class field", `class A {
                public field = true;
            }

            return new A().hasOwnProperty("field");`, `true`, `local ____lualib = require("lualib_bundle")
local __TS__Class = ____lualib.__TS__Class
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local A = __TS__Class()
    A.name = "A"
    function A.prototype.____constructor(self)
        self.field = true
    end
    return rawget(
        __TS__New(A),
        "field"
    ) ~= nil
end
return ____exports`, false, false},
		{".hasOwnProperty() class method", `class A {
                public method() {}
            }

            return new A().hasOwnProperty("method");`, `false`, `local ____lualib = require("lualib_bundle")
local __TS__Class = ____lualib.__TS__Class
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local A = __TS__Class()
    A.name = "A"
    function A.prototype.____constructor(self)
    end
    function A.prototype.method(self)
    end
    return rawget(
        __TS__New(A),
        "method"
    ) ~= nil
end
return ____exports`, false, false},
		{"Object.defineProperty writable (true)", `const foo = { bar: true };
            Object.defineProperty(foo, "bar", { writable: true });
            let error = false;
            try {
                foo.bar = false;
            } catch {
                error = true;
            }
            return { foobar: foo.bar, error };`, `{error = false, foobar = false}`, `local ____lualib = require("lualib_bundle")
local __TS__ObjectDefineProperty = ____lualib.__TS__ObjectDefineProperty
local ____exports = {}
function ____exports.__main(self)
    local foo = {bar = true}
    __TS__ObjectDefineProperty(foo, "bar", {writable = true})
    local ____error = false
    do
        local function ____catch()
            ____error = true
        end
        local ____try = pcall(function()
            foo.bar = false
        end)
        if not ____try then
            ____catch()
        end
    end
    return {foobar = foo.bar, error = ____error}
end
return ____exports`, false, false},
		{"Object.defineProperty writable (false)", `const foo = { bar: true };
            Object.defineProperty(foo, "bar", { writable: false });
            let error = false;
            try {
                foo.bar = false;
            } catch {
                error = true;
            }
            return { foobar: foo.bar, error };`, `{error = true, foobar = true}`, `local ____lualib = require("lualib_bundle")
local __TS__ObjectDefineProperty = ____lualib.__TS__ObjectDefineProperty
local ____exports = {}
function ____exports.__main(self)
    local foo = {bar = true}
    __TS__ObjectDefineProperty(foo, "bar", {writable = false})
    local ____error = false
    do
        local function ____catch()
            ____error = true
        end
        local ____try = pcall(function()
            foo.bar = false
        end)
        if not ____try then
            ____catch()
        end
    end
    return {foobar = foo.bar, error = ____error}
end
return ____exports`, false, false},
		{"Object.defineProperty configurable (true)", `const foo: { bar?: boolean } = { bar: true };
            Object.defineProperty(foo, "bar", { configurable: true });
            try { delete foo.bar } catch {};
            return foo.bar;`, `nil`, `local ____lualib = require("lualib_bundle")
local __TS__ObjectDefineProperty = ____lualib.__TS__ObjectDefineProperty
local __TS__Delete = ____lualib.__TS__Delete
local ____exports = {}
function ____exports.__main(self)
    local foo = {bar = true}
    __TS__ObjectDefineProperty(foo, "bar", {configurable = true})
    do
        pcall(function()
            __TS__Delete(foo, "bar")
        end)
    end
    return foo.bar
end
return ____exports`, false, false},
		{"Object.defineProperty configurable (false)", `const foo: { bar?: boolean } = { bar: true };
            Object.defineProperty(foo, "bar", { configurable: false });
            try { delete foo.bar } catch {};
            return foo.bar;`, `true`, `local ____lualib = require("lualib_bundle")
local __TS__ObjectDefineProperty = ____lualib.__TS__ObjectDefineProperty
local __TS__Delete = ____lualib.__TS__Delete
local ____exports = {}
function ____exports.__main(self)
    local foo = {bar = true}
    __TS__ObjectDefineProperty(foo, "bar", {configurable = false})
    do
        pcall(function()
            __TS__Delete(foo, "bar")
        end)
    end
    return foo.bar
end
return ____exports`, false, false},
		{"Object.defineProperty defines a new property", `const foo: any = {};
            Object.defineProperty(foo, "bar", { value: true });
            return foo.bar;`, `true`, `local ____lualib = require("lualib_bundle")
local __TS__ObjectDefineProperty = ____lualib.__TS__ObjectDefineProperty
local ____exports = {}
function ____exports.__main(self)
    local foo = {}
    __TS__ObjectDefineProperty(foo, "bar", {value = true})
    return foo.bar
end
return ____exports`, false, false},
		{"Object.defineProperty overwrites an existing property", `const foo = { bar: false };
            Object.defineProperty(foo, "bar", { value: true });
            return foo.bar;`, `true`, `local ____lualib = require("lualib_bundle")
local __TS__ObjectDefineProperty = ____lualib.__TS__ObjectDefineProperty
local ____exports = {}
function ____exports.__main(self)
    local foo = {bar = false}
    __TS__ObjectDefineProperty(foo, "bar", {value = true})
    return foo.bar
end
return ____exports`, false, false},
		{"Object.defineProperty default descriptor", `const foo = {};
            Object.defineProperty(foo, "bar", {});
            return Object.getOwnPropertyDescriptor(foo, "bar");`, `{configurable = false, enumerable = false, writable = false}`, `local ____lualib = require("lualib_bundle")
local __TS__ObjectDefineProperty = ____lualib.__TS__ObjectDefineProperty
local __TS__ObjectGetOwnPropertyDescriptor = ____lualib.__TS__ObjectGetOwnPropertyDescriptor
local ____exports = {}
function ____exports.__main(self)
    local foo = {}
    __TS__ObjectDefineProperty(foo, "bar", {})
    return __TS__ObjectGetOwnPropertyDescriptor(foo, "bar")
end
return ____exports`, false, false},
		{"Object.defineProperty invalid descriptor (\"{ value: true, get: () => true }\")", `const foo: any = {};
            let err = false;

            try {
                Object.defineProperty(foo, "bar", { value: true, get: () => true });
            } catch {
                err = true;
            }

            return { prop: foo.bar, err };`, `{err = true}`, `local ____lualib = require("lualib_bundle")
local __TS__ObjectDefineProperty = ____lualib.__TS__ObjectDefineProperty
local ____exports = {}
function ____exports.__main(self)
    local foo = {}
    local err = false
    do
        local function ____catch()
            err = true
        end
        local ____try = pcall(function()
            __TS__ObjectDefineProperty(
                foo,
                "bar",
                {
                    value = true,
                    get = function() return true end
                }
            )
        end)
        if not ____try then
            ____catch()
        end
    end
    return {prop = foo.bar, err = err}
end
return ____exports`, false, false},
		{"Object.defineProperty invalid descriptor (\"{ value: true, set: value => {} }\")", `const foo: any = {};
            let err = false;

            try {
                Object.defineProperty(foo, "bar", { value: true, set: value => {} });
            } catch {
                err = true;
            }

            return { prop: foo.bar, err };`, `{err = true}`, `local ____lualib = require("lualib_bundle")
local __TS__ObjectDefineProperty = ____lualib.__TS__ObjectDefineProperty
local ____exports = {}
function ____exports.__main(self)
    local foo = {}
    local err = false
    do
        local function ____catch()
            err = true
        end
        local ____try = pcall(function()
            __TS__ObjectDefineProperty(
                foo,
                "bar",
                {
                    value = true,
                    set = function(____, value)
                    end
                }
            )
        end)
        if not ____try then
            ____catch()
        end
    end
    return {prop = foo.bar, err = err}
end
return ____exports`, false, false},
		{"Object.defineProperty invalid descriptor (\"{ writable: true, get: () => true }\")", `const foo: any = {};
            let err = false;

            try {
                Object.defineProperty(foo, "bar", { writable: true, get: () => true });
            } catch {
                err = true;
            }

            return { prop: foo.bar, err };`, `{err = true}`, `local ____lualib = require("lualib_bundle")
local __TS__ObjectDefineProperty = ____lualib.__TS__ObjectDefineProperty
local ____exports = {}
function ____exports.__main(self)
    local foo = {}
    local err = false
    do
        local function ____catch()
            err = true
        end
        local ____try = pcall(function()
            __TS__ObjectDefineProperty(
                foo,
                "bar",
                {
                    writable = true,
                    get = function() return true end
                }
            )
        end)
        if not ____try then
            ____catch()
        end
    end
    return {prop = foo.bar, err = err}
end
return ____exports`, false, false},
		{"Object.defineProperty instance isolation", `class Test {
                declare obj: object;
                constructor() {
                    Object.defineProperty(this, "obj", { value: {}, writable: true, configurable: true });
                }
            }
            const t1 = new Test();
            const t2 = new Test();
            return t1.obj === t2.obj;`, `false`, `local ____lualib = require("lualib_bundle")
local __TS__Class = ____lualib.__TS__Class
local __TS__ObjectDefineProperty = ____lualib.__TS__ObjectDefineProperty
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local Test = __TS__Class()
    Test.name = "Test"
    function Test.prototype.____constructor(self)
        __TS__ObjectDefineProperty(self, "obj", {value = {}, writable = true, configurable = true})
    end
    local t1 = __TS__New(Test)
    local t2 = __TS__New(Test)
    return t1.obj == t2.obj
end
return ____exports`, false, false},
		{"Object.defineProperty instance isolation with three instances", `class Test {
                declare obj: object;
                constructor() {
                    Object.defineProperty(this, "obj", { value: {}, writable: true, configurable: true });
                }
            }
            const t1 = new Test();
            const t2 = new Test();
            const t3 = new Test();
            return [t1.obj === t2.obj, t1.obj === t3.obj, t2.obj === t3.obj];`, `{false, false, false}`, `local ____lualib = require("lualib_bundle")
local __TS__Class = ____lualib.__TS__Class
local __TS__ObjectDefineProperty = ____lualib.__TS__ObjectDefineProperty
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local Test = __TS__Class()
    Test.name = "Test"
    function Test.prototype.____constructor(self)
        __TS__ObjectDefineProperty(self, "obj", {value = {}, writable = true, configurable = true})
    end
    local t1 = __TS__New(Test)
    local t2 = __TS__New(Test)
    local t3 = __TS__New(Test)
    return {t1.obj == t2.obj, t1.obj == t3.obj, t2.obj == t3.obj}
end
return ____exports`, false, false},
		{"Object.defineProperty instance isolation with mutation", `class Test {
                declare value: number;
                constructor(v: number) {
                    Object.defineProperty(this, "value", { value: v, writable: true, configurable: true });
                }
            }
            const t1 = new Test(1);
            const t2 = new Test(2);
            return [t1.value, t2.value];`, `{1, 2}`, `local ____lualib = require("lualib_bundle")
local __TS__Class = ____lualib.__TS__Class
local __TS__ObjectDefineProperty = ____lualib.__TS__ObjectDefineProperty
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local Test = __TS__Class()
    Test.name = "Test"
    function Test.prototype.____constructor(self, v)
        __TS__ObjectDefineProperty(self, "value", {value = v, writable = true, configurable = true})
    end
    local t1 = __TS__New(Test, 1)
    local t2 = __TS__New(Test, 2)
    return {t1.value, t2.value}
end
return ____exports`, false, false},
		{"Object.defineProperty instance isolation with multiple properties", `class Test {
                declare a: string;
                declare b: string;
                constructor(a: string, b: string) {
                    Object.defineProperty(this, "a", { value: a, writable: true, configurable: true });
                    Object.defineProperty(this, "b", { value: b, writable: true, configurable: true });
                }
            }
            const t1 = new Test("x", "y");
            const t2 = new Test("p", "q");
            return [t1.a, t1.b, t2.a, t2.b];`, `{"x", "y", "p", "q"}`, `local ____lualib = require("lualib_bundle")
local __TS__Class = ____lualib.__TS__Class
local __TS__ObjectDefineProperty = ____lualib.__TS__ObjectDefineProperty
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local Test = __TS__Class()
    Test.name = "Test"
    function Test.prototype.____constructor(self, a, b)
        __TS__ObjectDefineProperty(self, "a", {value = a, writable = true, configurable = true})
        __TS__ObjectDefineProperty(self, "b", {value = b, writable = true, configurable = true})
    end
    local t1 = __TS__New(Test, "x", "y")
    local t2 = __TS__New(Test, "p", "q")
    return {t1.a, t1.b, t2.a, t2.b}
end
return ____exports`, false, false},
		{"Object.defineProperty instance isolation preserves prototype methods", `class Test {
                declare val: number;
                constructor(v: number) {
                    Object.defineProperty(this, "val", { value: v, writable: true, configurable: true });
                }
                getVal() { return this.val; }
            }
            const t1 = new Test(10);
            const t2 = new Test(20);
            return [t1.getVal(), t2.getVal()];`, `{10, 20}`, `local ____lualib = require("lualib_bundle")
local __TS__Class = ____lualib.__TS__Class
local __TS__ObjectDefineProperty = ____lualib.__TS__ObjectDefineProperty
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local Test = __TS__Class()
    Test.name = "Test"
    function Test.prototype.____constructor(self, v)
        __TS__ObjectDefineProperty(self, "val", {value = v, writable = true, configurable = true})
    end
    function Test.prototype.getVal(self)
        return self.val
    end
    local t1 = __TS__New(Test, 10)
    local t2 = __TS__New(Test, 20)
    return {
        t1:getVal(),
        t2:getVal()
    }
end
return ____exports`, false, false},
		{"Object.getOwnPropertyDescriptor descriptor is exactly the same as the last one set", `const foo = {};
            Object.defineProperty(foo, "bar", {});
            return Object.getOwnPropertyDescriptor(foo, "bar");`, `{configurable = false, enumerable = false, writable = false}`, `local ____lualib = require("lualib_bundle")
local __TS__ObjectDefineProperty = ____lualib.__TS__ObjectDefineProperty
local __TS__ObjectGetOwnPropertyDescriptor = ____lualib.__TS__ObjectGetOwnPropertyDescriptor
local ____exports = {}
function ____exports.__main(self)
    local foo = {}
    __TS__ObjectDefineProperty(foo, "bar", {})
    return __TS__ObjectGetOwnPropertyDescriptor(foo, "bar")
end
return ____exports`, false, false},
		{"Object.getOwnPropertyDescriptors all descriptors match", `const foo = { bar: true };
            Object.defineProperty(foo, "bar", {});
            return Object.getOwnPropertyDescriptors(foo);`, `{bar = {configurable = true, enumerable = true, value = true, writable = true}}`, `local ____lualib = require("lualib_bundle")
local __TS__ObjectDefineProperty = ____lualib.__TS__ObjectDefineProperty
local __TS__ObjectGetOwnPropertyDescriptors = ____lualib.__TS__ObjectGetOwnPropertyDescriptors
local ____exports = {}
function ____exports.__main(self)
    local foo = {bar = true}
    __TS__ObjectDefineProperty(foo, "bar", {})
    return __TS__ObjectGetOwnPropertyDescriptors(foo)
end
return ____exports`, false, false},
		{"delete from object delete from object", `const obj: { foo?: string, bar: string } = { foo: "bar", bar: "baz" };
            return [delete obj["foo"], obj];`, `{true, {bar = "baz"}}`, `local ____lualib = require("lualib_bundle")
local __TS__Delete = ____lualib.__TS__Delete
local ____exports = {}
function ____exports.__main(self)
    local obj = {foo = "bar", bar = "baz"}
    return {
        __TS__Delete(obj, "foo"),
        obj
    }
end
return ____exports`, false, false},
		{"delete from object delete nonexistent property", `const obj = {} as any
            return [delete obj["foo"], obj];`, `{true, {}}`, `local ____lualib = require("lualib_bundle")
local __TS__Delete = ____lualib.__TS__Delete
local ____exports = {}
function ____exports.__main(self)
    local obj = {}
    return {
        __TS__Delete(obj, "foo"),
        obj
    }
end
return ____exports`, false, false},
		{"Object.groupBy empty", `const array: number[] = [];

            return Object.groupBy(array, (num, index) => {
                return num % 2 === 0 ? "even": "odd";
            });`, `{}`, `local ____lualib = require("lualib_bundle")
local __TS__ObjectGroupBy = ____lualib.__TS__ObjectGroupBy
local ____exports = {}
function ____exports.__main(self)
    local array = {}
    return __TS__ObjectGroupBy(
        array,
        function(____, num, index)
            return num % 2 == 0 and "even" or "odd"
        end
    )
end
return ____exports`, false, false},
		{"Object.groupBy groupBy", `const array = [0, 1, 2, 3, 4, 5];

            return Object.groupBy(array, (num, index) => {
                return num % 2 === 0 ? "even": "odd";
            });`, `{even = {0, 2, 4}, odd = {1, 3, 5}}`, `local ____lualib = require("lualib_bundle")
local __TS__ObjectGroupBy = ____lualib.__TS__ObjectGroupBy
local ____exports = {}
function ____exports.__main(self)
    local array = {
        0,
        1,
        2,
        3,
        4,
        5
    }
    return __TS__ObjectGroupBy(
        array,
        function(____, num, index)
            return num % 2 == 0 and "even" or "odd"
        end
    )
end
return ____exports`, false, false},
		{"Object.groupBy groupBy index", `const array = [0, 1, 2, 3, 4, 5];

            return Object.groupBy(array, (num, index) => {
                return index < 3 ? "low": "high";
            });`, `{high = {3, 4, 5}, low = {0, 1, 2}}`, `local ____lualib = require("lualib_bundle")
local __TS__ObjectGroupBy = ____lualib.__TS__ObjectGroupBy
local ____exports = {}
function ____exports.__main(self)
    local array = {
        0,
        1,
        2,
        3,
        4,
        5
    }
    return __TS__ObjectGroupBy(
        array,
        function(____, num, index)
            return index < 3 and "low" or "high"
        end
    )
end
return ____exports`, false, false},
	})

	batchRunTests(t, []batchTestCase{
		{name: "delete from object delete from object with metatable", tsCode: `declare function setmetatable<T extends object>(this: void, table: T, metatable: any): T;
export function __main() {const obj: { foo?: string, bar: string } = { foo: "bar", bar: "baz" };
        setmetatable(obj, {});
        return [delete obj["foo"], obj];}`, accessor: `mod.__main()`, want: `{true, {bar = "baz"}}`, refLua: `local ____lualib = require("lualib_bundle")
local __TS__Delete = ____lualib.__TS__Delete
local ____exports = {}
function ____exports.__main(self)
    local obj = {foo = "bar", bar = "baz"}
    setmetatable(obj, {})
    return {
        __TS__Delete(obj, "foo"),
        obj
    }
end
return ____exports`},
	})

	t.Run("delete from object delete nonconfigurable own property", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `const obj = {} as any
            Object.defineProperty(obj, "foo", {
                configurable: false,
                value: true
            })
            try {
                delete obj["foo"]
                return "deleted"
            } catch (e) {
                return e instanceof TypeError
            }`, `true`, WithOptions(map[string]any{"strict": true}))
	})
}
