// Code generated by scripts/migrate from extern/tstl/test/unit/objectLiteral.spec.ts. DO NOT EDIT.
package tstltest

import "testing"

func TestEval_ObjectLiteral(t *testing.T) {
	t.Parallel()

	batchExpectExpressions(t, []exprTestCase{
		{"Object Literal (\"{ a: 3, b: \\\"4\\\" }\")", `{ a: 3, b: "4" }`, `{a = 3, b = "4"}`, `local ____exports = {}
____exports.__result = {a = 3, b = "4"}
return ____exports`, false, false},
		{"Object Literal (\"{ \\\"a\\\": 3, b: \\\"4\\\" }\")", `{ "a": 3, b: "4" }`, `{a = 3, b = "4"}`, `local ____exports = {}
____exports.__result = {a = 3, b = "4"}
return ____exports`, false, false},
		{"Object Literal (\"{ [\\\"a\\\"]: 3, b: \\\"4\\\" }\")", `{ ["a"]: 3, b: "4" }`, `{a = 3, b = "4"}`, `local ____exports = {}
____exports.__result = {a = 3, b = "4"}
return ____exports`, false, false},
		{"Object Literal (\"{ [\\\"a\\\" + 123]: 3, b: \\\"4\\\" }\")", `{ ["a" + 123]: 3, b: "4" }`, `{a123 = 3, b = "4"}`, `local ____exports = {}
____exports.__result = {["a" .. 123] = 3, b = "4"}
return ____exports`, false, false},
		{"property shorthand should support NaN shorthand", `({ NaN }).NaN`, `NaN`, `local ____exports = {}
____exports.__result = ({NaN = 0 / 0}).NaN
return ____exports`, false, false},
		{"property shorthand should support Infinity shorthand", `({ Infinity }).Infinity`, `Infinity`, `local ____exports = {}
____exports.__result = ({Infinity = math.huge}).Infinity
return ____exports`, false, false},
		{"object literal property access (\"{x: \\\"foobar\\\"}.x\")", `{x: "foobar"}.x`, `"foobar"`, `local ____exports = {}
____exports.__result = ({x = "foobar"}).x
return ____exports`, false, false},
		{"object literal property access (\"{x: \\\"foobar\\\"}[\\\"x\\\"]\")", `{x: "foobar"}["x"]`, `"foobar"`, `local ____exports = {}
____exports.__result = ({x = "foobar"}).x
return ____exports`, false, false},
		{"object literal property access (\"{x: () => \\\"foobar\\\"}.x()\")", `{x: () => "foobar"}.x()`, `"foobar"`, `local ____exports = {}
____exports.__result = ({x = function() return "foobar" end}):x()
return ____exports`, false, false},
		{"object literal property access (\"{x: () => \\\"foobar\\\"}[\\\"x\\\"]()\")", `{x: () => "foobar"}["x"]()`, `"foobar"`, `local ____exports = {}
local ____self_0 = {x = function() return "foobar" end}
____exports.__result = ____self_0.x(____self_0)
return ____exports`, false, false},
	})

	batchExpectFunctions(t, []funcTestCase{
		{"object literal with function call to get key", `const myFunc = () => "a";
        return { [myFunc() + "b"]: 3 };`, `{ab = 3}`, `local ____exports = {}
function ____exports.__main(self)
    local function myFunc()
        return "a"
    end
    return {[myFunc(nil) .. "b"] = 3}
end
return ____exports`, false, false},
		{"object literal with shorthand property", `const x = 5;
        return { x };`, `{x = 5}`, `local ____exports = {}
function ____exports.__main(self)
    local x = 5
    return {x = x}
end
return ____exports`, false, false},
		{"property shorthand should support property shorthand", `const x = 1;
            const o = { x };
            return o.x;`, `1`, `local ____exports = {}
function ____exports.__main(self)
    local x = 1
    local o = {x = x}
    return o.x
end
return ____exports`, false, false},
		{"undefined as object key", `const foo = {undefined: "foo"};
        return foo.undefined;`, `"foo"`, `local ____exports = {}
function ____exports.__main(self)
    local foo = {undefined = "foo"}
    return foo.undefined
end
return ____exports`, false, false},
		{"noSelf in functions Explicit this: void parameter", `const obj: Record<string, (this: void, arg: string) => string> = {
                method(a) {
                    return a;
                },
                func: function(a) {
                    return a;
                },
                arrow: (a) => {
                    return a;
                }
            };
            return [obj.method("a") ?? "nil", obj.func("b") ?? "nil", obj.arrow("c") ?? "nil"];`, `{"a", "b", "c"}`, `local ____exports = {}
function ____exports.__main(self)
    local obj = {
        method = function(a)
            return a
        end,
        func = function(a)
            return a
        end,
        arrow = function(a)
            return a
        end
    }
    return {
        obj.method("a") or "nil",
        obj.func("b") or "nil",
        obj.arrow("c") or "nil"
    }
end
return ____exports`, false, false},
		{"noSelf in functions No self annotation", `const obj: Record<string, /** @noSelf */(arg: string) => string> = {
                method(a) {
                    return a;
                },
                func: function(a) {
                    return a;
                },
                arrow: (a) => {
                    return a;
                }
            };
            return [obj.method("a") ?? "nil", obj.func("b") ?? "nil", obj.arrow("c") ?? "nil"];`, `{"a", "b", "c"}`, `local ____exports = {}
function ____exports.__main(self)
    local obj = {
        method = function(self, a)
            return a
        end,
        func = function(self, a)
            return a
        end,
        arrow = function(____, a)
            return a
        end
    }
    return {
        obj:method("a") or "nil",
        obj:func("b") or "nil",
        obj:arrow("c") or "nil"
    }
end
return ____exports`, false, false},
		{"noSelf in functions individual function types", `interface FunctionContainer {
                method: (this: void, a: string) => string
                func: (this: void, a: string) => string
                arrow: (this: void, a: string) => string
            }

            const obj: FunctionContainer = {
                method(a) {
                    return a
                },
                func: function(a) {
                    return a
                },
                arrow: (a) => {
                    return a
                }
            }

            return [obj.method("a") ?? "nil", obj.func("b") ?? "nil", obj.arrow("c") ?? "nil"];`, `{"a", "b", "c"}`, `local ____exports = {}
function ____exports.__main(self)
    local obj = {
        method = function(a)
            return a
        end,
        func = function(a)
            return a
        end,
        arrow = function(a)
            return a
        end
    }
    return {
        obj.method("a") or "nil",
        obj.func("b") or "nil",
        obj.arrow("c") or "nil"
    }
end
return ____exports`, false, false},
	})

	batchExpectModules(t, []moduleTestCase{
		{"property shorthand should support export property shorthand", `export const x = 1;
            const o = { x };
            export const y = o.x;`, `{x = 1, y = 1}`, `local ____exports = {}
____exports.x = 1
local o = {x = ____exports.x}
____exports.y = o.x
return ____exports`, false, false},
	})

	t.Run("property shorthand should support _G shorthand", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `declare const _G: any;
export const __result = ({ _G })._G.foobar;`, `"foobar"`, WithLuaHeader(`foobar = "foobar"`), WithReturnExport("__result"))
	})
}
