// Code generated by scripts/migrate from extern/tstl/test/unit/language-extensions/pairsIterable.spec.ts. DO NOT EDIT.
package tstltest

import (
	"testing"

	"github.com/realcoldfry/tslua/internal/transpiler"
)

func TestEval_PairsIterable(t *testing.T) {
	t.Parallel()

	batchExpectDiagnostics(t, []diagTestCase{
		{"invalid LuaPairsIterable without destructuring (\"for (const s of testIterable) {}\")", "function", `const testIterable = {a1: "a2", b1: "b2", c1: "c2"} as unknown as LuaPairsIterable<string, string>;

        for (const s of testIterable) {}`, []int32{100025}, []string{`local ____exports = {}
function ____exports.__main(self)
    local testIterable = {a1 = "a2", b1 = "b2", c1 = "c2"}
    for ____ in pairs(testIterable) do
    end
end
return ____exports`}},
		{"invalid LuaPairsIterable without destructuring (\"let s; for (s of testIterable) {}\")", "function", `const testIterable = {a1: "a2", b1: "b2", c1: "c2"} as unknown as LuaPairsIterable<string, string>;

        let s; for (s of testIterable) {}`, []int32{100025}, []string{`local ____exports = {}
function ____exports.__main(self)
    local testIterable = {a1 = "a2", b1 = "b2", c1 = "c2"}
    local s
    for ____ in pairs(testIterable) do
    end
end
return ____exports`}},
	}, WithLanguageExtensions())

	batchExpectCodegen(t, []codegenTestCase{
		{"invalid LuaPairsIterable without destructuring (\"for (const s of testIterable) {}\")", "function", `const testIterable = {a1: "a2", b1: "b2", c1: "c2"} as unknown as LuaPairsIterable<string, string>;

        for (const s of testIterable) {}`, nil, nil, nil, nil},
		{"invalid LuaPairsIterable without destructuring (\"let s; for (s of testIterable) {}\")", "function", `const testIterable = {a1: "a2", b1: "b2", c1: "c2"} as unknown as LuaPairsIterable<string, string>;

        let s; for (s of testIterable) {}`, nil, nil, nil, nil},
	}, WithLanguageExtensions())

	t.Run("pairs iterable", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `const testIterable = {a1: "a2", b1: "b2", c1: "c2"} as unknown as LuaPairsIterable<string, string>;

        const results: Record<string, string> = {};
        for (const [k, v] of testIterable) {
            results[k] = v;
        }
        return results;`, `{a1 = "a2", b1 = "b2", c1 = "c2"}`, WithLanguageExtensions())
	})

	t.Run("pairs iterable with external control variable", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `const testIterable = {a1: "a2", b1: "b2", c1: "c2"} as unknown as LuaPairsIterable<string, string>;

        const results: Record<string, string> = {};
        let k: string, v: string;
        for ([k, v] of testIterable) {
            results[k] = v;
        }
        return results;`, `{a1 = "a2", b1 = "b2", c1 = "c2"}`, WithLanguageExtensions())
	})

	t.Run("pairs iterable function forward", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `const testIterable = {a1: "a2", b1: "b2", c1: "c2"} as unknown as LuaPairsIterable<string, string>;

        function forward() { return testIterable; }
        const results: Record<string, string> = {};
        for (const [k, v] of forward()) {
            results[k] = v;
        }
        return results;`, `{a1 = "a2", b1 = "b2", c1 = "c2"}`, WithLanguageExtensions())
	})

	t.Run("pairs iterable function indirect forward", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `const testIterable = {a1: "a2", b1: "b2", c1: "c2"} as unknown as LuaPairsIterable<string, string>;

        function forward() { const iter = testIterable; return iter; }
        const results: Record<string, string> = {};
        for (const [k, v] of forward()) {
            results[k] = v;
        }
        return results;`, `{a1 = "a2", b1 = "b2", c1 = "c2"}`, WithLanguageExtensions())
	})

	t.Run("pairs iterable arrow function forward", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `const testIterable = {a1: "a2", b1: "b2", c1: "c2"} as unknown as LuaPairsIterable<string, string>;

        const forward = () => testIterable;
        const results: Record<string, string> = {};
        for (const [k, v] of forward()) {
            results[k] = v;
        }
        return results;`, `{a1 = "a2", b1 = "b2", c1 = "c2"}`, WithLanguageExtensions())
	})

	t.Run("pairs iterable with __pairs metamethod", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `class PairsTest  {
            __pairs() {
                const kvp = [ ["a1", "a2"], ["b1", "b2"], ["c1", "c2"] ];
                let i = 0;
                return () => {
                    if (i < kvp.length) {
                        const [k, v] = kvp[i++];
                        return $multi(k, v);
                    }
                };
            }
        }
        const tester = new PairsTest() as PairsTest & LuaPairsIterable<string, string>;
        const results: Record<string, string> = {};
        for (const [k, v] of tester) {
            results[k] = v;
        }
        return results;`, `{a1 = "a2", b1 = "b2", c1 = "c2"}`, WithLanguageExtensions(), WithLuaTarget(transpiler.LuaTargetLua53))
	})

	t.Run("pairs key iterable", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `const testKeyIterable = {a1: true, b1: true, c1: true} as unknown as LuaPairsKeyIterable<string>;

        const results: Record<string, boolean> = {};
        for (const k of testKeyIterable) {
            results[k] = true;
        }
        return results;`, `{a1 = true, b1 = true, c1 = true}`, WithLanguageExtensions())
	})

	t.Run("pairs key iterable with external control variable", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `const testKeyIterable = {a1: true, b1: true, c1: true} as unknown as LuaPairsKeyIterable<string>;

        const results: Record<string, boolean> = {};
        let k: string;
        for (k of testKeyIterable) {
            results[k] = true;
        }
        return results;`, `{a1 = true, b1 = true, c1 = true}`, WithLanguageExtensions())
	})

	t.Run("pairs key iterable function forward", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `const testKeyIterable = {a1: true, b1: true, c1: true} as unknown as LuaPairsKeyIterable<string>;

        function forward() { return testKeyIterable; }
        const results: Record<string, boolean> = {};
        for (const k of forward()) {
            results[k] = true;
        }
        return results;`, `{a1 = true, b1 = true, c1 = true}`, WithLanguageExtensions())
	})

	t.Run("pairs key iterable function indirect forward", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `const testKeyIterable = {a1: true, b1: true, c1: true} as unknown as LuaPairsKeyIterable<string>;

        function forward() { const iter = testKeyIterable; return iter; }
        const results: Record<string, boolean> = {};
        for (const k of forward()) {
            results[k] = true;
        }
        return results;`, `{a1 = true, b1 = true, c1 = true}`, WithLanguageExtensions())
	})

	t.Run("pairs key iterable arrow function forward", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `const testKeyIterable = {a1: true, b1: true, c1: true} as unknown as LuaPairsKeyIterable<string>;

        const forward = () => testKeyIterable;
        const results: Record<string, boolean> = {};
        for (const k of forward()) {
            results[k] = true;
        }
        return results;`, `{a1 = true, b1 = true, c1 = true}`, WithLanguageExtensions())
	})

	t.Run("pairs key iterable with __pairs metamethod", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `class PairsTest  {
            __pairs() {
                const kvp = [ ["a1", true], ["b1", true], ["c1", true] ];
                let i = 0;
                return () => {
                    if (i < kvp.length) {
                        const [k, v] = kvp[i++];
                        return $multi(k, v);
                    }
                };
            }
        }
        const tester = new PairsTest() as PairsTest & LuaPairsKeyIterable<string>;
        const results: Record<string, boolean> = {};
        for (const k of tester) {
            results[k] = true;
        }
        return results;`, `{a1 = true, b1 = true, c1 = true}`, WithLanguageExtensions(), WithLuaTarget(transpiler.LuaTargetLua53))
	})
}
