// Code generated by scripts/migrate from extern/tstl/test/unit/printer/sourcemaps.spec.ts. DO NOT EDIT.
package tstltest

import "testing"

func TestEval_Sourcemaps(t *testing.T) {
	t.Parallel()

	t.Run("Inline sourcemaps", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function abc() {
            return def();
        }

        function def() {
            return "foo";
        }

        return abc();`, `"foo"`, WithAllowDiagnostics(), WithOptions(map[string]any{"inlineSourceMap": true}))
	})
}
