// Code generated by scripts/migrate from extern/tstl/test/unit/statements.spec.ts. DO NOT EDIT.
package tstltest

import "testing"

func TestEval_Statements(t *testing.T) {
	t.Parallel()

	batchExpectFunctions(t, []funcTestCase{
		{"Block statement", `let a = 4;
        { let a = 42; }
        return a;`, `4`, `local ____exports = {}
function ____exports.__main(self)
    local a = 4
    do
        local a = 42
    end
    return a
end
return ____exports`, false, false},
	})
}
