// Code generated by scripts/migrate from extern/tstl/test/unit/language-extensions/table.spec.ts. DO NOT EDIT.
package tstltest

import "testing"

func TestEval_Table(t *testing.T) {
	t.Parallel()

	batchExpectDiagnostics(t, []diagTestCase{
		{"LuaTableGet & LuaTableSet extensions invalid use (\"const foo: unknown = getTable;\")", "module", `declare const getTable: LuaTableGet<{}, string, number>;
            const foo: unknown = getTable;`, []int32{100035}, []string{`foo = getTable`}},
		{"LuaTableGet & LuaTableSet extensions invalid use (\"const foo = `${getTable}`;\")", "module", "declare const getTable: LuaTableGet<{}, string, number>;\n            const foo = `${getTable}`;", []int32{100035}, nil},
		{"LuaTableGet & LuaTableSet extensions invalid use (\"declare function foo(getTable: LuaTableGet<{}, string, number>): void; foo(getTable);\")", "module", `declare const getTable: LuaTableGet<{}, string, number>;
            declare function foo(getTable: LuaTableGet<{}, string, number>): void; foo(getTable);`, []int32{100035}, []string{`foo(_G, getTable)`}},
		{"LuaTableGet & LuaTableSet extensions invalid use (\"const foo = (getTable as any)(1, 2);\")", "module", `declare const getTable: LuaTableGet<{}, string, number>;
            const foo = (getTable as any)(1, 2);`, []int32{100035}, []string{`foo = getTable(_G, 1, 2)`}},
		{"LuaTableGet & LuaTableSet extensions invalid use (\"const foo = [getTable];\")", "module", `declare const getTable: LuaTableGet<{}, string, number>;
            const foo = [getTable];`, []int32{100035}, []string{`foo = {getTable}`}},
		{"LuaTableHas extension invalid use (\"const foo: unknown = tableHas;\")", "module", `declare const tableHas: LuaTableHas<{}, string>;
            const foo: unknown = tableHas;`, []int32{100035}, []string{`foo = tableHas`}},
		{"LuaTableHas extension invalid use (\"const foo = `${tableHas}`;\")", "module", "declare const tableHas: LuaTableHas<{}, string>;\n            const foo = `${tableHas}`;", []int32{100035}, nil},
		{"LuaTableHas extension invalid use (\"declare function foo(tableHas: LuaTableHas<{}, string>): void; foo(tableHas);\")", "module", `declare const tableHas: LuaTableHas<{}, string>;
            declare function foo(tableHas: LuaTableHas<{}, string>): void; foo(tableHas);`, []int32{100035}, []string{`foo(_G, tableHas)`}},
		{"LuaTableHas extension invalid use (\"const foo = (tableHas as any)(1, 2);\")", "module", `declare const tableHas: LuaTableHas<{}, string>;
            const foo = (tableHas as any)(1, 2);`, []int32{100035}, []string{`foo = tableHas(_G, 1, 2)`}},
		{"LuaTableHas extension invalid use (\"const foo = [tableHas];\")", "module", `declare const tableHas: LuaTableHas<{}, string>;
            const foo = [tableHas];`, []int32{100035}, []string{`foo = {tableHas}`}},
		{"LuaTableHas extension invalid use method assignment (\"LuaTable<string, number>\")", "module", `const table = new LuaTable<string, number>();
                const has = table.has;`, []int32{100035}, []string{`____table = {}
has = ____table.has`}},
		{"LuaTableHas extension invalid use method assignment (\"LuaMap<string, number>\")", "module", `const table = new LuaMap<string, number>();
                const has = table.has;`, []int32{100035}, []string{`____table = {}
has = ____table.has`}},
		{"LuaTableHas extension invalid use method assignment (\"LuaSet<string>\")", "module", `const table = new LuaSet<string>();
                const has = table.has;`, []int32{100035}, []string{`____table = {}
has = ____table.has`}},
		{"LuaTableHas extension invalid use method expression (\"LuaTable<string, number>\")", "module", `const table = new LuaTable<string, number>();
                ["a", "b", "c"].map(table.has);`, []int32{100035}, []string{`local ____lualib = require("lualib_bundle")
local __TS__ArrayMap = ____lualib.__TS__ArrayMap
____table = {}
__TS__ArrayMap({"a", "b", "c"}, ____table.has)`}},
		{"LuaTableHas extension invalid use method expression (\"LuaMap<string, number>\")", "module", `const table = new LuaMap<string, number>();
                ["a", "b", "c"].map(table.has);`, []int32{100035}, []string{`local ____lualib = require("lualib_bundle")
local __TS__ArrayMap = ____lualib.__TS__ArrayMap
____table = {}
__TS__ArrayMap({"a", "b", "c"}, ____table.has)`}},
		{"LuaTableHas extension invalid use method expression (\"LuaSet<string>\")", "module", `const table = new LuaSet<string>();
                ["a", "b", "c"].map(table.has);`, []int32{100035}, []string{`local ____lualib = require("lualib_bundle")
local __TS__ArrayMap = ____lualib.__TS__ArrayMap
____table = {}
__TS__ArrayMap({"a", "b", "c"}, ____table.has)`}},
		{"LuaTable extension interface LuaTable in strict mode does not accept key type that could be nil (\"null\")", "expression", `new LuaTable<null, unknown>()`, nil, []string{`local ____exports = {}
____exports.__result = {}
return ____exports`}},
		{"LuaTable extension interface LuaTable in strict mode does not accept key type that could be nil (\"null\")", "expression", `new LuaTable<null, unknown>()`, nil, []string{`local ____exports = {}
____exports.__result = {}
return ____exports`}},
		{"LuaTable extension interface LuaTable in strict mode does not accept key type that could be nil (\"undefined\")", "expression", `new LuaTable<undefined, unknown>()`, nil, []string{`local ____exports = {}
____exports.__result = {}
return ____exports`}},
		{"LuaTable extension interface LuaTable in strict mode does not accept key type that could be nil (\"undefined\")", "expression", `new LuaTable<undefined, unknown>()`, nil, []string{`local ____exports = {}
____exports.__result = {}
return ____exports`}},
		{"LuaTable extension interface LuaTable in strict mode does not accept key type that could be nil (\"number | undefined\")", "expression", `new LuaTable<number | undefined, unknown>()`, nil, []string{`local ____exports = {}
____exports.__result = {}
return ____exports`}},
		{"LuaTable extension interface LuaTable in strict mode does not accept key type that could be nil (\"number | undefined\")", "expression", `new LuaTable<number | undefined, unknown>()`, nil, []string{`local ____exports = {}
____exports.__result = {}
return ____exports`}},
		{"LuaTable extension interface LuaTable in strict mode does not accept key type that could be nil (\"string | null\")", "expression", `new LuaTable<string | null, unknown>()`, nil, []string{`local ____exports = {}
____exports.__result = {}
return ____exports`}},
		{"LuaTable extension interface LuaTable in strict mode does not accept key type that could be nil (\"string | null\")", "expression", `new LuaTable<string | null, unknown>()`, nil, []string{`local ____exports = {}
____exports.__result = {}
return ____exports`}},
		{"LuaTable extension interface LuaTable in strict mode does not accept key type that could be nil (\"unknown\")", "expression", `new LuaTable<unknown, unknown>()`, nil, []string{`local ____exports = {}
____exports.__result = {}
return ____exports`}},
		{"LuaTable extension interface LuaTable in strict mode does not accept key type that could be nil (\"unknown\")", "expression", `new LuaTable<unknown, unknown>()`, nil, []string{`local ____exports = {}
____exports.__result = {}
return ____exports`}},
		{"does not crash on invalid extension use global function", "module", `declare const op: LuaTableGet<{}, string, any>
        op({})`, nil, nil},
		{"does not crash on invalid extension use method", "module", `const left = {} as {
            op: LuaTableGet<{}, string, any>
        }
        left.op()`, nil, []string{`left = {}`}},
	}, WithLanguageExtensions())

	batchExpectCodegen(t, []codegenTestCase{
		{"LuaTableGet & LuaTableSet extensions invalid use (\"const foo: unknown = getTable;\")", "module", `declare const getTable: LuaTableGet<{}, string, number>;
            const foo: unknown = getTable;`, nil, nil, nil, nil},
		{"LuaTableGet & LuaTableSet extensions invalid use (\"declare function foo(getTable: LuaTableGet<{}, string, number>): void; foo(getTable);\")", "module", `declare const getTable: LuaTableGet<{}, string, number>;
            declare function foo(getTable: LuaTableGet<{}, string, number>): void; foo(getTable);`, nil, nil, nil, nil},
		{"LuaTableGet & LuaTableSet extensions invalid use (\"const foo = (getTable as any)(1, 2);\")", "module", `declare const getTable: LuaTableGet<{}, string, number>;
            const foo = (getTable as any)(1, 2);`, nil, nil, nil, nil},
		{"LuaTableGet & LuaTableSet extensions invalid use (\"const foo = [getTable];\")", "module", `declare const getTable: LuaTableGet<{}, string, number>;
            const foo = [getTable];`, nil, nil, nil, nil},
		{"LuaTableHas extension invalid use (\"const foo: unknown = tableHas;\")", "module", `declare const tableHas: LuaTableHas<{}, string>;
            const foo: unknown = tableHas;`, nil, nil, nil, nil},
		{"LuaTableHas extension invalid use (\"declare function foo(tableHas: LuaTableHas<{}, string>): void; foo(tableHas);\")", "module", `declare const tableHas: LuaTableHas<{}, string>;
            declare function foo(tableHas: LuaTableHas<{}, string>): void; foo(tableHas);`, nil, nil, nil, nil},
		{"LuaTableHas extension invalid use (\"const foo = (tableHas as any)(1, 2);\")", "module", `declare const tableHas: LuaTableHas<{}, string>;
            const foo = (tableHas as any)(1, 2);`, nil, nil, nil, nil},
		{"LuaTableHas extension invalid use (\"const foo = [tableHas];\")", "module", `declare const tableHas: LuaTableHas<{}, string>;
            const foo = [tableHas];`, nil, nil, nil, nil},
		{"LuaTableHas extension invalid use method assignment (\"LuaTable<string, number>\")", "module", `const table = new LuaTable<string, number>();
                const has = table.has;`, nil, nil, nil, nil},
		{"LuaTableHas extension invalid use method assignment (\"LuaMap<string, number>\")", "module", `const table = new LuaMap<string, number>();
                const has = table.has;`, nil, nil, nil, nil},
		{"LuaTableHas extension invalid use method assignment (\"LuaSet<string>\")", "module", `const table = new LuaSet<string>();
                const has = table.has;`, nil, nil, nil, nil},
		{"LuaTableHas extension invalid use method expression (\"LuaTable<string, number>\")", "module", `const table = new LuaTable<string, number>();
                ["a", "b", "c"].map(table.has);`, nil, nil, nil, nil},
		{"LuaTableHas extension invalid use method expression (\"LuaMap<string, number>\")", "module", `const table = new LuaMap<string, number>();
                ["a", "b", "c"].map(table.has);`, nil, nil, nil, nil},
		{"LuaTableHas extension invalid use method expression (\"LuaSet<string>\")", "module", `const table = new LuaSet<string>();
                ["a", "b", "c"].map(table.has);`, nil, nil, nil, nil},
		{"LuaTable extension interface LuaTable in strict mode does not accept key type that could be nil (\"null\")", "expression", `new LuaTable<null, unknown>()`, nil, nil, nil, nil},
		{"LuaTable extension interface LuaTable in strict mode does not accept key type that could be nil (\"null\")", "expression", `new LuaTable<null, unknown>()`, nil, nil, nil, nil},
		{"LuaTable extension interface LuaTable in strict mode does not accept key type that could be nil (\"undefined\")", "expression", `new LuaTable<undefined, unknown>()`, nil, nil, nil, nil},
		{"LuaTable extension interface LuaTable in strict mode does not accept key type that could be nil (\"undefined\")", "expression", `new LuaTable<undefined, unknown>()`, nil, nil, nil, nil},
		{"LuaTable extension interface LuaTable in strict mode does not accept key type that could be nil (\"number | undefined\")", "expression", `new LuaTable<number | undefined, unknown>()`, nil, nil, nil, nil},
		{"LuaTable extension interface LuaTable in strict mode does not accept key type that could be nil (\"number | undefined\")", "expression", `new LuaTable<number | undefined, unknown>()`, nil, nil, nil, nil},
		{"LuaTable extension interface LuaTable in strict mode does not accept key type that could be nil (\"string | null\")", "expression", `new LuaTable<string | null, unknown>()`, nil, nil, nil, nil},
		{"LuaTable extension interface LuaTable in strict mode does not accept key type that could be nil (\"string | null\")", "expression", `new LuaTable<string | null, unknown>()`, nil, nil, nil, nil},
		{"LuaTable extension interface LuaTable in strict mode does not accept key type that could be nil (\"unknown\")", "expression", `new LuaTable<unknown, unknown>()`, nil, nil, nil, nil},
		{"LuaTable extension interface LuaTable in strict mode does not accept key type that could be nil (\"unknown\")", "expression", `new LuaTable<unknown, unknown>()`, nil, nil, nil, nil},
		{"does not crash on invalid extension use method", "module", `const left = {} as {
            op: LuaTableGet<{}, string, any>
        }
        left.op()`, nil, nil, nil, nil},
	}, WithLanguageExtensions())

	t.Run("LuaTableGet & LuaTableSet extensions stand-alone function", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `declare const getTable: LuaTableGet<{}, string, number>;
            declare const setTable: LuaTableSet<{}, string, number>;
            const tbl = {};
            setTable(tbl, "foo", 3);
            const result = getTable(tbl, "foo");
            export { result }`, `3`, WithLanguageExtensions(), WithReturnExport("result"))
	})

	t.Run("LuaTableGet & LuaTableSet extensions stand-alone function with preceding statements", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `declare const setTable: LuaTableSet<{}, string, string>;
            const values: any[] = []
            const tbl: any = {};
            const get = (value: any) => {
                values.push(value)
                return value
            }
            let x = "a"
            setTable(tbl, x += "b", x += "c")
            export const result = tbl.ab`, `"abc"`, WithLanguageExtensions(), WithReturnExport("result"))
	})

	t.Run("LuaTableGet & LuaTableSet extensions namespace function", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `declare namespace Table {
                export const get: LuaTableGet<{}, string, number>;
                export const set: LuaTableSet<{}, string, number>;
            }
            const tbl = {};
            Table.set(tbl, "foo", 3);
            const result = Table.get(tbl, "foo");
            export { result }`, `3`, WithLanguageExtensions(), WithReturnExport("result"))
	})

	t.Run("LuaTableGet & LuaTableSet extensions method", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `interface Table {
                get: LuaTableGetMethod<string, number>;
                set: LuaTableSetMethod<string, number>;
            }
            const tbl = {} as Table;
            tbl.set("foo", 3);
            const result = tbl.get("foo");
            export { result }`, `3`, WithLanguageExtensions(), WithReturnExport("result"))
	})

	t.Run("LuaTableHas extension LuaTableHas standalone function", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `declare const tableHas: LuaTableHas<{}, string>;
            const table = { foo: "bar" };

            export const hasFoo = tableHas(table, "foo");
            export const hasBaz = tableHas(table, "baz");`, `{hasBaz = false, hasFoo = true}`, WithLanguageExtensions())
	})

	t.Run("LuaTableHas extension LuaTableHas nested expression", func(t *testing.T) {
		t.Parallel()
		expectModule(t, "declare const tableHas: LuaTableHas<{}, string>;\n            const table = { foo: \"bar\" };\n\n            export const result = `table has foo: ${tableHas(table, \"foo\")}`;", `{result = "table has foo: true"}`, WithLanguageExtensions())
	})

	t.Run("LuaTableHas extension LuaTableHas namespace function", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `declare namespace Table {
                export const tableHas: LuaTableHas<{}, string>;
            }
            const table = { foo: "bar" };

            export const hasFoo = Table.tableHas(table, "foo");
            export const hasBaz = Table.tableHas(table, "baz");`, `{hasBaz = false, hasFoo = true}`, WithLanguageExtensions())
	})

	t.Run("LuaTableHas extension LuaTableHasMethod method", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `interface TableWithHas {
                has: LuaTableHasMethod<string>;
                set: LuaTableSetMethod<string, number>;
            }
            const table = {} as TableWithHas;
            table.set("foo", 42);

            export const hasFoo = table.has("foo");
            export const hasBaz = table.has("baz");`, `{hasBaz = false, hasFoo = true}`, WithLanguageExtensions())
	})

	t.Run("LuaTableHas extension LuaTableHas as statement", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `declare const tableHas: LuaTableHas<{}, string>;
            const table = { foo: "bar" };

            let count = 0;
            function getKey() {
                count++;
                return "foo";
            }

            // The result is not captured, but the expression will be evaulated
            tableHas(table, getKey());

            export const numCalls = count;`, `{numCalls = 1}`, WithLanguageExtensions())
	})

	t.Run("LuaTableDelete extension LuaTableDelete standalone function", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `declare const tableDelete: LuaTableDelete<{}, string>;

            export const table = { foo: "bar", baz: "baz" };
            tableDelete(table, "foo");`, `{table = {baz = "baz"}}`, WithLanguageExtensions())
	})

	t.Run("LuaTableDelete extension LuaTableDelete namespace function", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `declare namespace Table {
                export const tableDelete: LuaTableDelete<{}, string>;
            }

            export const table = { foo: "bar", baz: "baz" };
            Table.tableDelete(table, "foo");`, `{table = {baz = "baz"}}`, WithLanguageExtensions())
	})

	t.Run("LuaTableDelete extension LuaTableDeleteMethod method", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `interface TableWithDelete {
                delete: LuaTableDeleteMethod<string>;
                set: LuaTableSetMethod<string, number>;
            }
            export const table = {} as TableWithDelete;
            table.set("foo", 42);
            table.set("bar", 12);
            table.delete("foo");`, `{table = {bar = 12}}`, WithLanguageExtensions())
	})

	t.Run("LuaTableAddKey extension LuaTableAddKey standalone function", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `declare const tableAddKey: LuaTableAddKey<{}, string>;
            export const table = { foo: "bar" };
            tableAddKey(table, "baz");`, `{table = {baz = true, foo = "bar"}}`, WithLanguageExtensions())
	})

	t.Run("LuaTableAddKey extension LuaTableAddKey namespace function", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `declare namespace Table {
                export const tableAddKey: LuaTableAddKey<{}, string>;
            }
            export const table = { foo: "bar" };
            Table.tableAddKey(table, "baz");`, `{table = {baz = true, foo = "bar"}}`, WithLanguageExtensions())
	})

	t.Run("LuaTableAddKey extension LuaTableAddKey method", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `interface TableWithAddKey {
                addKey: LuaTableAddKeyMethod<string>;
            }
            export const table = {} as TableWithAddKey;
            table.addKey("bar");`, `{table = {bar = true}}`, WithLanguageExtensions())
	})

	t.Run("LuaIsEmpty extension LuaIsEmpty standalone function", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `declare const isTableEmpty: LuaTableIsEmpty<{}>;

            const table = { foo: "bar", baz: "baz" };
            const emptyTable = {};

            export const result = [isTableEmpty(table), isTableEmpty(emptyTable)];`, `{result = {false, true}}`, WithLanguageExtensions())
	})

	t.Run("LuaIsEmpty extension LuaIsEmpty namespace function", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `declare namespace Table {
                export const isTableEmpty: LuaTableIsEmpty<{}>;
            }

            const table = { foo: "bar", baz: "baz" };
            const emptyTable = {};

            export const result = [Table.isTableEmpty(table), Table.isTableEmpty(emptyTable)];`, `{result = {false, true}}`, WithLanguageExtensions())
	})

	t.Run("LuaIsEmpty extension LuaTableIsEmptyMethod method", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `interface TableWithIsEmpty {
                isEmpty: LuaTableIsEmptyMethod;
                set: LuaTableSetMethod<string, number>;
            }
            const table = {} as TableWithIsEmpty;
            table.set("foo", 42);
            table.set("bar", 12);

            const emptyTable = {} as TableWithIsEmpty;

            export const result = [table.isEmpty(), emptyTable.isEmpty()];`, `{result = {false, true}}`, WithLanguageExtensions())
	})

	t.Run("Table extensions use as expression functions used as expression", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `declare const func: LuaTableAddKey<{}, string>
            export const result = func({}, "foo")`, `nil`, WithLanguageExtensions(), WithReturnExport("result"), WithAllowDiagnostics())
	})

	t.Run("Table extensions use as expression functions used as expression", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `declare const func: LuaTableAddKey<{}, string>
            export const result = "truthy" && func({}, "foo")`, `nil`, WithLanguageExtensions(), WithReturnExport("result"), WithAllowDiagnostics())
	})

	t.Run("Table extensions use as expression functions used as expression", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `declare const func: LuaTableDelete<{}, string>
            export const result = func({}, "foo")`, `true`, WithLanguageExtensions(), WithReturnExport("result"), WithAllowDiagnostics())
	})

	t.Run("Table extensions use as expression functions used as expression", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `declare const func: LuaTableDelete<{}, string>
            export const result = "truthy" && func({}, "foo")`, `true`, WithLanguageExtensions(), WithReturnExport("result"), WithAllowDiagnostics())
	})

	t.Run("Table extensions use as expression functions used as expression", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `declare const func: LuaTableSet<{}, string, number>
            export const result = func({}, "foo", 3)`, `nil`, WithLanguageExtensions(), WithReturnExport("result"), WithAllowDiagnostics())
	})

	t.Run("Table extensions use as expression functions used as expression", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `declare const func: LuaTableIsEmpty<{}>
            export const result = func({})`, `true`, WithLanguageExtensions(), WithReturnExport("result"), WithAllowDiagnostics())
	})

	t.Run("Table extensions use as expression functions used as expression", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `declare const func: LuaTableIsEmpty<{}>
            export const result = func({ foo: "bar", baz: "baz" })`, `false`, WithLanguageExtensions(), WithReturnExport("result"), WithAllowDiagnostics())
	})

	t.Run("Table extensions use as expression functions used as expression", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `declare const func: LuaTableIsEmpty<{}>
            export const result = "truthy" && func({})`, `true`, WithLanguageExtensions(), WithReturnExport("result"), WithAllowDiagnostics())
	})

	t.Run("Table extensions use as expression methods used as expression", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `const tbl = {} as { func: LuaTableDeleteMethod<string> }
            export const result = tbl.func("foo")`, `true`, WithLanguageExtensions(), WithReturnExport("result"))
	})

	t.Run("Table extensions use as expression methods used as expression", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `const tbl = {} as { func: LuaTableSetMethod<string, number> }
            export const result = tbl.func("foo", 3)`, `nil`, WithLanguageExtensions(), WithReturnExport("result"))
	})

	t.Run("Table extensions use as expression methods used as expression", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `const tbl = {} as { func: LuaTableAddKeyMethod<string> }
            export const result = tbl.func("foo")`, `nil`, WithLanguageExtensions(), WithReturnExport("result"))
	})

	t.Run("Table extensions use as expression methods used as expression", func(t *testing.T) {
		t.Parallel()
		expectModule(t, `const tbl = {} as { func: LuaTableIsEmpty<{}> }
            export const result = tbl.func({})`, `true`, WithLanguageExtensions(), WithReturnExport("result"))
	})

	t.Run("LuaTable extension interface untyped table", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `const tbl = new LuaTable();
            tbl.set("foo", 3);
            return tbl.get("foo");`, `3`, WithLanguageExtensions())
	})

	t.Run("LuaTable extension interface typed table", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `const tbl = new LuaTable<string, number>();
            tbl.set("foo", 3);
            return tbl.get("foo");`, `3`, WithLanguageExtensions())
	})

	t.Run("LuaTable extension interface typed table in type declaration", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function fill(tbl: LuaTable<string, number>) {
                tbl.set("foo", 3);
                return tbl;
            }
            return fill(new LuaTable()).get("foo");`, `3`, WithLanguageExtensions())
	})

	t.Run("LuaTable extension interface object keyed table", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `interface Key { keyStr: string }
            const key: Key = {keyStr: "foo"};
            const tbl = new LuaTable<Key, number>();
            tbl.set(key, 3);
            return tbl.get(key);`, `3`, WithLanguageExtensions())
	})

	t.Run("LuaTable extension interface table length", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `const tbl = new LuaTable<number, string>();
            tbl.set(1, "foo");
            tbl.set(3, "bar");
            return tbl.length();`, `1`, WithLanguageExtensions())
	})

	t.Run("LuaTable extension interface table has", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `const tbl = new LuaTable<number, string>();
            tbl.set(3, "foo");
            return [tbl.has(1), tbl.has(3)];`, `{false, true}`, WithLanguageExtensions())
	})

	t.Run("LuaTable extension interface table delete", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `const tbl = new LuaTable<string, number>();
            tbl.set("foo", 1);
            tbl.set("bar", 3);
            tbl.set("baz", 5);
            tbl.delete("bar");
            tbl.delete("foo");
            return tbl;`, `{baz = 5}`, WithLanguageExtensions())
	})

	t.Run("LuaTable extension interface table isEmpty", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `const tbl = new LuaTable<string, number>();
            tbl.set("foo", 1);

            const emptyTbl = new LuaTable<string, number>();

            return [tbl.isEmpty(), emptyTbl.isEmpty()];`, `{false, true}`, WithLanguageExtensions())
	})

	t.Run("LuaTable extension interface table add", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `const tbl = new LuaSet<string>();
            tbl.add("foo");
            return tbl`, `{foo = true}`, WithLanguageExtensions())
	})

	t.Run("LuaTable extension interface table pairs iterate", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `const tbl = new LuaTable<string, number>();
            tbl.set("foo", 1);
            tbl.set("bar", 3);
            tbl.set("baz", 5);
            const results: Record<string, number> = {};
            for (const [k, v] of tbl) {
                results[k] = v;
            }
            return results;`, `{bar = 3, baz = 5, foo = 1}`, WithLanguageExtensions())
	})

	t.Run("call on optional table with strictNullChecks (undefined)", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function getFoo(): LuaSet<string> | undefined {
            return undefined
        }
        const foo = getFoo()
        foo?.add("foo")
        return foo?.has("foo")`, `nil`, WithLanguageExtensions(), WithOptions(map[string]any{"strictNullChecks": true}))
	})

	t.Run("call on optional table with strictNullChecks (new LuaSet())", func(t *testing.T) {
		t.Parallel()
		expectFunction(t, `function getFoo(): LuaSet<string> | undefined {
            return new LuaSet()
        }
        const foo = getFoo()
        foo?.add("foo")
        return foo?.has("foo")`, `true`, WithLanguageExtensions(), WithOptions(map[string]any{"strictNullChecks": true}))
	})
}
