// Code generated by scripts/migrate from extern/tstl/test/unit/templateLiterals.spec.ts. DO NOT EDIT.
package tstltest

import "testing"

func TestEval_TemplateLiterals(t *testing.T) {
	t.Parallel()

	batchExpectExpressions(t, []exprTestCase{
		{"template literal ({\"a\":12,\"b\":23,\"c\":43})", "`${12} ${23} test ${43}`", `"12 23 test 43"`, `local ____exports = {}
____exports.__result = (((12 .. " ") .. 23) .. " test ") .. 43
return ____exports`, false, false},
		{"template literal ({\"a\":\"test\",\"b\":\"hello\",\"c\":\"bye\"})", "`${\"test\"} ${\"hello\"} test ${\"bye\"}`", `"test hello test bye"`, `local ____exports = {}
____exports.__result = ((("test" .. " ") .. "hello") .. " test ") .. "bye"
return ____exports`, false, false},
		{"template literal ({\"a\":\"test\",\"b\":42,\"c\":\"bye\"})", "`${\"test\"} ${42} test ${\"bye\"}`", `"test 42 test bye"`, `local ____exports = {}
____exports.__result = ((("test" .. " ") .. 42) .. " test ") .. "bye"
return ____exports`, false, false},
		{"template literal ({\"a\":\"test\",\"b\":42,\"c\":12})", "`${\"test\"} ${42} test ${12}`", `"test 42 test 12"`, `local ____exports = {}
____exports.__result = ((("test" .. " ") .. 42) .. " test ") .. 12
return ____exports`, false, false},
		{"template literal ({\"a\":\"test\",\"b\":42,\"c\":true})", "`${\"test\"} ${42} test ${true}`", `"test 42 test true"`, `local ____exports = {}
____exports.__result = ((("test" .. " ") .. 42) .. " test ") .. tostring(true)
return ____exports`, false, false},
		{"template literal ({\"a\":false,\"b\":42,\"c\":12})", "`${false} ${42} test ${12}`", `"false 42 test 12"`, `local ____exports = {}
____exports.__result = (((tostring(false) .. " ") .. 42) .. " test ") .. 12
return ____exports`, false, false},
		{"template literal property access (\"`foo${'bar'}`.length\")", "`foo${'bar'}`.length", `6`, `local ____exports = {}
____exports.__result = #("foo" .. "bar")
return ____exports`, false, false},
		{"template literal property access (\"`foo${'bar'}`.repeat(2)\")", "`foo${'bar'}`.repeat(2)", `"foobarfoobar"`, `local ____exports = {}
____exports.__result = string.rep(
    "foo" .. "bar",
    math.floor(2)
)
return ____exports`, false, false},
	})

	batchExpectFunctions(t, []funcTestCase{
		{"template literal with expression (\"a++\")", "let a = 3;\n        return `value${a++}`;", `"value3"`, `local ____exports = {}
function ____exports.__main(self)
    local a = 3
    local ____a_0 = a
    a = ____a_0 + 1
    return "value" .. tostring(____a_0)
end
return ____exports`, false, false},
		{"template literal with expression (\"a--\")", "let a = 3;\n        return `value${a--}`;", `"value3"`, `local ____exports = {}
function ____exports.__main(self)
    local a = 3
    local ____a_0 = a
    a = ____a_0 - 1
    return "value" .. tostring(____a_0)
end
return ____exports`, false, false},
		{"template literal with expression (\"--a\")", "let a = 3;\n        return `value${--a}`;", `"value2"`, `local ____exports = {}
function ____exports.__main(self)
    local a = 3
    a = a - 1
    return "value" .. tostring(a)
end
return ____exports`, false, false},
		{"template literal with expression (\"++a\")", "let a = 3;\n        return `value${++a}`;", `"value4"`, `local ____exports = {}
function ____exports.__main(self)
    local a = 3
    a = a + 1
    return "value" .. tostring(a)
end
return ____exports`, false, false},
		{"tagged template literal (\"func``\")", "function func(strings: TemplateStringsArray, ...expressions: any[]) {\n            return { strings: [...strings], raw: strings.raw, expressions };\n        }\n\n        const obj = { func };\n        return func``;", `{expressions = {}, raw = {""}, strings = {""}}`, `local ____exports = {}
function ____exports.__main(self)
    local function func(self, strings, ...)
        local expressions = {...}
        return {
            strings = {table.unpack(strings)},
            raw = strings.raw,
            expressions = expressions
        }
    end
    local obj = {func = func}
    return func(nil, {[1] = "", raw = {""}})
end
return ____exports`, false, false},
		{"tagged template literal (\"func`hello`\")", "function func(strings: TemplateStringsArray, ...expressions: any[]) {\n            return { strings: [...strings], raw: strings.raw, expressions };\n        }\n\n        const obj = { func };\n        return func`hello`;", `{expressions = {}, raw = {"hello"}, strings = {"hello"}}`, `local ____exports = {}
function ____exports.__main(self)
    local function func(self, strings, ...)
        local expressions = {...}
        return {
            strings = {table.unpack(strings)},
            raw = strings.raw,
            expressions = expressions
        }
    end
    local obj = {func = func}
    return func(nil, {[1] = "hello", raw = {"hello"}})
end
return ____exports`, false, false},
		{"tagged template literal (\"func`hello ${1} ${2} ${3}`\")", "function func(strings: TemplateStringsArray, ...expressions: any[]) {\n            return { strings: [...strings], raw: strings.raw, expressions };\n        }\n\n        const obj = { func };\n        return func`hello ${1} ${2} ${3}`;", `{expressions = {1, 2, 3}, raw = {"hello ", " ", " ", ""}, strings = {"hello ", " ", " ", ""}}`, `local ____exports = {}
function ____exports.__main(self)
    local function func(self, strings, ...)
        local expressions = {...}
        return {
            strings = {table.unpack(strings)},
            raw = strings.raw,
            expressions = expressions
        }
    end
    local obj = {func = func}
    return func(
        nil,
        {
            [1] = "hello ",
            [2] = " ",
            [3] = " ",
            [4] = "",
            raw = {"hello ", " ", " ", ""}
        },
        1,
        2,
        3
    )
end
return ____exports`, false, false},
		{"tagged template literal (\"func`hello ${(() => 'iife')()}`\")", "function func(strings: TemplateStringsArray, ...expressions: any[]) {\n            return { strings: [...strings], raw: strings.raw, expressions };\n        }\n\n        const obj = { func };\n        return func`hello ${(() => 'iife')()}`;", `{expressions = {"iife"}, raw = {"hello ", ""}, strings = {"hello ", ""}}`, `local ____exports = {}
function ____exports.__main(self)
    local function func(self, strings, ...)
        local expressions = {...}
        return {
            strings = {table.unpack(strings)},
            raw = strings.raw,
            expressions = expressions
        }
    end
    local obj = {func = func}
    return func(
        nil,
        {[1] = "hello ", [2] = "", raw = {"hello ", ""}},
        (function() return "iife" end)(nil)
    )
end
return ____exports`, false, false},
		{"tagged template literal (\"func`hello ${1 + 2 + 3} arithmetic`\")", "function func(strings: TemplateStringsArray, ...expressions: any[]) {\n            return { strings: [...strings], raw: strings.raw, expressions };\n        }\n\n        const obj = { func };\n        return func`hello ${1 + 2 + 3} arithmetic`;", `{expressions = {6}, raw = {"hello ", " arithmetic"}, strings = {"hello ", " arithmetic"}}`, `local ____exports = {}
function ____exports.__main(self)
    local function func(self, strings, ...)
        local expressions = {...}
        return {
            strings = {table.unpack(strings)},
            raw = strings.raw,
            expressions = expressions
        }
    end
    local obj = {func = func}
    return func(nil, {[1] = "hello ", [2] = " arithmetic", raw = {"hello ", " arithmetic"}}, 1 + 2 + 3)
end
return ____exports`, false, false},
		{"tagged template literal (\"func`begin ${'middle'} end`\")", "function func(strings: TemplateStringsArray, ...expressions: any[]) {\n            return { strings: [...strings], raw: strings.raw, expressions };\n        }\n\n        const obj = { func };\n        return func`begin ${'middle'} end`;", `{expressions = {"middle"}, raw = {"begin ", " end"}, strings = {"begin ", " end"}}`, `local ____exports = {}
function ____exports.__main(self)
    local function func(self, strings, ...)
        local expressions = {...}
        return {
            strings = {table.unpack(strings)},
            raw = strings.raw,
            expressions = expressions
        }
    end
    local obj = {func = func}
    return func(nil, {[1] = "begin ", [2] = " end", raw = {"begin ", " end"}}, "middle")
end
return ____exports`, false, false},
		{"tagged template literal (\"func`hello ${func`hello`}`\")", "function func(strings: TemplateStringsArray, ...expressions: any[]) {\n            return { strings: [...strings], raw: strings.raw, expressions };\n        }\n\n        const obj = { func };\n        return func`hello ${func`hello`}`;", `{expressions = {{expressions = {}, raw = {"hello"}, strings = {"hello"}}}, raw = {"hello ", ""}, strings = {"hello ", ""}}`, `local ____exports = {}
function ____exports.__main(self)
    local function func(self, strings, ...)
        local expressions = {...}
        return {
            strings = {table.unpack(strings)},
            raw = strings.raw,
            expressions = expressions
        }
    end
    local obj = {func = func}
    return func(
        nil,
        {[1] = "hello ", [2] = "", raw = {"hello ", ""}},
        func(nil, {[1] = "hello", raw = {"hello"}})
    )
end
return ____exports`, false, false},
		{"tagged template literal (\"func`hello \\\\u00A9`\")", "function func(strings: TemplateStringsArray, ...expressions: any[]) {\n            return { strings: [...strings], raw: strings.raw, expressions };\n        }\n\n        const obj = { func };\n        return func`hello \\u00A9`;", `{expressions = {}, raw = {"hello \\u00A9"}, strings = {"hello ©"}}`, `local ____exports = {}
function ____exports.__main(self)
    local function func(self, strings, ...)
        local expressions = {...}
        return {
            strings = {table.unpack(strings)},
            raw = strings.raw,
            expressions = expressions
        }
    end
    local obj = {func = func}
    return func(nil, {[1] = "hello ©", raw = {"hello \\u00A9"}})
end
return ____exports`, false, false},
		{"tagged template literal (\"func`hello $ { }`\")", "function func(strings: TemplateStringsArray, ...expressions: any[]) {\n            return { strings: [...strings], raw: strings.raw, expressions };\n        }\n\n        const obj = { func };\n        return func`hello $ { }`;", `{expressions = {}, raw = {"hello $ { }"}, strings = {"hello $ { }"}}`, `local ____exports = {}
function ____exports.__main(self)
    local function func(self, strings, ...)
        local expressions = {...}
        return {
            strings = {table.unpack(strings)},
            raw = strings.raw,
            expressions = expressions
        }
    end
    local obj = {func = func}
    return func(nil, {[1] = "hello $ { }", raw = {"hello $ { }"}})
end
return ____exports`, false, false},
		{"tagged template literal (\"func`hello { ${'brackets'} }`\")", "function func(strings: TemplateStringsArray, ...expressions: any[]) {\n            return { strings: [...strings], raw: strings.raw, expressions };\n        }\n\n        const obj = { func };\n        return func`hello { ${'brackets'} }`;", `{expressions = {"brackets"}, raw = {"hello { ", " }"}, strings = {"hello { ", " }"}}`, `local ____exports = {}
function ____exports.__main(self)
    local function func(self, strings, ...)
        local expressions = {...}
        return {
            strings = {table.unpack(strings)},
            raw = strings.raw,
            expressions = expressions
        }
    end
    local obj = {func = func}
    return func(nil, {[1] = "hello { ", [2] = " }", raw = {"hello { ", " }"}}, "brackets")
end
return ____exports`, false, false},
		{"tagged template literal (\"func`hello \\\\``\")", "function func(strings: TemplateStringsArray, ...expressions: any[]) {\n            return { strings: [...strings], raw: strings.raw, expressions };\n        }\n\n        const obj = { func };\n        return func`hello \\``;", "{expressions = {}, raw = {\"hello \\\\`\"}, strings = {\"hello `\"}}", "local ____exports = {}\nfunction ____exports.__main(self)\n    local function func(self, strings, ...)\n        local expressions = {...}\n        return {\n            strings = {table.unpack(strings)},\n            raw = strings.raw,\n            expressions = expressions\n        }\n    end\n    local obj = {func = func}\n    return func(nil, {[1] = \"hello `\", raw = {\"hello \\\\`\"}})\nend\nreturn ____exports", false, false},
		{"tagged template literal (\"obj.func`hello ${'propertyAccessExpression'}`\")", "function func(strings: TemplateStringsArray, ...expressions: any[]) {\n            return { strings: [...strings], raw: strings.raw, expressions };\n        }\n\n        const obj = { func };\n        return obj.func`hello ${'propertyAccessExpression'}`;", `{expressions = {"propertyAccessExpression"}, raw = {"hello ", ""}, strings = {"hello ", ""}}`, `local ____exports = {}
function ____exports.__main(self)
    local function func(self, strings, ...)
        local expressions = {...}
        return {
            strings = {table.unpack(strings)},
            raw = strings.raw,
            expressions = expressions
        }
    end
    local obj = {func = func}
    return obj:func({[1] = "hello ", [2] = "", raw = {"hello ", ""}}, "propertyAccessExpression")
end
return ____exports`, false, false},
		{"tagged template literal (\"obj['func']`hello ${'elementAccessExpression'}`\")", "function func(strings: TemplateStringsArray, ...expressions: any[]) {\n            return { strings: [...strings], raw: strings.raw, expressions };\n        }\n\n        const obj = { func };\n        return obj['func']`hello ${'elementAccessExpression'}`;", `{expressions = {"elementAccessExpression"}, raw = {"hello ", ""}, strings = {"hello ", ""}}`, `local ____exports = {}
function ____exports.__main(self)
    local function func(self, strings, ...)
        local expressions = {...}
        return {
            strings = {table.unpack(strings)},
            raw = strings.raw,
            expressions = expressions
        }
    end
    local obj = {func = func}
    return obj.func(obj, {[1] = "hello ", [2] = "", raw = {"hello ", ""}}, "elementAccessExpression")
end
return ____exports`, false, false},
		{"tagged template literal function context (\"func`noSelfParameter`\")", "function func(this: void, strings: TemplateStringsArray) {\n                return [...strings];\n            }\n\n            const obj = { func };\n            return func`noSelfParameter`;", `{"noSelfParameter"}`, `local ____exports = {}
function ____exports.__main(self)
    local function func(strings)
        return {table.unpack(strings)}
    end
    local obj = {func = func}
    return func({[1] = "noSelfParameter", raw = {"noSelfParameter"}})
end
return ____exports`, false, false},
		{"tagged template literal function context (\"obj.func`noSelfParameter`\")", "function func(this: void, strings: TemplateStringsArray) {\n                return [...strings];\n            }\n\n            const obj = { func };\n            return obj.func`noSelfParameter`;", `{"noSelfParameter"}`, `local ____exports = {}
function ____exports.__main(self)
    local function func(strings)
        return {table.unpack(strings)}
    end
    local obj = {func = func}
    return obj.func({[1] = "noSelfParameter", raw = {"noSelfParameter"}})
end
return ____exports`, false, false},
		{"tagged template literal function context (\"obj[`func`]`noSelfParameter`\")", "function func(this: void, strings: TemplateStringsArray) {\n                return [...strings];\n            }\n\n            const obj = { func };\n            return obj[`func`]`noSelfParameter`;", `{"noSelfParameter"}`, `local ____exports = {}
function ____exports.__main(self)
    local function func(strings)
        return {table.unpack(strings)}
    end
    local obj = {func = func}
    return obj.func({[1] = "noSelfParameter", raw = {"noSelfParameter"}})
end
return ____exports`, false, false},
		{"template span expect tostring for non string type (\"number\")", "// @ts-ignore\n        const msg = \"\" as number;\n        return `${msg}`;", `""`, `local ____exports = {}
function ____exports.__main(self)
    local msg = ""
    return tostring(msg)
end
return ____exports`, false, false},
		{"template span expect tostring for non string type (\"string | any\")", "// @ts-ignore\n        const msg = \"\" as string | any;\n        return `${msg}`;", `""`, `local ____exports = {}
function ____exports.__main(self)
    local msg = ""
    return tostring(msg)
end
return ____exports`, false, false},
		{"template span expect no tostring for string-like type (\"string\")", "// @ts-ignore\n            const msg = \"\" as string;\n            return `${msg}`;", `""`, `local ____exports = {}
function ____exports.__main(self)
    local msg = ""
    return msg
end
return ____exports`, false, false},
		{"template span expect no tostring for string-like type (\"'string literal type'\")", "// @ts-ignore\n            const msg = \"\" as 'string literal type';\n            return `${msg}`;", `""`, `local ____exports = {}
function ____exports.__main(self)
    local msg = ""
    return msg
end
return ____exports`, false, false},
		{"template span expect no tostring for string-like type (\"string & unknown\")", "// @ts-ignore\n            const msg = \"\" as string & unknown;\n            return `${msg}`;", `""`, `local ____exports = {}
function ____exports.__main(self)
    local msg = ""
    return msg
end
return ____exports`, false, false},
	})

	batchExpectModules(t, []moduleTestCase{
		{"tagged template literal returned from function call (#1637)", "function templateFactory() {\n            return (template: TemplateStringsArray) => {\n                return \"bar\";\n            }\n        }\n        export let result = templateFactory()`foo`;", `{result = "bar"}`, `local ____exports = {}
local function templateFactory(self)
    return function(____, template)
        return "bar"
    end
end
____exports.result = templateFactory(nil)(nil, {[1] = "foo", raw = {"foo"}})
return ____exports`, false, false},
		{"tagged template literal returned from function call, explicit no context (#1637)", "function templateFactory() {\n            return function(this: void, template: TemplateStringsArray) {\n                return \"bar\";\n            }\n        }\n        export let result = templateFactory()`foo`;", `{result = "bar"}`, `local ____exports = {}
local function templateFactory(self)
    return function(template)
        return "bar"
    end
end
____exports.result = templateFactory(nil)({[1] = "foo", raw = {"foo"}})
return ____exports`, false, false},
	})

	batchExpectCodegen(t, []codegenTestCase{
		{"template span expect tostring for non string type (\"number\")", "function", "// @ts-ignore\n        const msg = \"\" as number;\n        return `${msg}`;", []string{`tostring`}, nil, nil, nil},
		{"template span expect tostring for non string type (\"string | any\")", "function", "// @ts-ignore\n        const msg = \"\" as string | any;\n        return `${msg}`;", []string{`tostring`}, nil, nil, nil},
		{"template span expect no tostring for string-like type (\"string\")", "function", "// @ts-ignore\n            const msg = \"\" as string;\n            return `${msg}`;", nil, []string{`tostring`}, nil, nil},
		{"template span expect no tostring for string-like type (\"'string literal type'\")", "function", "// @ts-ignore\n            const msg = \"\" as 'string literal type';\n            return `${msg}`;", nil, []string{`tostring`}, nil, nil},
		{"template span expect no tostring for string-like type (\"string & unknown\")", "function", "// @ts-ignore\n            const msg = \"\" as string & unknown;\n            return `${msg}`;", nil, []string{`tostring`}, nil, nil},
	})
}
