// Code generated by scripts/migrate from extern/tstl/test/unit/using.spec.ts. DO NOT EDIT.
package tstltest

import "testing"

func TestEval_Using(t *testing.T) {
	t.Parallel()

	batchExpectFunctions(t, []funcTestCase{
		{"await-using with nested async arrow that also has await-using (runtime divergence)", `const logs: any[] = [];
        async function getA(): Promise<AsyncDisposable> {
            return { [Symbol.asyncDispose]: async () => {} };
        }
        async function outer(): Promise<number> {
            await using a = await getA();
            const inner = async (): Promise<number> => {
                await using b = await getA();
                return 42;
            };
            return inner();
        }
        outer().then(v => logs.push(v));
        return logs;`, `{42}`, `local ____lualib = require("lualib_bundle")
local __TS__UsingAsync = ____lualib.__TS__UsingAsync
local __TS__Symbol = ____lualib.__TS__Symbol
local Symbol = ____lualib.Symbol
local __TS__AsyncAwaiter = ____lualib.__TS__AsyncAwaiter
local __TS__Await = ____lualib.__TS__Await
local ____exports = {}
function ____exports.__main(self)
    local logs = {}
    local function getA(self)
        return __TS__AsyncAwaiter(function(____awaiter_resolve)
            return ____awaiter_resolve(
                nil,
                {[Symbol.asyncDispose] = function()
                    return __TS__AsyncAwaiter(function(____awaiter_resolve)
                    end)
                end}
            )
        end)
    end
    local function outer(self)
        return __TS__AsyncAwaiter(function(____awaiter_resolve)
            return ____awaiter_resolve(
                nil,
                __TS__Await(__TS__UsingAsync(
                    nil,
                    function(a)
                        return __TS__AsyncAwaiter(function(____awaiter_resolve)
                            local function inner()
                                return __TS__AsyncAwaiter(function(____awaiter_resolve)
                                    return ____awaiter_resolve(
                                        nil,
                                        __TS__Await(__TS__UsingAsync(
                                            nil,
                                            function(b)
                                                return __TS__AsyncAwaiter(function(____awaiter_resolve)
                                                    return ____awaiter_resolve(nil, 42)
                                                end)
                                            end,
                                            __TS__Await(getA(nil))
                                        ))
                                    )
                                end)
                            end
                            return ____awaiter_resolve(
                                nil,
                                inner(nil)
                            )
                        end)
                    end,
                    __TS__Await(getA(nil))
                ))
            )
        end)
    end
    local ____self_1 = outer(nil)
    ____self_1["then"](
        ____self_1,
        function(____, v)
            local ____temp_0 = #logs + 1
            logs[____temp_0] = v
            return ____temp_0
        end
    )
    return logs
end
return ____exports`, false, false},
		{"works with disposable classes (#1584)", `const log: string[] = [];
        
        class Scoped {
            action(): void {
                log.push("action")
            }
            [Symbol.dispose]() {
                log.push("cleanup")
            }
        }

        function TestScoped(): void {
            using s = new Scoped();
            s.action();
        }

        TestScoped();
        return log;`, `{"action", "cleanup"}`, `local ____lualib = require("lualib_bundle")
local __TS__Using = ____lualib.__TS__Using
local __TS__Class = ____lualib.__TS__Class
local __TS__Symbol = ____lualib.__TS__Symbol
local Symbol = ____lualib.Symbol
local __TS__New = ____lualib.__TS__New
local ____exports = {}
function ____exports.__main(self)
    local log = {}
    local Scoped = __TS__Class()
    Scoped.name = "Scoped"
    function Scoped.prototype.____constructor(self)
    end
    function Scoped.prototype.action(self)
        log[#log + 1] = "action"
    end
    Scoped.prototype[Symbol.dispose] = function(self)
        log[#log + 1] = "cleanup"
    end
    local function TestScoped(self)
        return __TS__Using(
            nil,
            function(s)
                s:action()
            end,
            __TS__New(Scoped)
        )
    end
    TestScoped(nil)
    return log
end
return ____exports`, false, false},
	})

	batchExpectModules(t, []moduleTestCase{
		{"works on root level (#1632)", `export let disposed = false;

        class A {
            [Symbol.dispose] = function (this: A) {
                disposed = true;
            }
        }
        using a = new A();`, `{disposed = true}`, `local ____lualib = require("lualib_bundle")
local __TS__Using = ____lualib.__TS__Using
local __TS__Class = ____lualib.__TS__Class
local __TS__Symbol = ____lualib.__TS__Symbol
local Symbol = ____lualib.Symbol
local __TS__New = ____lualib.__TS__New
local ____exports = {}
____exports.disposed = false
local A = __TS__Class()
A.name = "A"
function A.prototype.____constructor(self)
    self[Symbol.dispose] = function(self)
        ____exports.disposed = true
    end
end
__TS__Using(
    nil,
    function(a)
    end,
    __TS__New(A)
)
return ____exports`, false, false},
	})

	batchRunTests(t, []batchTestCase{
		{name: "using disposes object at end of function", tsCode: "\n    export const logs: string[] = [];\n\n    function loggedDisposable(id: string): Disposable {\n        logs.push(`Creating ${id}`);\n\n        return {\n            [Symbol.dispose]() {\n                logs.push(`Disposing ${id}`);\n            }\n        }\n    }\nfunction func() {\n            using a = loggedDisposable(\"a\");\n            using b = loggedDisposable(\"b\");\n\n            logs.push(\"function content\");\n        }\n        \n        func();", accessor: `mod`, want: `{logs = {"Creating a", "Creating b", "function content", "Disposing b", "Disposing a"}}`, refLua: `local ____lualib = require("lualib_bundle")
local __TS__Using = ____lualib.__TS__Using
local __TS__Symbol = ____lualib.__TS__Symbol
local Symbol = ____lualib.Symbol
local ____exports = {}
____exports.logs = {}
local function loggedDisposable(self, id)
    local ____exports_logs_0 = ____exports.logs
    ____exports_logs_0[#____exports_logs_0 + 1] = "Creating " .. id
    return {[Symbol.dispose] = function(self)
        local ____exports_logs_1 = ____exports.logs
        ____exports_logs_1[#____exports_logs_1 + 1] = "Disposing " .. id
    end}
end
local function func(self)
    return __TS__Using(
        nil,
        function(a)
            return __TS__Using(
                nil,
                function(b)
                    local ____exports_logs_2 = ____exports.logs
                    ____exports_logs_2[#____exports_logs_2 + 1] = "function content"
                end,
                loggedDisposable(nil, "b")
            )
        end,
        loggedDisposable(nil, "a")
    )
end
func(nil)
return ____exports`},
		{name: "handles multi-variable declarations", tsCode: "\n    export const logs: string[] = [];\n\n    function loggedDisposable(id: string): Disposable {\n        logs.push(`Creating ${id}`);\n\n        return {\n            [Symbol.dispose]() {\n                logs.push(`Disposing ${id}`);\n            }\n        }\n    }\nfunction func() {\n            using a = loggedDisposable(\"a\"), b = loggedDisposable(\"b\");\n\n            logs.push(\"function content\");\n        }\n        \n        func();", accessor: `mod`, want: `{logs = {"Creating a", "Creating b", "function content", "Disposing b", "Disposing a"}}`, refLua: `local ____lualib = require("lualib_bundle")
local __TS__Using = ____lualib.__TS__Using
local __TS__Symbol = ____lualib.__TS__Symbol
local Symbol = ____lualib.Symbol
local ____exports = {}
____exports.logs = {}
local function loggedDisposable(self, id)
    local ____exports_logs_0 = ____exports.logs
    ____exports_logs_0[#____exports_logs_0 + 1] = "Creating " .. id
    return {[Symbol.dispose] = function(self)
        local ____exports_logs_1 = ____exports.logs
        ____exports_logs_1[#____exports_logs_1 + 1] = "Disposing " .. id
    end}
end
local function func(self)
    return __TS__Using(
        nil,
        function(a, b)
            local ____exports_logs_2 = ____exports.logs
            ____exports_logs_2[#____exports_logs_2 + 1] = "function content"
        end,
        loggedDisposable(nil, "a"),
        loggedDisposable(nil, "b")
    )
end
func(nil)
return ____exports`},
		{name: "using disposes object at end of nested block", tsCode: "\n    export const logs: string[] = [];\n\n    function loggedDisposable(id: string): Disposable {\n        logs.push(`Creating ${id}`);\n\n        return {\n            [Symbol.dispose]() {\n                logs.push(`Disposing ${id}`);\n            }\n        }\n    }\nfunction func() {\n            using a = loggedDisposable(\"a\");\n\n            {\n                using b = loggedDisposable(\"b\");\n                logs.push(\"nested block\");\n            }\n\n            logs.push(\"function content\");\n        }\n        \n        func();", accessor: `mod`, want: `{logs = {"Creating a", "Creating b", "nested block", "Disposing b", "function content", "Disposing a"}}`, refLua: `local ____lualib = require("lualib_bundle")
local __TS__Using = ____lualib.__TS__Using
local __TS__Symbol = ____lualib.__TS__Symbol
local Symbol = ____lualib.Symbol
local ____exports = {}
____exports.logs = {}
local function loggedDisposable(self, id)
    local ____exports_logs_0 = ____exports.logs
    ____exports_logs_0[#____exports_logs_0 + 1] = "Creating " .. id
    return {[Symbol.dispose] = function(self)
        local ____exports_logs_1 = ____exports.logs
        ____exports_logs_1[#____exports_logs_1 + 1] = "Disposing " .. id
    end}
end
local function func(self)
    return __TS__Using(
        nil,
        function(a)
            do
                __TS__Using(
                    nil,
                    function(b)
                        local ____exports_logs_2 = ____exports.logs
                        ____exports_logs_2[#____exports_logs_2 + 1] = "nested block"
                    end,
                    loggedDisposable(nil, "b")
                )
            end
            local ____exports_logs_3 = ____exports.logs
            ____exports_logs_3[#____exports_logs_3 + 1] = "function content"
        end,
        loggedDisposable(nil, "a")
    )
end
func(nil)
return ____exports`},
		{name: "using does not affect function return value", tsCode: "\n    export const logs: string[] = [];\n\n    function loggedDisposable(id: string): Disposable {\n        logs.push(`Creating ${id}`);\n\n        return {\n            [Symbol.dispose]() {\n                logs.push(`Disposing ${id}`);\n            }\n        }\n    }\nfunction func() {\n            using a = loggedDisposable(\"a\");\n            using b = loggedDisposable(\"b\");\n\n            logs.push(\"function content\");\n\n            return \"success\";\n        }\n        \n        export const result = func();", accessor: `mod`, want: `{logs = {"Creating a", "Creating b", "function content", "Disposing b", "Disposing a"}, result = "success"}`, refLua: `local ____lualib = require("lualib_bundle")
local __TS__Using = ____lualib.__TS__Using
local __TS__Symbol = ____lualib.__TS__Symbol
local Symbol = ____lualib.Symbol
local ____exports = {}
____exports.logs = {}
local function loggedDisposable(self, id)
    local ____exports_logs_0 = ____exports.logs
    ____exports_logs_0[#____exports_logs_0 + 1] = "Creating " .. id
    return {[Symbol.dispose] = function(self)
        local ____exports_logs_1 = ____exports.logs
        ____exports_logs_1[#____exports_logs_1 + 1] = "Disposing " .. id
    end}
end
local function func(self)
    return __TS__Using(
        nil,
        function(a)
            return __TS__Using(
                nil,
                function(b)
                    local ____exports_logs_2 = ____exports.logs
                    ____exports_logs_2[#____exports_logs_2 + 1] = "function content"
                    return "success"
                end,
                loggedDisposable(nil, "b")
            )
        end,
        loggedDisposable(nil, "a")
    )
end
____exports.result = func(nil)
return ____exports`},
		{name: "using disposes even when error happens", tsCode: "\n    export const logs: string[] = [];\n\n    function loggedDisposable(id: string): Disposable {\n        logs.push(`Creating ${id}`);\n\n        return {\n            [Symbol.dispose]() {\n                logs.push(`Disposing ${id}`);\n            }\n        }\n    }\nfunction func() {\n            using a = loggedDisposable(\"a\");\n            using b = loggedDisposable(\"b\");\n\n            throw \"test-induced exception\";\n        }\n\n        try \n        {\n            func();\n        }\n        catch (e)\n        {\n            logs.push(`caught exception: ${e}`);\n        }", accessor: `mod`, want: `{logs = {"Creating a", "Creating b", "Disposing b", "Disposing a", "caught exception: test-induced exception"}}`, refLua: `local ____lualib = require("lualib_bundle")
local __TS__Using = ____lualib.__TS__Using
local __TS__Symbol = ____lualib.__TS__Symbol
local Symbol = ____lualib.Symbol
local ____exports = {}
____exports.logs = {}
local function loggedDisposable(self, id)
    local ____exports_logs_0 = ____exports.logs
    ____exports_logs_0[#____exports_logs_0 + 1] = "Creating " .. id
    return {[Symbol.dispose] = function(self)
        local ____exports_logs_1 = ____exports.logs
        ____exports_logs_1[#____exports_logs_1 + 1] = "Disposing " .. id
    end}
end
local function func(self)
    return __TS__Using(
        nil,
        function(a)
            return __TS__Using(
                nil,
                function(b)
                    error("test-induced exception", 0)
                end,
                loggedDisposable(nil, "b")
            )
        end,
        loggedDisposable(nil, "a")
    )
end
do
    local function ____catch(e)
        local ____exports_logs_2 = ____exports.logs
        ____exports_logs_2[#____exports_logs_2 + 1] = "caught exception: " .. tostring(e)
    end
    local ____try, ____hasReturned = pcall(function()
        func(nil)
    end)
    if not ____try then
        ____catch(____hasReturned)
    end
end
return ____exports`},
		{name: "await using can handle non-async disposables", tsCode: "\n    export const logs: string[] = [];\n\n    function loggedDisposable(id: string): Disposable {\n        logs.push(`Creating ${id}`);\n\n        return {\n            [Symbol.dispose]() {\n                logs.push(`Disposing ${id}`);\n            }\n        }\n    }\nasync function func() {\n            await using a = loggedDisposable(\"a\");\n\n            logs.push(\"function content\");\n        }\n        \n        func();", accessor: `mod`, want: `{logs = {"Creating a", "function content", "Disposing a"}}`, refLua: `local ____lualib = require("lualib_bundle")
local __TS__UsingAsync = ____lualib.__TS__UsingAsync
local __TS__Symbol = ____lualib.__TS__Symbol
local Symbol = ____lualib.Symbol
local __TS__AsyncAwaiter = ____lualib.__TS__AsyncAwaiter
local __TS__Await = ____lualib.__TS__Await
local ____exports = {}
____exports.logs = {}
local function loggedDisposable(self, id)
    local ____exports_logs_0 = ____exports.logs
    ____exports_logs_0[#____exports_logs_0 + 1] = "Creating " .. id
    return {[Symbol.dispose] = function(self)
        local ____exports_logs_1 = ____exports.logs
        ____exports_logs_1[#____exports_logs_1 + 1] = "Disposing " .. id
    end}
end
local function func(self)
    return __TS__AsyncAwaiter(function(____awaiter_resolve)
        return ____awaiter_resolve(
            nil,
            __TS__Await(__TS__UsingAsync(
                nil,
                function(a)
                    return __TS__AsyncAwaiter(function(____awaiter_resolve)
                        local ____exports_logs_2 = ____exports.logs
                        ____exports_logs_2[#____exports_logs_2 + 1] = "function content"
                    end)
                end,
                loggedDisposable(nil, "a")
            ))
        )
    end)
end
func(nil)
return ____exports`},
	})

	t.Run("await using disposes object with await at end of function", func(t *testing.T) {
		t.Parallel()
		expectModule(t, "\n    export const logs: string[] = [];\n\n    function loggedDisposable(id: string): Disposable {\n        logs.push(`Creating ${id}`);\n\n        return {\n            [Symbol.dispose]() {\n                logs.push(`Disposing ${id}`);\n            }\n        }\n    }\nlet disposeAsync: (() => void) | undefined;\n\n        function loggedAsyncDisposable(id: string): AsyncDisposable {\n            logs.push(`Creating ${id}`);\n\n            return {\n                [Symbol.asyncDispose]() {\n                    logs.push(`Disposing async ${id}`);\n                    return new Promise(resolve => {\n                        disposeAsync = () => {\n                            logs.push(`Disposed ${id}`);\n                            resolve();\n                        };\n                    });\n                }\n            }\n        }\n\n        async function func() {\n            await using a = loggedAsyncDisposable(\"a\");\n\n            logs.push(\"function content\");\n            return \"function result\";\n        }\n        \n        const p = func().then(r => logs.push(\"promise resolved\", r));\n\n        logs.push(\"function returned\");\n\n        disposeAsync!();", `{logs = {"Creating a", "function content", "Disposing async a", "function returned", "Disposed a", "promise resolved", "function result"}}`, WithOptions(map[string]any{"luaLibImport": "inline"}))
	})
}
