// Code generated by scripts/migrate from extern/tstl/test/unit/void.spec.ts. DO NOT EDIT.
package tstltest

import "testing"

func TestEval_Void(t *testing.T) {
	t.Parallel()

	batchExpectExpressions(t, []exprTestCase{
		{"void evaluates to undefined (\"0\")", `void (0)`, `nil`, `local ____exports = {}
____exports.__result = nil
return ____exports`, false, false},
		{"void evaluates to undefined (\"1\")", `void (1)`, `nil`, `local ____exports = {}
____exports.__result = nil
return ____exports`, false, false},
		{"void evaluates to undefined (\"\\\"a\\\"\")", `void ("a")`, `nil`, `local ____exports = {}
____exports.__result = nil
return ____exports`, false, false},
		{"void works with lambdas", `void (() => {})()`, `nil`, `local ____exports = {};
(function()
end)(nil)
____exports.__result = nil
return ____exports`, false, false},
	})

	batchExpectFunctions(t, []funcTestCase{
		{"void applies to function declarations", `let result = 0;
        void function setResult() {
            result = 1;
        }();
        return result;`, `1`, `local ____exports = {}
function ____exports.__main(self)
    local result = 0;
    (function(self)
        result = 1
    end)(nil)
    return result
end
return ____exports`, false, false},
		{"void used to ignore function return values", `let result = 0;
        function setResult() {
            result = 1;
            return 3
        };

        void(setResult());

        return result;`, `1`, `local ____exports = {}
function ____exports.__main(self)
    local result = 0
    local function setResult(self)
        result = 1
        return 3
    end
    setResult(nil)
    return result
end
return ____exports`, false, false},
	})
}
