package luatest

import (
	"strings"
	"testing"

	"github.com/realcoldfry/tslua/internal/transpiler"
)

// TestUsing_Eval verifies using declarations work correctly, including
// edge cases around scope, hoisting, and symbol tracking inside the
// callback generated by the using transform.
func TestUsing_Eval(t *testing.T) {
	t.Parallel()

	cases := []struct {
		name string
		body string
		want string
	}{
		{
			"basic using disposes",
			`const log: string[] = [];
			const d = { [Symbol.dispose]() { log.push("disposed"); } };
			function run() {
				using x = d;
				log.push("body");
			}
			run();
			return log;`,
			`{"body", "disposed"}`,
		},
		{
			"using with hoisted function",
			`const log: string[] = [];
			function run() {
				using x = { [Symbol.dispose]() { log.push("disposed"); } };
				foo();
				function foo() { log.push("hoisted"); }
			}
			run();
			return log;`,
			`{"hoisted", "disposed"}`,
		},
		{
			"using with later variable reference",
			`function run() {
				using x = { [Symbol.dispose]() {} };
				foo();
				const val = 42;
				function foo() { return val; }
				return val;
			}
			return run();`,
			`42`,
		},
		{
			"using preserves return value",
			`function run() {
				using x = { [Symbol.dispose]() {} };
				return "hello";
			}
			return run();`,
			`"hello"`,
		},
		{
			"nested using in standalone block",
			`const log: string[] = [];
			function run() {
				using a = { [Symbol.dispose]() { log.push("a"); } };
				{
					using b = { [Symbol.dispose]() { log.push("b"); } };
					log.push("inner");
				}
				log.push("outer");
			}
			run();
			return log;`,
			`{"inner", "b", "outer", "a"}`,
		},
		{
			"multi-variable using",
			`const log: string[] = [];
			function run() {
				using a = { [Symbol.dispose]() { log.push("a"); } },
				      b = { [Symbol.dispose]() { log.push("b"); } };
				log.push("body");
			}
			run();
			return log;`,
			`{"body", "b", "a"}`,
		},
		{
			"using disposes on throw",
			`const log: string[] = [];
			function run() {
				using x = { [Symbol.dispose]() { log.push("disposed"); } };
				throw "oops";
			}
			try { run(); } catch(e) { log.push("caught"); }
			return log;`,
			`{"disposed", "caught"}`,
		},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			t.Parallel()

			lua := ExpectFunctionLua(t, c.body, c.want, Opts{})

			// Verify __TS__Using appears in generated Lua
			if !strings.Contains(lua, "__TS__Using") {
				t.Errorf("expected __TS__Using in output:\n%s", lua)
			}
		})
	}
}

// TestUsing_Codegen verifies specific structural properties of the generated Lua.
func TestUsing_Codegen(t *testing.T) {
	t.Parallel()

	t.Run("callback wraps remaining statements", func(t *testing.T) {
		t.Parallel()
		tsCode := `export function __main() {
			using x = { [Symbol.dispose]() {} };
			const a = 1;
			const b = 2;
			return a + b;
		}`
		results := TranspileTS(t, tsCode, Opts{})
		for _, r := range results {
			if !strings.HasSuffix(r.FileName, "main.ts") {
				continue
			}
			// The using should produce a return __TS__Using(nil, function(x) ... end, ...)
			if !strings.Contains(r.Lua, "return __TS__Using(") {
				t.Errorf("expected 'return __TS__Using(' in output:\n%s", r.Lua)
			}
			// Remaining statements should be inside the callback, not after it
			lines := strings.Split(r.Lua, "\n")
			foundUsing := false
			for _, line := range lines {
				trimmed := strings.TrimSpace(line)
				if strings.Contains(trimmed, "__TS__Using") {
					foundUsing = true
				}
				// After __TS__Using, there should be no bare local declarations at function scope
				if foundUsing && strings.HasPrefix(trimmed, "local a = ") {
					t.Errorf("found bare 'local a' after __TS__Using — should be inside callback:\n%s", r.Lua)
				}
			}
		}
	})

	t.Run("standalone block using does not return", func(t *testing.T) {
		t.Parallel()
		tsCode := `export function __main() {
			const log: string[] = [];
			{
				using x = { [Symbol.dispose]() { log.push("d"); } };
				log.push("inner");
			}
			log.push("after");
			return log;
		}`
		results := TranspileTS(t, tsCode, Opts{})
		for _, r := range results {
			if !strings.HasSuffix(r.FileName, "main.ts") {
				continue
			}
			lua := r.Lua
			// The standalone block should use expression statement, not return
			if strings.Contains(lua, "return __TS__Using") && !strings.Contains(lua, "return log") {
				t.Errorf("standalone block using should not be the only return:\n%s", lua)
			}
		}
	})

	t.Run("await using wraps callback in AsyncAwaiter", func(t *testing.T) {
		t.Parallel()
		tsCode := `export async function __main() {
			await using x = { [Symbol.asyncDispose]() { return Promise.resolve(); } };
			return "done";
		}`
		results := TranspileTS(t, tsCode, Opts{LuaTarget: transpiler.LuaTargetLua55})
		for _, r := range results {
			if !strings.HasSuffix(r.FileName, "main.ts") {
				continue
			}
			if !strings.Contains(r.Lua, "__TS__UsingAsync") {
				t.Errorf("expected __TS__UsingAsync in output:\n%s", r.Lua)
			}
			if !strings.Contains(r.Lua, "__TS__AsyncAwaiter") {
				t.Errorf("expected __TS__AsyncAwaiter in callback for await using:\n%s", r.Lua)
			}
		}
	})
}

// TestUsing_AsyncArrowReturnValue verifies that an async arrow body containing
// `await using` correctly propagates the return value. Arrow function bodies
// were going through the standalone-block path (shouldReturn=false), which
// dropped the value and resolved the promise to undefined instead of the
// returned value.
func TestUsing_AsyncArrowReturnValue(t *testing.T) {
	t.Parallel()

	body := `const log: string[] = [];
	function getD(): AsyncDisposable {
		return { [Symbol.asyncDispose]: async () => { log.push("d"); } };
	}
	async function run() {
		const inner = async () => {
			await using b = getD();
			return 42;
		};
		const result = await inner();
		log.push("result=" + String(result));
	}
	run();
	return log;`

	ExpectFunction(t, body, `{"d", "result=42"}`, Opts{
		LuaTarget: transpiler.LuaTargetLuaJIT,
	})
}
